### ISSUE TITLE
Describe purpose in README

### ISSUE THREAD

**Issue by ivan-m** [obsidiansystems/obelisk#1]
Just saw Ryan's talk on this at Lambda Jam, but there's no way of knowing if you stumble across this repo as to what it's for.

**Comment by sajidanower23** [comment]
Agreed. The `CONTRIBUTING.md` file needs more info as well, I suppose.

**Comment by ivan-m** [comment]
I think the purpose is satisfied by bf8f7ad50b46, but leaving this open for @sajidanower23's other points/questions.

**Comment by jacobstern** [comment]
I'd appreciate more clarification about the usage of `obelisk-backend`. Is it supposed to coexist with e.g. a REST server in the same repository?

**Comment by ryantrinkle** [comment]
@jacobstern The REST server should go in the backend module.  Right now, it's a fairly bare Snap server.  We typically start from there and build out additional services with REST and websockets.

**Comment by jacobstern** [comment]
Thanks @ryantrinkle! I think it would be helpful to indicate how to add e.g. a Servant entry point into the backend code since it's not clear to me from reading the skeleton.

**Comment by johnny555** [comment]
@jacobstern would you be able to use https://github.com/haskell-servant/servant-snap to add the servant entry point API?

**Comment by jacobstern** [comment]
@johnny555 Thanks, yeah that makes sense though it's not clear to me if the Obelisk lib backend allows extensibility in the Snap app?

**Comment by johnny555** [comment]
Yeah you might be right there, looking at `backend :: BackendConfig -> IO ()` from Obelisk.Backend it seems that there isn't a way to pass in a snaplet or something else to be run by snap here ...
