### ISSUE TITLE
'ob run' doesn't result in a browsable page on localhost:8080

### ISSUE THREAD

**Issue by Shoadi** [obsidiansystems/obelisk#1006]
- I am running NixOS 22.05 on current/updated version
- I installed obelisk as described and
- ...initialised an Obelisk project by 'ob init' in my ~/prj/ -folder
- assuming everything worked fine I went into my project folder and initiated an 'ob run' which seems to be running
`[user@OS:~/prj]$ ob run
./.obelisk/impl: command not cached, building ...
◒ Running nix-build on ./.obelisk/impl [command]
✔ Built on ./.obelisk/impl [command]`
Route should be fine: 
`[user@OS:~/prj]$ cat config/common/route
http://localhost:8000`

Though if I try to see something on chrome or brave it tells me that nothing is happening in here. Can someone enlighten and noobn't me please - how to make these basics work

**Comment by mankyKitty** [comment]
A couple of things that might help debug things... 

After you've run `ob run` and navigated to `http://localhost:8000` in your browser, do you see output similar to the following in your terminal:

```
Frontend running on http://localhost:8000/
127.0.0.1 - - [25/Nov/2022:11:33:39 +0000] "GET /static/main.css HTTP/1.1" 200 54 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
127.0.0.1 - - [25/Nov/2022:11:33:39 +0000] "GET /static/obelisk.jpg HTTP/1.1" 200 17351 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
127.0.0.1 - - [25/Nov/2022:11:33:39 +0000] "GET /favicon.ico HTTP/1.1" 200 5 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
```

Was there any output in the browser console in the dev tools that might provide some hints?

Another thing that's helpful is to use the `--verbose` flag when using `ob` to see a bit more about what is going on, like so:
```shell
$ ob run --verbose
```
That'll display a lot more information and should provide some insight. If can run that and post the output here we can debug this a bit more. :)

**Comment by Shoadi** [comment]
Ah here I was stupid and `$ ob run --verbose` brought light - ob was still building.

Thanks a lot for answering this and have a marvelous weekend. =)

**Comment by mankyKitty** [comment]
Glad it was simple ! :+1:
