### ISSUE TITLE
encoder for int newtype

### ISSUE THREAD

**Issue by rubenmoor** [obsidiansystems/obelisk#1013]
I have this `int` wrapped in a newtype:

```haskell
newtype StageIndex = StageIndex { unStageIndex :: Int }
  deriving stock (Eq, Generic, Ord)
  deriving newtype (Enum, FromJSON, ToJSON, FromHttpApiData, ToHttpApiData, Num, Read, Show)
```

For the use in this route:

```haskell
data FrontendRoute :: * -> * where
  FrontendRoute_Main  :: FrontendRoute ()
  FrontendRoute_DE    :: FrontendRoute StageIndex
```

and this is how i get it to work using `unsafeTshowEncoder`

```haskell
        FrontendRoute_DE   -> PathSegment "DE" $ singlePathSegmentEncoder . unsafeTshowEncoder
```

... which relies on the `Read` and `Show` instances via `GeneralizedNewtypeDeriving`, i.e. the url shows "/5" instead of "/StageIndex 5".

But is there a more elegant way that doesn't rely on `unsafeTshowEncoder`?

**Comment by ali-abrar** [comment]
There are a couple of things in `Obelisk.Route` that are relevant here: `unwrappedEncoder` and `integralEncoder`.

I'd start by adding a Wrapped instance to `StageIndex` so that we can use `unwrappedEncoder` to get access to the wrapped `Int`:

```haskell
newtype StageIndex = StageIndex { unStageIndex :: Int }
  deriving (Eq, Generic, Ord)

instance Wrapped StageIndex
```

Let's remove `unsafeTshowEncoder` and replace it with a hole:

```haskell
      FrontendRoute_DE -> PathSegment "DE" $ singlePathSegmentEncoder . _
```

The error message is:
```
    • Found hole:
        _ :: Encoder (Either Text) (Either Text) StageIndex Text
```

Now, let's add `unwrappedEncoder`:

```haskell
      FrontendRoute_DE -> PathSegment "DE" $ singlePathSegmentEncoder . _ . unwrappedEncoder
```

The error is now:
```
    • Found hole: _ :: Encoder (Either Text) (Either Text) Int Text
```

In other words, we need an encoder for an `Int`. If you were using `Integer`, we could use `integralEncoder`. That function is defined as:

```haskell
integralEncoder :: (MonadError Text parse, Applicative check, Integral a) => Encoder check parse a Integer
integralEncoder = reviewEncoder Numeric.Lens.integral
```

We can write something similar:

```haskell
reviewEncoder (Numeric.Lens.base 10)
```

Plugging that in to our route encoder:

```haskell
      FrontendRoute_DE -> PathSegment "DE" $ singlePathSegmentEncoder . _ . reviewEncoder (base 10) . unwrappedEncoder
```

and the error is now:

```
    • Found hole: _ :: Encoder (Either Text) (Either Text) String Text
```

For which we have `packTextEncoder`:

```haskell
      FrontendRoute_DE -> PathSegment "DE" $ singlePathSegmentEncoder . packTextEncoder . reviewEncoder (base 10) . unwrappedEncoder
```

**Comment by rubenmoor** [comment]
Awesome!

I got it to work according to your instructions like this

```haskell
        FrontendRoute_DE   -> PathSegment "DE" $ singlePathSegmentEncoder . wrappedIntEncoder
  where
    wrappedIntEncoder
      :: forall (check :: * -> *) (parse :: * -> *) text a
      . ( Applicative check
        , IsText text
        , Integral (Unwrapped a)
        , MonadError Text parse
        , Wrapped a
        )
      => Encoder check parse a text
    wrappedIntEncoder = packTextEncoder . reviewEncoder (base 10) . unwrappedEncoder
```

Even after changing the wrapped type from `Int` to `Integer`, I didn't find a way to employ `integralEncoder`. I still get

"Couldn't match type Integer with [Char]"

**Comment by ali-abrar** [comment]
You'd still need the `packTextEncoder` after `integralEncoder` -- i.e., switch out `reviewEncoder (base 10)` for `integralEncoder` in your code above.
