### ISSUE TITLE
Static assets are not loaded on Android

### ISSUE THREAD

**Issue by jecaro** [obsidiansystems/obelisk#1043]
I see the same behavior as #382: the image doesn't appear and the style in the CSS file is not applied implying that it is not loaded as well. This has been tested on Android 11. 

I can repro on those versions:
-  [v1.1.1.0](https://github.com/obsidiansystems/obelisk/releases/tag/v1.1.1.0)
- the current latest commit: 74aec0df7e4b1ff62ad5d55760d9fa5d5f29898b

Git bisecting the issue, the last working version is 983e2c9be078d0ada3b3f7f4d747c75ec0830ad4 and the first broken 4b4c32eea8c62df2aad658b414d3029624f55697. That last commit contains a big version bump of the reflex-platform. I suspect the regression comes from here but I run out of ideas on how to debug any further.

Happy to help debug the issue if someone can provide me with rough instructions on how to move forward.

**Comment by ali-abrar** [comment]
This should be fixed in reflex-dom 0.6.3.0, which supports the [new webview asset loader](https://developer.android.com/reference/androidx/webkit/WebViewAssetLoader)

**Comment by ali-abrar** [comment]
https://github.com/obsidiansystems/obelisk/pull/1045

**Comment by ali-abrar** [comment]
Fixed in https://github.com/obsidiansystems/obelisk/releases/tag/v1.2.0.0

**Comment by jecaro** [comment]
works perfectly thx :+1:
