### ISSUE TITLE
text function and emojis causes jsaddle errors in certain cases

### ISSUE THREAD

**Issue by augyg** [obsidiansystems/obelisk#1055]
**Works no problem:**
`text "👋 Contact Support"`

and 

`text "👋"`

**Causes JSaddle Error:** 

`text "👋" >>
text "Contact Support"
` 

**JSaddle Error:**
jsaddle Results decode failed : "{\"tag\":\"BatchResults\",\"contents\":[215,{\"tag\":\"Success\",\"contents\":[[],[{\"tag\":\"ValueToStringResult\",\"contents\":\"\\udc4bContact Support\"}]]}]}"
CallStack (from HasCallStack):
  error, called at src/Language/Javascript/JSaddle/WebSockets.hs:103:50 in jsaddle-warp-0.9.8.2-DFAPM2CvatBGFm3L9xaA1B:Language.Javascript.JSaddle.WebSockets

**Comment by ali-abrar** [comment]
Looks like this might be something internal to jsaddle.

**Comment by alexfmpe** [comment]
It looks like hydration also gets tripped up on this. When doing the ghcjs build, I see a flash of the expected result, followed by duplicated output and a broken emoji.

<img width="247" alt="image" src="https://github.com/obsidiansystems/obelisk/assets/2335822/701feaf2-e586-455a-a060-f9ac47a91ac8">

**Comment by alexfmpe** [comment]
It seems to also only happen when there's two `text` nodes. Can't reproduce without the full ghcjs build due to the jsaddle-warp issue.
Is that a separate reflx-dom issue or?
