### ISSUE TITLE
`nix-shell` fails in newly initialized obelisk project

### ISSUE THREAD

**Issue by abigailalice** [obsidiansystems/obelisk#1058]
I'm trying to set up a new obelisk project, and after running `nix shell` in the project root I get the following error message:
```
error: Package ‘fix-darwin-dylib-names-hook’ in /nix/store/ahg8gp1z3qrw1ds5vx2324j72i7y9vjg-source/pkgs/build-support/trivial-builders.nix:74 is not supported on ‘x86_64-linux’, refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```
Running the command with `NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1` returned
```
error: iOS builds are not supported on this platform.
```

I'm super new to nix, and am not even sure that using `nix-shell` is how I'm supposed to start things; `ob run` seems to work on its own already, but I had added a local package, and putting it in the cabal file didn't seem to be enough for `ob run` to find it, so thought maybe I was supposed to add it to `default.nix` and enter a nix-shell before using the `ob` commands, but truthfully I'm not sure if that's right.

I'm running in NixOS, and don't need iOS support for anything. I'm not even sure how much this is an obelisk issue; I had a similar issue trying to modify the `default.nix` shown at https://github.com/reflex-frp/reflex-platform/blob/develop/docs/project-development.rst to work for a minimal project to after deciding obelisk might be too much complexity too soon.

I'm mainly posting here since all of the code in my obelisk project was exactly as created by `ob init`, so if `nix-shell` is supposed to work, I feel like it should work there.

**Comment by ali-abrar** [comment]
ob has its own shell command: `ob shell`. This might get you the shell you want.

**Comment by abigailalice** [comment]
Ah, I didn't know about that one, thanks. After doing some more digging on the local packages problems I was having it seemed to be a permissions problem; fixing that got `ob run` working the way I had expected it to work.
