### ISSUE TITLE
Distribution.PackageDescription.Parse is removed in Cabal 2.2

### ISSUE THREAD

**Issue by matthewbauer** [obsidiansystems/obelisk#106]
```obelisk/lib/command/src/Obelisk/Command/Run.hs``` uses the ```Distribution.PackageDescription.Parse``` module to parse packages. It has been removed from Cabal starting in version 2.2: https://github.com/haskell/cabal/issues/5025. I'm not sure what a good alternative is but ```ob run``` uses it pretty extensively.

I think in the reunification branch we may be able to override to use an older version of cabal but this will get harder as newer versions are introuced.

https://github.com/obsidiansystems/obelisk/blob/master/lib/command/src/Obelisk/Command/Run.hs#L18

**Comment by ryantrinkle** [comment]
@matthewbauer Is there some kind of replacement available?  Maybe we should ask the Cabal guys what the right approach is here.  We could, for example, move some of our functionality into Cabal.

**Comment by luigy** [comment]
This was covered and fixed as part of `routes` work which is now in master
