### ISSUE TITLE
`ob init` fails on nix-prefetch-url

### ISSUE THREAD

**Issue by cah6** [obsidiansystems/obelisk#107]
I had obelisk working on NixOS, I'm not sure what changed but now the following is thrown on `ob init`:
```
$ ob init
RawCommand "nix-prefetch-url" ["--unpack","--type","sha256","https://codeload.github.com/obsidiansystems/obelisk/legacy.tar.gz/38cc2c5f8330eae6bb12e1e8502c1b0764739791"] failed with exit code: 1
nix-prefetch-url: Failed to determine sha256 hash of URL https://codeload.github.com/obsidiansystems/obelisk/legacy.tar.gz/38cc2c5f8330eae6bb12e1e8502c1b0764739791
✖ Setting up obelisk
```
Any ideas? I double checked my setup and everything seems to match up.

**Comment by 3noch** [comment]
Hm I just ran `ob init` last night without issue. Also, this command run directly works for me:

```sh
nix-prefetch-url --unpack --type sha256 https://codeload.github.com/obsidiansystems/obelisk/legacy.tar.gz/38cc2c5f8330eae6bb12e1e8502c1b0764739791
```

Could it have been a network glitch? Also, are you using the very latest version of `ob` from `master`?

**Comment by srid** [comment]
@cah6 Run `ob init -v` to see the original error.

I suspect you are hitting #100 and thus need to set the `NIX_REMOTE=daemon` env var.

**Comment by cah6** [comment]
Ah, yep setting the daemon var worked. Thanks!
