### ISSUE TITLE
How to customize sub-project cabal dependency?

### ISSUE THREAD

**Issue by cah6** [obsidiansystems/obelisk#108]
Let's say I have a completely fresh project via `ob init`. I have a situation where I want to use https://github.com/hellertime/time-recurrence in the common directory. It has a requirement of `time >=1.4 && <1.6` and `HUnit >=1.2 && <1.4`, so I added those to the `common.cabal` file...
```
name: common
version: 0.1
cabal-version: >= 1.2
build-type: Simple
License: BSD3

library
  hs-source-dirs: src
  build-depends: base
               , time >=1.4 && <1.6
               , HUnit >=1.2 && <1.4
               , time-recurrence
  default-language: Haskell2010
  exposed-modules:
    Common.Api
``` 
and running `ob run` passes, great. 

Add in `time-recurrence` too...
```
...
  build-depends: base
               , time >=1.4 && <1.6
               , HUnit >=1.2 && <1.4
               , time-recurrence
...
```
and then running `ob run` gives:
```
...
Configuring time-recurrence-0.9.3...
Setup: Encountered missing dependencies:
HUnit >=1.2 && <1.4, time >=1.4 && <1.6
builder for '/nix/store/wnmzkrpcwr16vcrrybf4jlzzl7fs9zrq-time-recurrence-0.9.3.drv' failed with exit code 1
cannot build derivation '/nix/store/y3llzxpr76v55dkpvw063q92smy6djpb-ghc-8.0.2-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/y3llzxpr76v55dkpvw063q92smy6djpb-ghc-8.0.2-with-packages.drv' failed
/nix/store/npx12kr33dra5lcvlavwp3bwbv2haa1p-nix-1.11.15/bin/nix-shell: failed to build all dependencies
```

I know nothing about nix and little about cabal (since I typically use stack), but I tried to get this working in a non-obelisk project by starting a new project and making:
shell.nix:
```
let
  pkgs = import <nixpkgs> { };

in
  { project1 = pkgs.haskellPackages.callPackage ./default.nix { };
  }
```
and generating default.nix with `cabal2nix . > default.nix`. Then entering a shell with a good GHC with `nix-shell shell.nix`. Adding `time >=1.4 && <1.6` and `time-recurrence` to my project then builds fine with `cabal new-build`. As an aside / in desperation I tried doing exactly the same in my obelisk project's common folder (make the nix files, generate default.nix from common.cabal, get in shell with ghc, run cabal new-build) but `cabal new-build` ran from common/ gives:
```
$ cabal new-build
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: backend-0.1 (user goal)
unknown package: obelisk-executable-config-inject (dependency of backend-0.1)
fail (backjumping, conflict set: backend, obelisk-executable-config-inject)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: backend,
obelisk-executable-config-inject
```
I'm not sure why exactly it's backtracking and finding backend in the project, but obviously this is not the right way to do it.

Sorry for the long rant...my ending questions are:
1. specifically, how would I pin a specific version of a package for a specific sub-project of an obelisk project
2. generally, what is `ob run` or `ob repl` actually doing under the hood? I can see that some cabal2nix things are happening, but I assume these are not actually being stored somewhere since `find . -name "*.nix"` doesn't return anything. 
3. building off 2, if I wanted to customize sub-projects with a more detailed nix expression, how would I tie that into the top-level `default.nix`? I don't see anywhere where it's actually referencing the sub-projects and it's not clear to me (a new nix user) how to do so.

**Comment by 3noch** [comment]
@cah6 `ob run` fires up `ghcid` in a `nix-shell` that doesn't care about your version bounds at all. It uses the versions pinned in obelisk/reflex-platform. You can, however, override these in `default.nix`. The version of `time` that's currently pinned is `1.6` so it technically falls out of the range. However, if the issue is merely that `time-recurrence`'s version bounds are unnecessarily tight, you can tell it to install without caring about version bounds. Make your `default.nix` look something like this:

```nix
project ./. ({ pkgs, ... }: {
  android.applicationId = "systems.obsidian.obelisk.examples.minimal";
  android.displayName = "Obelisk Minimal Example";
  ios.bundleIdentifier = "systems.obsidian.obelisk.examples.minimal";
  ios.bundleName = "Obelisk Minimal Example";

  overrides = self: super: {
    time-recurrence = pkgs.haskell.lib.doJailbreak super.time-recurrence;
  };
```

**Comment by srid** [comment]
See also #62

**Comment by cah6** [comment]
Ahh I see, thank you! Does this mean that all sub-directories in an obelisk project need to rely on the same version of packages? I haven't ran into a situation where I need this to not be the case, just wondering. 

Also how does ob get into that `nix-shell` where it runs  `ghcid`? I noticed that if I do `nix-shell default.nix` it still doesn't have `ghcid`?

**Comment by 3noch** [comment]
@cah6 `nix-shell -A shells.ghc` should put you in the same shell that `ob run` uses.

**Comment by ali-abrar** [comment]
The [readme](https://github.com/obsidiansystems/obelisk/blob/develop/README.md#adding-package-overrides) documents how to do this.
