### ISSUE TITLE
Customize Ob.backend function?

### ISSUE THREAD

**Issue by Rizary** [obsidiansystems/obelisk#110]
Hi, So I've been playing around with Obelisk and wondering is it intended for us to customize the `backend` function [here](https://github.com/obsidiansystems/obelisk/blob/master/lib/backend/src/Obelisk/Backend.hs#L30) so I can have something like this (i got this from [matrix-hackage repo](https://github.com/Rizary/hackage-matrix-builder/blob/master/src-exe/Controller/WebSvc.hs)).

```
runController :: App -> Word16 -> IO ()
runController !app port =
    serveSnaplet conf initApp
  where
    conf = Snap.setPort (fromIntegral port) $
           Snap.setBind "127.0.0.1" $
           Snap.setProxyType Snap.xForwardedFor $
           defaultConfig

    initApp :: SnapletInit App App
    initApp = makeSnaplet "matrix-controller" "Matrix CI controller" Nothing $ do
        addRoutes [("/api/swagger.json",apiSwaggerJsonHandler)
                  ,("/api/",      apiHandler)

                  ,("/package/",  hashRedir)
                  ,("/packages/", hashRedir)
                  ,("/user/",     hashRedir)
                  ,("/users/",    hashRedir)
                  ,("/latest/",   hashRedir)

                  ,("/",          uiHandler)
                  ]
        return app
```

I mean does this permissible in the way of developing `reflex` project using `obelisk`? If not, what is the best way to customize the backend?

**Comment by kitlangton** [comment]
I'm equally confused, @Rizary. Any luck figuring out how to customize the Backend?

**Comment by ohri-anurag** [comment]
@Rizary We now have a function called [`_backend_run`](https://github.com/obsidiansystems/obelisk/blob/e3ec75f6988eed47189dd20f8c8514748b33ea81/lib/backend/src/Obelisk/Backend.hs#L70). Does this meet your requirements?

If not, would it be possible to provide some more details on your requirements?

**Comment by madeline-os** [comment]
I'm closing this issue under the rationale that the way that the backend is specified has drastically changed in the last few years. If you are still interested in obelisk, and the current design still does not meet your use-case, please make a new issue. I promise to attend to it in a timely fashion.
