### ISSUE TITLE
ob deploy is broken on Mac

### ISSUE THREAD

**Issue by 3noch** [obsidiansystems/obelisk#113]
Somehow recent changes have caused build/deploy support to be broken on Mac. Oddly, copying and pasting the `nix-build` command directly from the verbose output actually works fine. Something must be broken about the environment of `nix-build` when run by `ob`. Perhaps its the fact that `wrapProgram` pins `nixStable2`.

**Comment by ali-abrar** [comment]
@3noch do you have an easy way to test this with a more recent obelisk?

**Comment by 3noch** [comment]
@luigy has taken over this feature and it's changed considerably since I worked on it. I believe it now works. Would you mind updating, @luigy?

**Comment by ali-abrar** [comment]
This now appears to be working.
