### ISSUE TITLE
Enable users to add services to the deployed nixos config

### ISSUE THREAD

**Issue by JBetz** [obsidiansystems/obelisk#114]
Users should be able to specify any services they need on their deploy target that obelisk doesn't provide. E.g., I want to run a Postgres server on the EC2 instance that I'm deploying my project to, but I can't because obelisk takes full control of the nixos config.

**Comment by ElvishJerricco** [comment]
It'd best way to support this would probably be to allow users to specify their own arbitrary NixOS module.

**Comment by 3noch** [comment]
If obelisk exposes a NixOS module then you could also manage deploys separately and just import the obelisk config.

**Comment by lgastako** [comment]
We recently ran into a situation where we wanted something like this.  Specifically we wanted to be able to add a cron job to configuration.nix.  I'm not a nix expert so I don't know if a nix module can do this or not, but if it can, then that would work for our scenario.  If it can't then we would also like to the ability to provide a chunk of code to be included in configuration.nix or some other way to add/override settings from configuration.nix.

**Comment by 3noch** [comment]
This is actually now possible if you construct the server yourself using obelisk's exposed modules: https://github.com/obsidiansystems/obelisk/blob/develop/default.nix#L167

**Comment by 3noch** [comment]
You can actually keep using `ob deploy` if you just override the `server` attribute to build the server piece-meal instead of using the default value provided by obelisk.

**Comment by anfelor** [comment]
> This is actually now possible if you construct the server yourself using obelisk's exposed modules: 

@3noch Could you give a bit more detail here? For example, how would I add a package `nixos.xyz` to my configuration?

**Comment by 3noch** [comment]
@anfelor Check out: https://github.com/obsidiansystems/obelisk/tree/4f2d3f1c1312d833ae814b7a86cf7b65ea0614ec#custom-non-ec2-deployment

**Comment by anfelor** [comment]
@3noch I tried using the method described there, but I am stuck. In particular, I am trying to install `eprover`, but
```
{ nixosPkgs, ... }: {...}: {
  imports = [ (nixosPkgs.path) ];
  config = {
    environment.systemPackages = [nixosPkgs.eprover];
  };
}
```
takes no effect.

**Comment by 3noch** [comment]
@anfelor You don't want to import `nixosPkgs.path`. That should be a module appropriate for your target, such as EC2 or digital ocean or virtualbox. I can't provide adequate NixOS support here but there are plenty of people willing to help on nixos IRC channel. Also be sure to use `-v` with obelisk to make sure it's properly using your `module.nix` file.

**Comment by anfelor** [comment]
@3noch I believe this is actually an issue with obelisk, because both `ob run` and `nix-build -A exe --no-out-link` now give me a working executable, but `ob deploy push` doesn't.
My `default.nix`:
```
{ obelisk ? import ./.obelisk/impl {
    system = builtins.currentSystem;
    iosSdkVersion = "10.2";
    config.android_sdk.accept_license = true;
  }
}:
with obelisk;
project ./. ({ pkgs, ... }: {
  android.applicationId = "systems.naproche";
  android.displayName = "Naproche";
  ios.bundleIdentifier = "systems.naproche";
  ios.bundleName = "Naproche";
  packages = {
    nave = ./nave;
    Naproche-SAD = ./Naproche-SAD;
    extern = ./extern;
  };
  overrides = self: super:
  {
    Naproche-SAD = self.callPackage ./Naproche-SAD {
      eprover = pkgs.eprover;
    };
    extern = self.callPackage ./extern {
      lean3 = pkgs.lean;
      pdflatex = pkgs.texlive.combined.scheme-medium;
    };
  };
})
```
For the haskell libraries `Naproche-SAD` and `extern` I have generated a `default.nix` with `cabal2nix` and added a line `  librarySystemDepends = [ <pkgs> ];`
I have also experimented using a `module.nix` with content:
```
{ nixosPkgs, ... }: {...}: {
  imports = [
    (nixosPkgs.path + /nixos/modules/virtualisation/amazon-image.nix)
  ];
  ec2.hvm = true;
  environment.systemPackages = [ nixosPkgs.eprover nixosPkgs.lean nixosPkgs.texlive.combined.scheme-medium ];
}
```
but while this installs the necessary packages, there are not linked to the haskell libraries one way or another.

**Comment by 3noch** [comment]
I haven't spent much time looking at this but there's a possible nuance here: `nixosPkgs` is the base package set used to build the entire obelisk project. But it isn't the package set that actually gets installed. For that you need `pkgs` in the *second* argument (that's the one which comes from NixOS module system). So you might want to try `{nixosPkgs, ...}: {pkgs, ...}:` and then use `pkgs` for your `systemPackages`.

**Comment by 3noch** [comment]
The reason for this confusing discrepancy is that the module-based `pkgs` doesn't have a `path` attribute because it's not actually a physical copy of nixpkgs but a derived one.

**Comment by anfelor** [comment]
@3noch I tried your suggestion, but that does not seem to fix the issue. Actually, `nixosPkgs.eprover` already installs the correct executables in the ssh shell; it is just that my package can't access them.

**Comment by 3noch** [comment]
Oh, if your Haskell code needs access to a program then you need to declare that in nix. The nix-shell won't be a great representation of that because it often installs many things at the same time. But your Haskell package will not have access to systemPackages. You need to make sure it's added to librarySystemDepends or similar. For example: https://github.com/obsidiansystems/obelisk/blob/3fa3600946d6dfd33ab7bfe9838ea8b99071a92c/haskell-overlays/obelisk.nix#L20

**Comment by anfelor** [comment]
@3noch I am a bit confused. I do declare `librarySystemDepends` in my `default.nix` for each package. Isn't that enough? It also works on my local `nix-build` so the problem must be connected to some difference between local builds and builds on EC2.

**Comment by rubenmoor** [comment]
> You can actually keep using `ob deploy` if you just override the `server` attribute to build the server piece-meal instead of using the default value provided by obelisk.

I want to add a database to the deployment like original poster. Can you give more details on how to override the `server` attribute? I do have basic nix knowledge, but I am stuck. Do I replace the file `deployment/.obelisk/impl/default.nix` or can I make my changes in a seperate file? Does the file `module.nix` play a role for that purpose?

**Comment by Ericson2314** [comment]
https://github.com/obsidiansystems/obelisk-systemd is probably a better method for highly customized deployed machine configurations. We hope to eventually smooth the gap so that is more discoverable from the default `ob deploy`.
