### ISSUE TITLE
`master`'s migration graph is incorrect

### ISSUE THREAD

**Issue by srid** [obsidiansystems/obelisk#116]
When PR #91 was merged I think it introduced a non-mempty diamond (which we don't support yet). Looking at git history I see that that branch was not rebased with `master` (so as to avoid the non-mempty diamond) _prior_ to merging.

@ryantrinkle  We can manually fix this in master now, but how to ensure that this doesn't happen in the future?

```
$ ob internal verify-migration
✔ Reading migration graph
✔ Checking graph integrity
No vertex found for HEAD (b0b562b83e8a198bb858deeb19d5868c)
✖ Checking existence of HEAD vertex
```

```
$ ob internal hash
b0b562b83e8a198bb858deeb19d5868c
$ ob internal hash HEAD~1
e66afc8befac4d76b5780a960f768c31
$ ob internal hash HEAD~2
6a18939264224d6ce24c7426249edfea
$ ob internal hash HEAD~3
554c459ff2cced3e1b11241ed403890d
```

```
$ git show 7d0b41b50870bebb55d41ec41956647ce35804a2 | tail -3
diff --git a/migration/554c459ff2cced3e1b11241ed403890d-3543ea607791bc2e19419d22918823bd/obelisk-upgrade b/migration/554c459ff2cced3e1b11241ed403890d-3543ea607791bc2e19419d22918823bd/obelisk-upgrade
new file mode 100644
index 0000000..e69de29
```

**Comment by 3noch** [comment]
Oops. I think that PR was submitted prior to the migration changes. Perhaps we could disable non-fast-forward merges?

**Comment by JBetz** [comment]
Possibly related. This is after installing the latest version of master.
```
$ ob upgrade
✖ Deciding whether to handoff
ob: MultipleTerminalVertices
```

**Comment by srid** [comment]
@JBetz Yes, that would be an (expected) symptom of this issue.

**Comment by JBetz** [comment]
Is this going to be fixed anytime soon? And in the meantime, what's the best way to switch an existing project to a different version of obelisk?

**Comment by luigy** [comment]
Closing this since migrations have been deferred for now
