### ISSUE TITLE
ob init on macOS uses an illegal option for cp

### ISSUE THREAD

**Issue by tjweir** [obsidiansystems/obelisk#182]
After installing obelisk according to the README, attempting to run "ob init" results in the following error.

```
[ ~/g/obelisk/one ] [89%] [ ]
> ob init
/private/var/folders/6h/qzvz8g_x6wq5tvvpvpmtnvp80000gn/T/ob-init86349/.obelisk/impl: command not cached, building ...
⇾ Setting up obelisk ✔ Built /private/var/folders/6h/qzvz8g_x6wq5tvvpvpmtnvp80000gn/T/ob-init86349/.obelisk/impl [command]
/private/var/folders/6h/qzvz8g_x6wq5tvvpvpmtnvp80000gn/T/ob-init86349/.obelisk/impl: skeleton not cached, building ...
⇾ Setting up obelisk ✔ Built /private/var/folders/6h/qzvz8g_x6wq5tvvpvpmtnvp80000gn/T/ob-init86349/.obelisk/impl [skeleton]
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
✖ Setting up obelisk
Process exited with code 64; RawCommand "cp" ["-r","--preserve=links","/private/var/folders/6h/qzvz8g_x6wq5tvvpvpmtnvp80000gn/T/ob-init86349/.obelisk","./.obelisk"]
[ ~/g/obelisk/one ] [89%] [ ]
> uname -a                   
Darwin My-MacBook-Pro-2.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

```

The contribution guidelines ask that I run: `$(nix-build -A selftest --no-out-link)` but that results in: 
```[ ~ ] [86%] [ ]
> $(nix-build -A selftest --no-out-link)
error: getting status of '/Users/<username>/default.nix': No such file or directory
```

I think I need to run that in my obelisk app, but I don't get that far.

**Comment by 3noch** [comment]
@tjweir Can you ensure you have the latest version of `ob` from current `master` and report back?

**Comment by tjweir** [comment]
Absolutely I will. Just on vacation without my laptop.  I will verify and update when I return.

**Comment by ali-abrar** [comment]
I just tested `ob init` from current master on macOS 10.12.6 and everything seems to work.

**Comment by ali-abrar** [comment]
Didn't mean to close the issue until @tjweir confirms. Sorry about that.

**Comment by tjweir** [comment]
I grabbed the latest and ran into the same issue with `ob init`.

I then ran `nix-env -I obelisk` and `ob init` and things ran as expectedly.

I am currently 2 hours into a run of `ob run` and will update after.

Should I need to run within a `nix-env` ?

**Comment by 3noch** [comment]
Excellent! I'll close this then. :)
