### ISSUE TITLE
Project without backend

### ISSUE THREAD

**Issue by abueide** [obsidiansystems/obelisk#190]
I intend to make a peer to peer desktop/android/mobile app and do not need the backend and common modules in my project. Is there a way to remove them? Can some one recommend a project structure or if I should even be using obelisk? I'm just trying to figure out how to get started with an example app that runs reflex on android and desktop without ghcjs for now.

**Comment by tomsmalley** [comment]
Since you're only interested in the frontend side, you can just use [reflex-platform's project implementation](https://github.com/reflex-frp/reflex-platform/blob/develop/project/default.nix).

**Comment by 3noch** [comment]
@tomsmalley  This of course works but doesn't provide any of the niceties of `ob run` etc. @abueide I suspect you'd be fine using an obelisk project as-is and just not *using* the default skeleton backend that it comes with.

**Comment by tomsmalley** [comment]
The problem is then that `ob run` expects a particular module structure, in particular it wants a backend to serve the frontend. In single package environments, `ghcid` is almost equivalent. I ran into this when switching `semantic-reflex`'s examples over to `obelisk-route`, and just ended up using `ghcid`.

**Comment by 3noch** [comment]
Right but there's no reason you must *use* the backend/common modules other than for the basic infra that `ob run` uses, right?

**Comment by rprije** [comment]
@abueide I built a similar project and kept all the backend / common / devel structure only for ease of development. Once I had built my frontend, I grabbed the contents of frontend-result/bin/frontend.jsexe/ and uploaded it to a static website. It worked fine for my purposes. Maybe you could take a similar approach?

**Comment by 3noch** [comment]
@rprije Cool! Yeah that's exactly what I meant.

**Comment by chengzh2008** [comment]
Kind of related question. Is there example or documentation on how to add servant into obelisk project? Do I have to use snap on the backend in order to use obelisk? Thanks!

**Comment by ali-abrar** [comment]
@chengzh2008 Perhaps you'll find this relevant: https://github.com/jonathanknowles/obelisk-reflex-servant-example
