### ISSUE TITLE
Use of "import from derivation" is causing issues with docker / CI.

### ISSUE THREAD

**Issue by dalaing** [obsidiansystems/obelisk#192]
I've got a coworker who is trying to get an Obelisk project setup in a docker based CI environment, where they're not willing to use the `--priviledged` option.  This means that the import-from-derivation stuff done in the ob project template (inside `./obelisk/impl/default.nix`, and again in `./deps/reflex-platform/default.nix` in the main Obelisk repository) cause builds to fail with permission issues.

I can get past the first of these issues by setting up Obelisk as a git submodule in `./obelisk/impl`, but I can't set up reflex-platform in there because I'd have a submodule containing a submodule. 

If I could change [this](https://github.com/obsidiansystems/obelisk/blob/master/default.nix#L6) such that the path to reflex-platform was overridable, I could probably submodule my way to victory.

So I have two questions:

- would you be open to such a change?
- would you be open to a change that adds an extra option to `ob init` to set this up for people right from the start?

I'm happy to hack away on these things myself, I just wanted to make sure it's something folks are interested in.

**Comment by ryantrinkle** [comment]
I'd be happy to make reflex-platform configurable, but I'm really surprised that import-from-derivation has this kind of security implication.  Is that fundamental or just a quirk of how nix works?

**Comment by ElvishJerricco** [comment]
What do docker privileges have to do with IFD?

**Comment by ElvishJerricco** [comment]
I think you're going to run into this problem regardless; `callCabal2nix` is used extensively in `reflex-platform`, which relies on IFD.

**Comment by matthewbauer** [comment]
I would be interested in knowing where Nix fails in Docker with unprivileged. Most likely it is a bug in Nix. You may have to add the SYS_CHROOT capability though.

**Comment by dalaing** [comment]
Maybe I should provide some more context :)

If we're in [this](https://github.com/LnL7/nix-docker) and try to build the artifacts for an Obelisk project we get:
```
8964b3248562:/code# nix-build . -A exe -o result-exe --show-trace
error: cloning builder process: Operation not permitted
error: while evaluating anonymous function at /code/default.nix:1:1, called from undefined position:
while evaluating the file '/code/.obelisk/impl/default.nix':
unable to start build process
```
and if I make `.obelisk/impl` a submodule pointing at the Obelisk repository we get:
```
error: cloning builder process: Operation not permitted
error: while evaluating anonymous function at /code/default.nix:1:1, called from undefined position:
while evaluating 'project' at /code/.obelisk/impl/default.nix:252:19, called from /code/default.nix:5:1:
while evaluating 'projectOut' at /code/.obelisk/impl/default.nix:255:22, called from /code/.obelisk/impl/default.nix:313:8:
while evaluating 'getReflexPlatform' at /code/.obelisk/impl/default.nix:6:23, called from /code/.obelisk/impl/default.nix:255:28:
while evaluating the file '/code/.obelisk/impl/dep/reflex-platform/default.nix':
unable to start build process
```
which is what made me think IFD was the problem.

From some googling and one of the other Obelisk issues, I think that `sysctl -w kernel.unprivileged_userns_clone=1` might help but I don't know if the ops person I'm talking to is going to go for that.

**Comment by dalaing** [comment]
Yeah, I've now done my very first Docker thing and it's working fine for me.  I'll chat with the ops person who was running into this issue and try to work out where our approaches differ.

Sorry for the noise, and thanks for the help.

**Comment by ryantrinkle** [comment]
I'd there anything we can improve/document to help people who might find
themselves in a similar situation in the future?

**Comment by dalaing** [comment]
All I can think of is to tweak the installation instructions.  Maybe a new entry in between "other linux" and "macOS"? It could possibly be done with a tweak from "other linux" to "other linux (but not docker)", but getting the wording right so that it flows properly could be tricky.
