### ISSUE TITLE
Support mounting frontend widget to an arbitrary DOM element

### ISSUE THREAD

**Issue by 3noch** [obsidiansystems/obelisk#20]

**Comment by ryantrinkle** [comment]
Can you elaborate on the motivation for this? Since obelisk handles the
backend as well, we may be able to create a more elegant solution.

**Comment by 3noch** [comment]
I'm thinking of a project that I want to move to obelisk that mounts the frontend differently in different contexts. For example, in some cases the frontend gets mounted as a WordPress plugin. In other cases, it is mounted normally to `body`. But perhaps its not necessary to support this *directly* via obelisk. Since the frontend is a cabal library, you could create different exes for it that mount differently. Obelisk could focus on supporting the obvious one.

**Comment by 3noch** [comment]
We have no plans to support this directly. It's still possible to add extra `executable`s to a frontend and expose this manually.
