### ISSUE TITLE
Consider not pinning nix for ob commands

### ISSUE THREAD

**Issue by 3noch** [obsidiansystems/obelisk#204]
Obelisk currently uses a pinned `nix` (et al). From various reports (#52, #100, #198) it seems this may not be the best idea after all. Consider dropping the pin entirely.

**Comment by srhb** [comment]
I think the pin is sane, but the fact that reflex-platform has a nixUnstable at 1.12pre5619_346aeee1 is probably not.

**Comment by ElvishJerricco** [comment]
@srhb I don't think the pin is sane. The nix daemon protocol should not be considered stable, IMO.
