### ISSUE TITLE
ob run should run ghc with -Wall

### ISSUE THREAD

**Issue by eskimor** [obsidiansystems/obelisk#206]
Just wasted an hour for a bug, that could have been found in seconds if I had -Wall enabled. Which I have in the cabal file, but checked the code via ob run which ignores this setting.

**Comment by luigy** [comment]
Agreed, I thought this was added already, but it must have been to a different branch

**Comment by ElvishJerricco** [comment]
Sounds like really `ob` should use your cabal file's arguments. Can it not use `cabal (new-)repl` instead of `ghci`?

**Comment by 3noch** [comment]
@ElvishJerricco No because it loads multiple packages in at once.

**Comment by ElvishJerricco** [comment]
Ah. That's a feature I wish cabal had.

**Comment by ali-abrar** [comment]
Fixed in 176e9ab
