### ISSUE TITLE
Stuck after Test suite doctests: RUNNING...

### ISSUE THREAD

**Issue by dukedave** [obsidiansystems/obelisk#215]
I followed [the readme](https://github.com/obsidiansystems/obelisk#developing-an-obelisk-project) up to `ob run`, but now I'm stuck at:

```
Test suite doctests: RUNNING...
```

http://localhost:8000/ just gives the _Refused to connect_ error in Chrome, I checked `config/common/route` and it matches.

I'm on MacOS 10.13.6 and nix 2.0.4.

**Comment by luigy** [comment]
Do you know for which package is running tests ? Seems like ‘ob run’ has not gotten to run your app yet and is still building deps

**Comment by cah6** [comment]
I've had this happen with a different package. Not sure why but you can probably get around this by turning off tests for that library with `dontCheck`. I.e. assuming you haven't made any other changes to `default.nix`, making it:
```
{ system ? builtins.currentSystem # TODO: Get rid of this system cruft
, iosSdkVersion ? "10.2"
}:
with import ./.obelisk/impl { inherit system iosSdkVersion; };
project ./. ({ pkgs, ... }: {
  android.applicationId = "systems.obsidian.obelisk.examples.minimal";
  android.displayName = "Obelisk Minimal Example";
  ios.bundleIdentifier = "systems.obsidian.obelisk.examples.minimal";
  ios.bundleName = "Obelisk Minimal Example";

  overrides = self: super: {
    linear = pkgs.haskell.lib.dontCheck super.linear;
  };
})
```

**Comment by dfordivam** [comment]
@dukedave From the log it is clear that the test suite of linear-1.20.7 is stuck

Hope the workaround suggested by cah6 worked for you.
