### ISSUE TITLE
Make closure compiler level configurable

### ISSUE THREAD

**Issue by JBetz** [obsidiansystems/obelisk#229]
The closure compiler's ADVANCED optimizations causes problems when using external JS libs. It's been an issue for me when trying to use [reflex-dom-ace](https://github.com/reflex-frp/reflex-dom-ace). It worked fine when using `ob run`, but not at all when I built the frontend with `ghcjs`.

**Comment by JBetz** [comment]
To start, this could be as simple adding a parameter to remove `-o ADVANCED` from the closure-compile command. Removing it solved my problem with ace.

**Comment by ryantrinkle** [comment]
Hmm, how much of a size difference does ADVANCED make?  As a stopgap, making an easy way to disable ADVANCED mode makes sense, but it would be a *lot* better to have a solution that allows it to stay on.

**Comment by JBetz** [comment]
For my project, it's 4.2mb with ADVANCED, 9.7mb without. So it's a pretty big difference, but not having access to the external JS libs is a dealbreaker.

[Reflex.Dom.ACE](https://github.com/reflex-frp/reflex-dom-ace/blob/master/src/Reflex/Dom/ACE.hs) is the problematic module, but I don't see anything "wrong" with it, since there's no raw JS that might get mangled.

Do you have any idea how to make it compatible with ADVANCED optimization?

**Comment by ryantrinkle** [comment]
My guess would be that something in [here](https://github.com/reflex-frp/reflex-dom-ace/blob/f5a7f5999c20f2a27aeaa93f96f093bcc560b526/lib/ace.js), perhaps [this line](https://github.com/reflex-frp/reflex-dom-ace/blob/f5a7f5999c20f2a27aeaa93f96f093bcc560b526/lib/ace.js#L9), is getting mutilated.  I think that file gets dumped wholesale into the output somewhere, and then ADVANCED optimizations may rewrite it in a way that other things aren't expecting.

**Comment by JBetz** [comment]
I don't think that `ace.js` file is actually required. I was able to vendor `reflex-dom-ace` by simply copying its single Haskell module into my project, and it works fine.

@mightybyte, can you verify?

**Comment by ryantrinkle** [comment]
I've determined what's going on with ACE.  GHCJS creates a lot of top-level functions, which closure-compiler comes along and renames.  It so happens that `ace` is one of the fairly early names closure-compiler picks, and as a result, `window.ace` becomes that value.  In @JBetz case, I suspect ACE is being loaded before the app code, and so the app code comes along and clobbers `window.ace`.  In @vaibhavsagar's case, the app code loads first, and so `window.ace` already exists when [this](https://github.com/reflex-frp/reflex-dom-ace/blob/f5a7f5999c20f2a27aeaa93f96f093bcc560b526/lib/ace.js#L8) runs.

One possible solution (which seems like a good idea in any case) would be to wrap the whole app in a `(function(){ . . . })()` block.  Let me know if you guys have any other ideas, too!

**Comment by mightybyte** [comment]
I still have another personal project that is not using `reflex-dom-ace` that I haven't been able to successfully closure-compile.  It uses `reflex-dom-semui` though.  It's not using obelisk yet because of backend support, but if it was, I'd probably want the closure compiler optimization level to be configurable.

**Comment by JBetz** [comment]
@ryantrinkle, that solution sounds good to me. What would be the right way to implement it? Simply prepending and appending text to the output file `all.js`?

**Comment by vaibhavsagar** [comment]
Simply prepending and appending text to the output `all.js` doesn't seem to work for me, I'm getting the following errors:

```
all.unminified.js:2698: ERROR - Closure dependency methods(goog.provide, goog.require, etc) must be called at file scope.
goog.provide('goog.math.Long');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

all.unminified.js:23785: ERROR - Closure dependency methods(goog.provide, goog.require, etc) must be called at file scope.
goog.provide('goog.crypt.Hash');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

all.unminified.js:23889: ERROR - Closure dependency methods(goog.provide, goog.require, etc) must be called at file scope.
goog.provide('goog.crypt.Md5');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

all.unminified.js:23890: ERROR - Closure dependency methods(goog.provide, goog.require, etc) must be called at file scope.
goog.require('goog.crypt.Hash');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

4 error(s), 0 warning(s)
```

**Comment by ryantrinkle** [comment]
`all.js` is a concatenation of several other files - perhaps we could wrap *some* of them?

**Comment by JBetz** [comment]
Since upgrading `obelisk`, this is no longer an issue for my project. I can build the frontend with advanced optimizations and the ACE widgets work as expected. @vaibhavsagar, you might want to try doing the same.

@ryantrinkle any idea why it would be working now?

**Comment by vaibhavsagar** [comment]
Yes, this seems to work for me too!
