### ISSUE TITLE
`ob` command handoff doesn't happen on Fedora without user intervention.

### ISSUE THREAD

**Issue by danbornside** [obsidiansystems/obelisk#232]
Fedora has, by default, a per-user umask of `0002` instead of the more restrictive `0022`.  so when someone on such a configuration does a git-checkout of an obelisk project, the obelisk thunk ends up with permissions of `775`, but the obelisk command refuses to hand-off if any of those directories (`.`, `.obelisk` or `.obelisk/impl`) are group writable.

It would be much nicer if `ob` honored the umask, checking that traversed directories are at least as restrictive as `umask | 0002`

**Comment by danbornside** [comment]
To add insult to injury, even if you had chmoded the relevant dirs, if you happen to `ob thunk unpack ... ob thunk pack`, the file permissions revert to whatever is determined by the umask, and handoff stops working again.

**Comment by 3noch** [comment]
So the solution would be care as much about group-writable as the umask does. We'd still put our foot down about world writable though, as you suggest.

**Comment by 3noch** [comment]
This was fixed in #578
