### ISSUE TITLE
ob deploy push fails due to missing github.json file in nix store entry

### ISSUE THREAD

**Issue by JBetz** [obsidiansystems/obelisk#234]
After successfully running `ob deploy init ...`, `ob deploy push` fails because `/.obelisk/impl/github.json` isn't in the nix store entry for the app.

```
$ ob deploy push -v
Starting Obelisk </nix/store/59m4lgsy2gz4r3snbdbl1sny7yiyib7s-obelisk-command-0.1/bin/ob> args=["deploy","push","-v"] logging-level=Debug
Creating process: RawCommand "nix-build" ["./.obelisk/impl","-A","command","--no-out-link"]
error: opening file '/nix/store/jrj23bykinvsnsm5nvmnzn1186jmhqkb-app-0b220af/.obelisk/impl/github.json': No such file or directory
(use '--show-trace' to show detailed location information)
✖ Locating project obelisk
Process exited with code 1; RawCommand "nix-build" ["./.obelisk/impl","-A","command","--no-out-link"]
```

Does this suggest that something is wrong with my file structure? My `./obelisk/impl/default.nix` and `.obelisk/impl/github.json` files are identical to the ones created by `ob init`. And `app/.obelisk/impl/github.json` exists, and so does `app-deploy/src/git.json`, but `app-deploy/.obelisk/impl/github.json` does *not*.

Running on NixOS.

**Comment by 3noch** [comment]
`ob deploy` should be getting obelisk from your app (via `src/git.json`). Does your app have `.obelisk/impl/github.json` checked in to the same commit that `src/git.json` is pointing to?

**Comment by JBetz** [comment]
@3noch it did not, and after adding it the deploy command works. So yeah, it seems that was the problem. I must have messed something up when I was playing around with `ob thunk`. 

Thanks. :)

**Comment by 3noch** [comment]
No problem. If you end up with a `src` thunk that has a broken version of obelisk, you can use `ob --no-handoff deploy update` to get back onto a working thunk where `ob deploy` works.
