### ISSUE TITLE
ObeliskWidget is missing MonadJSM constraint

### ISSUE THREAD

**Issue by JBetz** [obsidiansystems/obelisk#241]
I need to use `GHCJS.DOM.Types.MonadJSM`'s `currentWindow` method in order to react to window events, but this constraint currently isn't provided by the `ObeliskWidget` that the frontend widgets are forced to run under. And adding it resulted in backend build errors, presumably because it relies on a `GHCJS` module.

Is there another way to get window events? And if not, can the `MonadJSM` constraint somehow be enabled for the frontend without interfering with the backend?

**Comment by ryantrinkle** [comment]
Obelisk now pre-renders the page on the server side, so to create a widget that relies on JS, you can use [`prerender`](https://github.com/reflex-frp/reflex-dom/blob/8bde2d72193369c92a995820ca1f56690d3c8ec3/reflex-dom-core/src/Reflex/Dom/Prerender.hs#L47).  You supply it two widgets, and the first will be used for server-side rendering, while the second will be used for client-side rendering (and will have access to JS).

**Comment by ryantrinkle** [comment]
Leaving this open so I remember to add documentation for this.
