### ISSUE TITLE
ob deploy push fails, needs config argument

### ISSUE THREAD

**Issue by cah6** [obsidiansystems/obelisk#263]
So close! When trying to run `ob deploy push` from my deploy directory, it's failing with:
```
$ ob deploy push -v
Starting Obelisk </nix/store/3lr65id93gb95q6xc77v8sgx5s0035gm-obelisk-command-0.1/bin/ob> args=["deploy","push","-v"] logging-level=Debug
Not in a project; no need to hand off
Not handing off
Creating process: RawCommand "nix-build" ["./src","-A","server","--argstr","hostName","myhost","--argstr","adminEmail","myeail","--argstr","routeHost","myroute","--arg","enableHttps","false","--no-out-link"]
error: cannot auto-call a function that has an argument without a default value (‘config’)
✖ Running nix-build on ./src [server]
Process exited with code 1; RawCommand "nix-build" ["./src","-A","server","--argstr","hostName","myhost","--argstr","adminEmail","myemail","--argstr","routeHost","myroute,"--arg","enableHttps","false","--no-out-link"]
```
even though this dir contains my config folder (didn't change anything). I can actually have that command go through if I manually append the config dir to it with `--argstr config /full/path/to/deploy/config` to run:
```
nix-build ./src -A server --argstr hostName myhost --argstr adminEmail myemail --argstr routeHost myroute --arg enableHttps false --no-out-link --argstr config /full/path/to/deploy/config
```
though I don't know what `ob deploy push` does after that. 

By the way, since I'm pretty close to deploying something with obelisk, I'd like to give feedback on the pain points I felt throughout that process. Is opening an issue here the best way to provide feedback like this, or is there some better forum?

**Comment by tomsmalley** [comment]
`ob deploy` should also be handing off to the obelisk in `.obelisk/impl`. Could you try re-initialising your deployment directory? You'll probably need to bump obelisk in your project first, or it'll hand off to the old version.

> By the way, since I'm pretty close to deploying something with obelisk, I'd like to give feedback on the pain points I felt throughout that process. Is opening an issue here the best way to provide feedback like this, or is there some better forum?

Yes, this is the right place, thanks!

**Comment by dfordivam** [comment]
Looks like this issue got resolved by properly setting/upgrading obelisk.
