### ISSUE TITLE
Webassembly build with asterious

### ISSUE THREAD

**Issue by janat08** [obsidiansystems/obelisk#283]
The performance is the worst.

**Comment by hSloan** [comment]
@janat08 Improvements coming soon. Thanks!

**Comment by janat08** [comment]
There's a benchmarking repo here: https://krausest.github.io/js-framework-benchmark/current.html, there's a repo behind it.

**Comment by ali-abrar** [comment]
This isn't something we're actively pursuing, but we'd be happy to work with anyone who is interested in adding this sort of support. Closing this until such a person comes along.
