### ISSUE TITLE
Command line option for changing the deployment branch

### ISSUE THREAD

**Issue by mightybyte** [obsidiansystems/obelisk#284]
The way I was told to change the deployment branch was to edit `deploy/src/git.json` and change the branch, then run `ob deploy update`.  This is easy enough, but not at all discoverable.  It would be really helpful if there was an `ob deploy` subcommand that did this.

**Comment by ryantrinkle** [comment]
There should also be a corresponding `ob thunk` command to switch branches.

**Comment by 3noch** [comment]
Perhaps both `ob deploy update` and `ob thunk update` could take an extra argument like `--ref <branch>`

**Comment by ali-abrar** [comment]
ob thunk update takes `--branch` now.

**Comment by mightybyte** [comment]
Is there some place you could mention this in `ob deploy` documentation?  There's no way I would have thought to look at the docs for `ob thunk` to solve this problem.

**Comment by 3noch** [comment]
I personally would vote for getting rid of `ob deploy update` and just making people realize that `src` is a thunk... Then you don't have to learn two APIs for the same thing.

**Comment by ryantrinkle** [comment]
@3noch I'm not so sure about that.  They're doing the same thing under the hood, but I'm not sure they express the same intent.  Is `ob thunk update src` the only thing `ob deploy update` will *ever* do?  Perhaps, but I'm not sure.

**Comment by 3noch** [comment]
If the intent was for them to diverge at some point then it makes sense to keep them separate.
