### ISSUE TITLE
"ob run" should work offline

### ISSUE THREAD

**Issue by mightybyte** [obsidiansystems/obelisk#297]
Nix in general is pretty bad with respect to working offline, but at least I know how to do it.  With `ob run` there doesn't seem to be any way to do offline development.

**Comment by 3noch** [comment]
If you open `nix-shell -A shells.ghc` manually *before* running `ob run` it will let you configure how things get built before `ob run` tries to do it. Of course, this is a workaround at best...

**Comment by mightybyte** [comment]
Thanks, good to know.  My point with this ticket is that it should be easy and discoverable, not just possible.

**Comment by 3noch** [comment]
Much agreed.

**Comment by ryantrinkle** [comment]
Yes, definitely.  Also, obelisk should create GC roots for everything it
needs, so that nix-collect-garbage doesn't set the user back.

**Comment by mightybyte** [comment]
Just now I was about to open another ticket entitled "allow customization of the internal nix commands used by obelisk", but I realized that that is actually a generalization of this ticket.  My new motivation was that I have a nix binary cache that I occasionally use by manually adding `--option substituters ...` to the nix-build command line.  Doing so would probably have sped up `ob run`, but I didn't have a way to tell ob run to use this.  Not sure whether you want a separate ticket or not, but I thought I'd mention it here first to keep things minimal.

**Comment by ElvishJerricco** [comment]
@mightybyte It'd probably be a good idea for `ob` to have an `--option` argument that passes options through to Nix.

**Comment by madeline-os** [comment]
I am closing in favor of enabling nix argument pass through. We will include a FAQ entry for this use case.
