### ISSUE TITLE
Type mismatch Text after following readme

### ISSUE THREAD

**Issue by SebastianCallh** [obsidiansystems/obelisk#3]
When installing Obelisk on Ubuntu 16.04 by following the instructions in the readme (installing Obelisk in the nix-env, and using hub) the command `ob run` gives the following error when it tries to build the frontend. 

    frontend/src/Frontend.hs:18:23: error:
    • Couldn't match expected type ‘text
       1.2.2.2@text1.2.2.2-1cn50juu89QSL9QkUVcRY:Data.Text.Internal.Text’
                  with actual type ‘T.Text’
      NB: ‘T.Text’
            is defined in ‘Data.Text.Internal’
                in package ‘text-1.2.2.2@text-1.2.2.2-KC7dWoG09dA1F6jKj5GSqh’
          ‘text-1.2.2.2@text-1.2.2.2-1cn50juu89QSL9QkUVcRY:Data.Text.Internal.Text’
            is defined in ‘Data.Text.Internal’
                in package ‘text-1.2.2.2@text-1.2.2.2-1cn50juu89QSL9QkUVcRY’
    • In the second argument of ‘($)’, namely ‘T.pack commonStuff’
      In the second argument of ‘($)’, namely ‘text $ T.pack commonStuff’
      In a stmt of a 'do' block: el "p" $ text $ T.pack commonStuff 

I am not sure where to start searching for the issue so unfortunately I haven't tried anything to solve it yet.

**Comment by ryantrinkle** [comment]
Hi @SebastianCallh!  That looks to me like something that could be caused by other Haskell dependencies kicking around in ~/.cabal or ~/.ghc.  Could you try moving those out of the way (e.g. rename to .cabal.old and .ghc.old) and see if that fixes it?

**Comment by SebastianCallh** [comment]
Hi @ryantrinkle! Thank you for that amazingly fast answer.

Ok, right, we don't want Obelisk to use global dependencies but the ones in the local nix environment. I renamed those directories, bu running `ob run` again after renaming those gives the very vague error 

    <interactive>:10:1: error:
      parse error on input ‘$’
      Perhaps you intended to use TemplateHaskell

Do you know where the code that triggers this is? I once again am not sure where to start looking.

**Comment by ryantrinkle** [comment]
@luigy Any idea where this could be coming from?

**Comment by SebastianCallh** [comment]
Hi @luigy! Running the example app with your changes did indeed solve the problem.

Thank you for the quick response and keep up the amazing work with Reflex!

**Comment by ryantrinkle** [comment]
@SebastianCallh Looks like this should be closed out.  Thanks for trying things out and giving us all the feedback!
