### ISSUE TITLE
Add the ability to run app locally with GHCJS-generated code

### ISSUE THREAD

**Issue by mightybyte** [obsidiansystems/obelisk#302]
There are some circumstances where you need to test the GHCJS-generated code.  The current `ob run` behavior doesn't seem o allow this.

**Comment by 3noch** [comment]
This is done with `nix-build -A exe`...albeit not documented?

**Comment by ElvishJerricco** [comment]
@3noch That wouldn't include spinning up the backend and serving assets.

**Comment by 3noch** [comment]
It doesn't *include* it but you can do it: `mkdir tmp && ln -s $(nix-build -A exe --no-out-link)/* tmp && cd tmp && ./backend`.

**Comment by 3noch** [comment]
Oh but I guess @mightybyte wants a way to do a minimal build of just GHCJS output but still use `ghci` for the backend? That would indeed be nice. `nix-build -A exe` not only builds frontend and backend, but it also runs the GHCJS output through closure-compiler so your build times are pretty long.

**Comment by mightybyte** [comment]
At the moment I don't particularly care how the backend gets run.  I just know that there is a need to run the actual generated JS in some way.  From there I'll leave it to you all to figure out the best scheme, but I would note that users will probably want an easy way to do both forms sooner or later.

**Comment by ali-abrar** [comment]
Documented [here](https://github.com/obsidiansystems/obelisk#locally)
