### ISSUE TITLE
HTTPS deployment should not be required

### ISSUE THREAD

**Issue by mightybyte** [obsidiansystems/obelisk#305]
When I do `ob deploy init` with `--route http://...`, I get this error:

```
Route (http://pact-web-beta.kadena.io/) must be HTTPS
```

I understand that HTTPS is recommended, but obelisk should still let me do an HTTP deploy.

**Comment by ryantrinkle** [comment]
I think that error message is wrong.  Could you try giving `--disable-https` ?

**Comment by hSloan** [comment]
@mightybyte Did the `--disable-https` flag work out for you?

**Comment by luigy** [comment]
Another thing that could be done here is to base whether to enable https from the arg passed to `--route` instead of having another flag to set that `--disableHttps`. So `--route http://` would disable `https`, but `examples.com` or `https://example.com` would have it on by default

**Comment by mightybyte** [comment]
I never got around to trying this again since I had already gotten https set up.

**Comment by ingenieroariel** [comment]
This should be closed in favor of: https://github.com/obsidiansystems/obelisk/issues/576
