### ISSUE TITLE
How to set the target Android API level?

### ISSUE THREAD

**Issue by sj4nes** [obsidiansystems/obelisk#316]
My silver-searcher foo is failing me.  I have been searching the `obelisk` and `android-activity` repositories. 

Currently when I try to upload an APK, the Play Developer console reports:

> Your app currently targets API level 25 and must target at least API level 26 to ensure it is built on the latest APIs optimized for security and performance. Change your app's target API level to at least 26

**Comment by sj4nes** [comment]
Found `targetSdkVersion 25` in `build.gradle.nix` at line 43 inside a Nix package that may have been automatically generated--so now how to get that to change from my project's configuration is the new question.

**Comment by hSloan** [comment]
@sj4nes Thanks for reaching out. We're currently working on this by exposing configuration in reflex-platform and updating nixpkgs to include API level 26.

**Comment by ali-abrar** [comment]
The target sdk version has been bumped to abide by the google requirement, but it isn't easily configurable yet

**Comment by madeline-os** [comment]
I am closing this, as the original question was answered (it's not easily possible), and the issue that motivated the question has been fixed. If you still have a use-case for manually changing the API level, feel free to open a new ticket.
