### ISSUE TITLE
need Bluetooth device support with native android application

### ISSUE THREAD

**Issue by hSloan** [obsidiansystems/obelisk#333]
According to these MDN docs (https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API) using javascript to pair with bluetooth devices is not supported in Android WebView. 

In the case of a Native Android Application, some alternatives I've considered are Android/Java FFI. 

I've looked into using the `jvm`and `inline-java` haskell packages so far in the `frontend`, it seems like ghc is having a problem deducing a `Coercible` instance within `MonadWidget`. There doesn't seem to be a way to manually create an instance of Coercible without getting an error, so I'm at a bit of a stand-still here. 

Not sure if this approach is the best approach to having a Bluetooth device pair with an Obelisk App, any suggestions or feedback would be greatly appreciated. Thanks in advance.

**Comment by eskimor** [comment]
In Gonimo, I simply used JavaScript for interacting with the host. This is a quite straighforward approach as we already have jsaddle, I am simply extending the browser API:

https://github.com/eskimor/reflex-dom/blob/gonimo/reflex-dom/java/org/reflexfrp/reflexdom/MainWidget.java#L36

https://github.com/eskimor/reflex-dom/blob/gonimo/reflex-dom/java/org/reflexfrp/reflexdom/MainWidget.java#L71

It is a bit awkward having to hack on reflex-dom on this, but I don't know a better way at the moment.

**Comment by hSloan** [comment]
@eskimor Thanks a bunch for sharing this implementation. I'll will give this a try.

**Comment by eskimor** [comment]
glad if it helped :-)
