### ISSUE TITLE
ob run: custom host/ port argument

### ISSUE THREAD

**Issue by srid** [obsidiansystems/obelisk#34]
To allow multiple obelisk apps to run locally. 

Example: `ob run -h 0.0.0.0 -p 8003`

**Comment by ryantrinkle** [comment]
Small nitpick: I think usually the binding IP address (`0.0.0.0`) is usually called the "interface" or something like that, so it would be `-i` rather than `-h`.  Also, we should have long forms for both of these, e.g. `--port`.

**Comment by ali-abrar** [comment]
All you need to do now is modify `config/common/route`. You can, e.g., change it to `http://localhost:8001` to use port `8001` instead of the default.
