### ISSUE TITLE
Default Android frontend does not build

### ISSUE THREAD

**Issue by drbsg** [obsidiansystems/obelisk#349]
I was just working through the documentation and sanity checking the builds and found I cannot build the Android frontend:
```
Bretts-MBP:Experiments brett$ mkdir obelisk-test
Bretts-MBP:Experiments brett$ cd obelisk-test/
Bretts-MBP:obelisk-test brett$ ob init
/private/var/folders/g3/jdltgkjn5_l61y3yyyl56vph0000gn/T/ob-init-85f302e78b82f663/.obelisk/impl: command not cached, building ...
Tip: Press Ctrl+e to display full output
⇾ Setting up obelisk ✔ Built  on /private/var/folders/g3/jdltgkjn5_l61y3yyyl56vph0000gn/T/ob-init-85f302e78b82f663/.obelisk/impl [command]
/private/var/folders/g3/jdltgkjn5_l61y3yyyl56vph0000gn/T/ob-init-85f302e78b82f663/.obelisk/impl: skeleton not cached, building ...
⇾ Setting up obelisk ✔ Built  on /private/var/folders/g3/jdltgkjn5_l61y3yyyl56vph0000gn/T/ob-init-85f302e78b82f663/.obelisk/impl [skeleton]
✔ Setting up obelisk
✔ Copying project skeleton
Bretts-MBP:obelisk-test brett$ ls
backend		cabal.project	common		config		default.nix	frontend	static
Bretts-MBP:obelisk-test brett$ nix-build -A android.frontend -o result-android
error: attribute 'frontend' in selection path 'android.frontend' not found
```

`frontend.ios` and `exe` targets both work fine. The version of obelisk installed is v0.1 going by the following:
```
Bretts-MBP:matching brett$ ls -l $(which ob)
lrwxr-xr-x  1 brett  wheel  70  1 Jan  1970 /Users/brett/.nix-profile/bin/ob -> /nix/store/g318wkhafni204l8ma0244m24k165g9g-obelisk-command-0.1/bin/ob
```

This is on a Mac running Mojave if it makes a difference.

**Comment by eskimor** [comment]
To my knowledge it is not possible to build an Android application on Mac. You will need a Linux machine for this. Same holds the other way round - you can't build an iOS application on Linux - you will need MacOS for this.

I believe not being able to build iOS apps on Linux is due to licensing issues, I don't know what's the problem for building Android applications on MacOS.

**Comment by ryantrinkle** [comment]
@eskimor That's correct.

@drbsg Unfortunately, we don't currently support building Android apps on a Mac.  I believe it should be possible in theory, but it wasn't something we were able to figure out in the time we could allocate.  If you're interested in trying to figure this out, we'd be happy to help!  But if you'd just like to get it built ASAP, the easiest way will be to use a virtual machine with linux for your Android builds.

**Comment by drbsg** [comment]
Thank you for clarifying. It wasn't clear to me from the documentation that this was the case.

**Comment by ali-abrar** [comment]
New documentation added in reflex-frp/reflex-platform#475 and #389 

We'll probably add support for macOS android builds in the future, but at least the errors will be more intelligible now. Thanks for reporting this.
