### ISSUE TITLE
How to pass in configs in Android?

### ISSUE THREAD

**Issue by eskimor** [obsidiansystems/obelisk#398]
There is the _android function in default.nix which takes a config path, but it is not obvious how to pass in that config path, as the `android` attribute gets initialized with `_android null`.

**Comment by ali-abrar** [comment]
Doesn't it just use the `config` directory excluding the backend configs?

**Comment by kmicklas** [comment]
@ali-abrar That's the intention but it appears to be broken. I don't even see the configs in the APK.

**Comment by ali-abrar** [comment]
Ok, when we address this one we should add a test that builds the APK and
checks that the result contains the expected config files.

This has to be a fairly recent regression: we've got deployed apps that
require and successfully use this functionality.

**Comment by eskimor** [comment]
@ali-abrar It does not apparently. I also don't see any config in the apk. But in addition, I don't think that just using the config directory would be a good idea, as usually I would want different configs for Android than I do for development.

**Comment by kmicklas** [comment]
I think it might still work with `ob deploy`, but the development configs should be put in the APK that you get with `nix-build -A android.frontend`.

**Comment by eskimor** [comment]
Wait a minute - I can deploy Android with `ob deploy`?! `ob deploy --help` says nothing about that - *checking source ...*

**Comment by eskimor** [comment]
indeed, there is a `deployMobile` function, also the REAME has been updated at some point - *sweet*!

But still, if the config path could be configurable somehow this would still be nice. As even during development the needed configs will very likely differ from a local host testing environment. Anyhow, this might be less of an issue if the `ob deploy` for Android does not enforce all changes to be checked in and pushed for testing.

**Comment by kmicklas** [comment]
I don't think we should encourage using different configs for different platforms in development builds. If you need platform-specific configuration you can use different config keys and read the ones for the host platform.

**Comment by eskimor** [comment]
I am actually thinking about config/common/route in particular, which would be http://localhost:8000 in development builds - that can't work in any Android build that makes use of a backend.

**Comment by ali-abrar** [comment]
But whatever you set it to so that it works on android ought to work for
local development as well :)

**Comment by eskimor** [comment]
> But whatever you set it to so that it works on android ought to work for local development as well :)

Haha - that's a valid point. I usually want localhost for `ob run` though, but anyway if it picks up some config, that would definitely be the most important part. ;-)
