### ISSUE TITLE
Fetching widget data while prerendering

### ISSUE THREAD

**Issue by aveltras** [obsidiansystems/obelisk#399]
After browsing the obelisk examples, it seems the first widget given to the prerender function (the one to be rendered server side) is always some kind of placeholder with a text like "loading.." waiting for the second widget to replace it when the whole thing has loaded and data has been fetched from the server.

Are there solutions to abstract the data fetching part so that, for example, if i have clearly defined Request / Response pairs like provided by the reflex-websocket-interface package, the widget can be fully prerendered server-side (not just placeholder text) by handling a given Request directly without waiting for it to be sent via websockets by the frontend ?

**Comment by ryantrinkle** [comment]
In the past, we've written server-side prerendering that issued DB queries and actually filled in data server-side; however, that requires pretty serious integration between the DB and the prerendering infrastructure.  Right now, Obelisk doesn't have much in the way of database integration, so this would be difficult to do.  However, it's definitely possible!

**Comment by aveltras** [comment]
The relevant code seems to be in the **renderFrontendHtml** function in the Frontend module.

Do you think it's much different from the HasCookies type class which get the cookies either from the request (snap side)
```
instance HasCookies Snap where
askCookies = map (\c -> (cookieName c, cookieValue c)) <$> getsRequest rqCookies
```
 or from the document (browser side) 
```
instance (MonadJSM m, RawDocument (DomBuilderSpace (HydrationDomBuilderT s t m)) ~ Document) => HasCookies (HydrationDomBuilderT s t m) where
askCookies = fmap (parseCookies . encodeUtf8) $ getCookie =<< askDocument
```

? 

There would be a HasDataSource kind of constraint which would accept Requests and would either process them through websockets (client side) or throug direct calls (server side).

Do you see any blocking issue with this ?

I might try to implement that if you think it's viable but i'm no haskell expert :)

**Comment by 3noch** [comment]
@aveltras That sounds like a reasonable approach. I'm not (yet) sure it would be ideal for a general solution for all obelisk apps, but there shouldn't be any reason you can't implement this abstraction rather easily in your own app. I'd be curious to hear how it goes if you do!

**Comment by aveltras** [comment]
In fact, i think the cleaner solution would be to rely on graphql for this and having each reflex widget define the data it needs. Client and server would then be less coupled. Too bad there doesn't seem to be any viable graphql client library at the moment in the haskell ecosystem.

**Comment by 3noch** [comment]
Your abstraction would, I imagine, work regardless of what data-supplying mechanism you used.

**Comment by kmicklas** [comment]
@aveltras Check out `QueryT`/`MonadQuery` in Reflex. It can be used for roughly the purpose you're describing with GraphQL. However it still needs special integration with Obelisk to be used in prerendering.

**Comment by aveltras** [comment]
Following discussion held at https://github.com/reflex-frp/reflex-platform/issues/498, I'm reopening this issue.
I've started work here https://github.com/obsidiansystems/obelisk/compare/develop...aveltras:datasource to enable the "full prerendering" behavior.
Didn't want to go ahead and adapt the frontend package (mainly because i'm still not clear on how to make this interact with the routing system) before knowing if this already looks like the way to go or not for expert obelisk users :)

**Comment by 3noch** [comment]
If you're embarking on this, you'll want to have some idea of how hydration fits in (cc @tomsmalley).

**Comment by ryantrinkle** [comment]
@aveltras It would be totally fine to add something *other than* MonadIO that allows lifting IO - something like `unsafeLiftBackendIO` or another suitably-scary name.

**Comment by madeline-os** [comment]
Hi, this is an interesting idea. Over the years, I have seen a few attempts at doing this for obelisk. It's a complex problem, and the design space is large. If you are still interested in this project, and you have a plan, I am here to help shepherd the work along. In particular, it won't be something that is solvable in a single issue or PR!

I am closing, but you are welcome to re-open to revisit the idea.
