### ISSUE TITLE
Unable to build for android right now

### ISSUE THREAD

**Issue by rprije** [obsidiansystems/obelisk#412]
Performing a fresh ob init and attempting to build for android results in the following error:

```
$ mkdir tmpob
$ cd tmpob/
$ ob init
/tmp/ob-init-703657eeab75ba7c/.obelisk/impl: command not cached, building ...
⇾ Setting up obelisk ✔ Built  on /tmp/ob-init-703657eeab75ba7c/.obelisk/impl [command]
/tmp/ob-init-703657eeab75ba7c/.obelisk/impl: skeleton not cached, building ...
⇾ Setting up obelisk ✔ Built  on /tmp/ob-init-703657eeab75ba7c/.obelisk/impl [skeleton]
✔ Setting up obelisk
✔ Copying project skeleton

$ nix-build --cores 7 -A android.frontend -o result-android
error: You must accept the Android Software Development Kit License Agreement at
https://developer.android.com/studio/terms
by setting nixpkgs config option 'android_sdk.accept_license = true;'

(use '--show-trace' to show detailed location information)

```

It appears this is fixed in the latest version of obelisk, but that doesn't seem to be what `ob init` is currently initialising to.

**Comment by kmicklas** [comment]
Until we release to `master` again, you'll need to update to the `develop` branch, which has the fix.

You can update an existing project with `ob thunk update --branch develop .obelisk/impl` or start a new project with `ob init --branch develop`. Then you can pass `config.android_sdk.accept_license = true;` to the import of Obelisk in `default.nix`.
