### ISSUE TITLE
Unable to use android-activity on latest obelisk platform

### ISSUE THREAD

**Issue by rprije** [obsidiansystems/obelisk#413]
If I update .obelisk/impl/github.json to point to the latest obelisk (currently f68858627ea8614c2ac412b76d5c0403b89039fd) then I can get past the licensing problems found in #412. At that point, I then add android-activity to frontend/frontend.cabal under the frontend executable build-depends.

Attempting to build for android gives me:

```
$ nix-build --cores 7 -A android.frontend -o result-android
[...]
Setup: Encountered missing dependencies:
android-activity -any
```

Attempting to build natively for linux gives me:

```
$ nix-build --cores 7 -A exe -o result-exe
[...]
Configuring android-activity-0.1...
[...]
Setup: Encountered missing dependencies:
base >=4.9 && <4.11
```

Adding the following to default.nix:

```
  packages = {
    android-activity = pkgs.fetchFromGitHub {
      owner  = "obsidiansystems";
      repo   = "android-activity";
      rev    = "af7139857b33b8617539a3bb3d8ac91c91daa3de";
      sha256 = "0wphsfpswbw5ihqsx456vh406rc8ca0anfkcaz4rxx4lm8prn444";
    };
  };
```

then attempting to build android again gives me:

```
$ nix-build --cores 7 -A android.frontend -o result-android
[...]
Configuring text-show-3.7.4...
[...]
Setup: Encountered missing dependencies:
integer-gmp -any
```

text-show comes from the recently added log dependency in android-activity.

**Comment by eskimor** [comment]
First of all, you should not need to add android-activity to your cabal files.

What I needed for my project is a modified version of android-activity, in case you need that at well you need to override it correctly - you can check out the reflex-platform source to see how it gets imported here. The following is derived from that and worked for me:

I added an override with a modified version this way:

```
overrides = self: super:
  {
          android-activity = self.callPackage (hackGet ./dep/android-activity) {
            inherit (nixpkgs.buildPackages) jdk;
          };
  }
```

you need to add hackGet to the arguments of project:

```
project ./. ({pkgs, hackGet, ... }:
```

You will also need to add obelisk and reflex-platform to your default.nix arguments:

```
{ system ? builtins.currentSystem # TODO: Get rid of this system cruft
, iosSdkVersion ? "10.2"
, obelisk ? (import ./.obelisk/impl { inherit system iosSdkVersion; })
, nixpkgs ? obelisk.reflex-platform.nixpkgs
}:
```

dep/android-activity can be created like this:

```
mkdir dep
cd dep
# Makes more sense for some fork, otherwise this is pretty pointless:
git clone git@github.com:obsidiansystems/android-activity.git
ob thunk pack android-activity
```

**Comment by rprije** [comment]
I'm hoping I can get away without needing to modify android-activity at this stage, so I hopefully won't need most of what you mention. But thanks for that; I had been looking at how to do what you describe and had only figured out a small part of what you mention, so your description is very helpful.

> First of all, you should not need to add android-activity to your cabal files.

I tried this out but it didn't work for me. Here's what I tried:

1. Started with a freshly initialised obelisk project
2. Did `ob thunk update --branch develop .obelisk/impl` to get a version supporting Android licensing (per #412 ) and added the necessary config.android_sdk.accept_license = true;
3. To `Frontend.hs` added the line `import Android.HaskellActivity` 
4. Built with `$ nix-build --cores 7 -A android.frontend -o result-android`
5. Got the following error: `src/Frontend.hs:16:1: error: Could not find module ‘Android.HaskellActivity’`

This suggests to me I do need android-activity in my cabal file which brings me back to the original issue I was having..

**Comment by eskimor** [comment]
Why do you need to import Android.HaskellActivity?

**Comment by rprije** [comment]
I'm importing it because I've found that my application, when compiled to android, has buggy behaviour with regards to processing camera input whenever the application gets paused. So I want to use the onPause / onResume functionality available in android-activity to add support for pausing the events triggering attempted camera reads.

**Comment by eskimor** [comment]
I see! I had something working for Gonimo, prior to Obelisk:

https://github.com/gonimo/gonimo/blob/master/front-android/app/Android.hs

I think, I needed to adjust reflex-dom to export a needed file to make that work. I am currently in the process of porting Gonimo to Obelisk, but I did not yet get to porting that part. (With a little luck I might get away without that need actually.) 

But back to the problem at hand, the reason Android.HaskellActivity is not found, is because android-activity will only be present on the Android build. So I suggest the following in your _executable_*) section in your cabal file:

```cabal
 if os(linux-android)
    build-depends:
      android-activity
    cpp-options: -DANDROID
```

And then in your frontend/src-bin/main.hs:

```haskell
{-# LANGUAGE CPP #-}
import Frontend
import Common.Route
import Obelisk.Frontend
import Obelisk.Route.Frontend
import Reflex.Dom
#ifdef ANDROID
import Android.HaskellActivity
#endif

main :: IO ()
main = do
  let Right validFullEncoder = checkEncoder backendRouteEncoder
  run $ runFrontend validFullEncoder frontend
```

Then maybe with some adjustments to reflex-dom (see my remark above), you should be able to replace run with something that handles Android events.

*) the Android specifics need to be handled in frontend/src-bin/main.hs not in src/Frontend.hs.

**Comment by eskimor** [comment]
**) Don't ask me, why it actually tries to build anything that is not for Android if you do `nix-build -A android.frontend`, but it obviously does.

**Comment by rprije** [comment]
It took me a while to get back to this, but this does indeed seem to help me get past my problem. Thank you so much for taking the time to help me out, @eskimor !
