### ISSUE TITLE
Reflex-dom 0.5 Prerender & Obelisk Routing issues 

### ISSUE THREAD

**Issue by benkolera** [obsidiansystems/obelisk#416]
I've got an issue with the new prerendering types combined with the obelisk routing `subRoute` function that I can't quite figure out to encode the types.

If you use `subRoute` it forces the top of your context to be concretely RoutedT so it can peel the layer off and replace it with the sub part of the route. This makes a lot of sense. So if you want to wire a ReaderT / EventWriterT / etc in, you want to end up with something like: `RoutedT t r (ReaderT e m) a` and use `mapRoutedT (flip runReaderT env)` to get rid of your layer before handing it to obelisk. This works perfectly OK when the function to run the reader is pure, but often it is not and it is this point where I start getting into trouble with the types.   

See the following example, where running the readerT involves (a contrived-but-minimal-example of) going off to local storage in MonadJSM. In ObeliskWidget, Client m does not have a MonadJSM or DomBuilder, which my current intuition makes me think that ObeliskWidget is missing some constraints. Isn't `(Client m) ~ HydrationDomBuilderT` at the top level in obelisk in runFrontend, or am I missing something?

I'm hoping that I'm just being silly or there are just some missing constraints in obelisk, because this has me a little stuck. :slightly_smiling_face: @tomsmalley ?

```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE ScopedTypeVariables #-}
module Frontend where

import qualified Data.Text as T
import Data.Foldable (for_)
import Data.Functor (void)
import Control.Monad.Fix (MonadFix)
import Obelisk.Frontend
import Obelisk.Route
import Obelisk.Route.Frontend
import Reflex.Dom.Core

import Common.Api
import Common.Route
import Obelisk.Generated.Static
import Control.Monad.Reader (ReaderT, runReaderT, ask, lift)
import GHCJS.DOM (currentWindowUnchecked)
import GHCJS.DOM.Types (MonadJSM)
import GHCJS.DOM.Window (Window, getLocalStorage)
import GHCJS.DOM.Storage (getItem)

runStorage :: (MonadJSM m) => ReaderT (Maybe T.Text) m a -> m a
runStorage m = getStorage >>= runReaderT m

runStoragePure :: ReaderT (Maybe T.Text) m a -> m a
runStoragePure = flip runReaderT Nothing

getStorage :: (MonadJSM m) => m (Maybe T.Text)
getStorage = do
  w <- currentWindowUnchecked
  s <- getLocalStorage w
  getItem s ("stored_item" :: T.Text)

pageHead :: (DomBuilder t m) => m ()
pageHead = el "title" $ text "Obelisk Minimal Example"

pageBody
  :: forall t m
  .  (DomBuilder t m, MonadFix m, MonadHold t m, Monad m)
  => RoutedT t (R FrontendRoute) (ReaderT (Maybe T.Text) m) ()
pageBody =  do
  text "Welcome to Obelisk!"
  subRoute_ $ \case
    FrontendRoute_Main -> do
      el "p" $ text $ T.pack commonStuff
      mMay <- lift $ (ask :: ReaderT (Maybe T.Text) m (Maybe T.Text))
      for_ mMay $ el "p" . text
      elAttr "img" ("src" =: static @"obelisk.jpg") blank

frontend :: Frontend (R FrontendRoute)
frontend = Frontend
  { _frontend_head = prerender_ pageHead pageHead
  , _frontend_body = mapRoutedT runStoragePure pageBody
  -- Could not deduce (MonadJSM (Client m))
  --, _frontend_body = prerender_ (mapRoutedT runStoragePure pageBody) (mapRoutedT runStorage pageBody)
  --, _frontend_body = prerender_ blank (mapRoutedT runStorage pageBody)
  -- This obviously wont work because it would require: Client m ~ m
  --,_frontend_body = mapRoutedT (\m -> prerender_ (runStoragePure m) (runStorage m)) pageBody
  -- This works in 0.4
  --, _frontend_body = prerender blank $ do -- Get an m is untouchable without this outer prerender.
  --    mapRoutedT (\m -> prerender blank (runStorage m)) pageBody
  --    pure ()
  }
```

**Comment by tomsmalley** [comment]
There is definitely some weirdness with constraints happening there. Fortunately the "right" way to deal with this kind of thing avoids them entirely: make your reader take a `Dynamic` and use the version of `prerender` that allows you to access the result,

```haskell
pageBody
  :: forall t m
  .  (DomBuilder t m, MonadFix m, MonadHold t m, PostBuild t m)
  => RoutedT t (R FrontendRoute) (ReaderT (Dynamic t (Maybe T.Text)) m) ()
pageBody = do
  text "Welcome to Obelisk!"
  subRoute_ $ \case
    FrontendRoute_Main -> do
      el "p" $ text $ T.pack commonStuff
      dyn_ . fmap (traverse_ $ el "p" . text) =<< ask
      elAttr "img" ("src" =: static @"obelisk.jpg") blank

frontend :: Frontend (R FrontendRoute)
frontend = Frontend
  { _frontend_head = prerender_ pageHead pageHead
  , _frontend_body = do
    storage <- prerender (pure Nothing) getStorage
    mapRoutedT (flip runReaderT storage) pageBody
  }
```

This way the browser doesn't have to fully recreate your page, it can just add the paragraph and text node when it learns about the contents of local storage. If this was a token you want to send requests with, you'd use something like `attachWithMaybe` so the token is grabbed as necessary when you do a request.

**Comment by tomsmalley** [comment]
w.r.t. the constraints stuff, it seems to me the right constraints should be there. With `prerender_ blank $ void $ lift getStorage` I get the error

```
frontend/src/Frontend.hs:58:10-19: error:
    • Could not deduce (MonadJSM (Client m))
        arising from a use of ‘getStorage’
      from the context: ObeliskWidget js t (R FrontendRoute) m
        bound by a type expected by the context:
                   forall js t (m :: * -> *).
                   ObeliskWidget js t (R FrontendRoute) m =>
                   RoutedT t (R FrontendRoute) m ()
        at frontend/src/Frontend.hs:(55,12)-(61,3)
      or from: PrerenderClientConstraint
                 js t (Client (RoutedT t (R FrontendRoute) m))
        bound by a type expected by the context:
                   PrerenderClientConstraint
                     js t (Client (RoutedT t (R FrontendRoute) m)) =>
                   Client (RoutedT t (R FrontendRoute) m) ()
        at frontend/src/Frontend.hs:(57,22)-(58,19)
    • In the first argument of ‘lift’, namely ‘getStorage’
      In a stmt of a 'do' block: lift getStorage
      In the second argument of ‘($)’, namely ‘do lift getStorage’
   |
58 |     lift getStorage
   |          ^^^^^^^^^^
```

So we have the constraint
```haskell
PrerenderClientConstraint js t (Client (RoutedT t r m))
```

but essentially
```hs
type PrerenderClientConstraint js t m = MonadJSM m
```
so
```hs
MonadJSM (Client (RoutedT t r m))
```
from the Prerender instance of RoutedT we have
```hs
type Client (RoutedT t r m) = RoutedT t r (Client m)
```
so
```hs
MonadJSM (RoutedT t r (Client m))
```
from the MonadJSM instance of RoutedT
```hs
instance MonadJSM m => MonadJSM (RoutedT t r m)
```
thus
```hs
MonadJSM (Client m) => MonadJSM (RoutedT t r (Client m))
```

Am I missing something? @cgibbard save me

**Comment by kmicklas** [comment]
I ran into this too and I suspect https://github.com/reflex-frp/reflex-dom/pull/294 might help GHC figure this out correctly.

**Comment by benkolera** [comment]
Thanks for that help, @tomsmalley . That helped sort out my brain a lot to get a much better outcome. https://github.com/qfpl/reflex-dom-storage/pull/5/files#diff-e5269899b0235b3f89c1dee8ec397b00R198

Glad that that is still a weird thing that should work but GHC can't figure it out. It had me feeling really dumb for a while there. :slightly_smiling_face: 

We can close this if you'd like or we can wait to see if https://github.com/reflex-frp/reflex-dom/pull/294 fixes this?

**Comment by kmicklas** [comment]
I've confirmed that https://github.com/reflex-frp/reflex-dom/pull/294 fixes this issue but it also introduced small but bizarre type inference errors in the hydration tests in `reflex-dom` so GHC may still be having issues.

**Comment by benkolera** [comment]
Cool. I'll close this and we'll just track the reflex-dom work. Thanks for you help everyone!
