### ISSUE TITLE
Missing Content-Type in header

### ISSUE THREAD

**Issue by Ericson2314** [obsidiansystems/obelisk#421]
I noticed that going to `https://obsidian.systems` in Lynx the HTML was displayed as plain text.

**Comment by matthewbauer** [comment]
I don't think this is an obelisk issue. Running the skeleton app in ob run gives me:

```
curl -I http://localhost:8000/
HTTP/1.1 200 OK
Date: Tue, 26 Nov 2019 02:21:57 GMT
Server: Warp/3.2.26
Content-Type: text/html; charset=utf-8
```

Most likely it's actually the nginx configuration on obsidian.systems that is incorrect.

**Comment by matthewbauer** [comment]
Closing as it is not an issue. If you don't think that's the case, feel free to reopen.
