### ISSUE TITLE
Ghc panic if stale *.hi or *.o files are found

### ISSUE THREAD

**Issue by meditans** [obsidiansystems/obelisk#427]
If `ob run` or `ob repl` are interrupted, after I try to restart them, during the executions of the tests the following error will appear:

```
ghc: panic! (the 'impossible' happened)
  (GHC version 8.4.3 for x86_64-unknown-linux):
	Loading temp shared object failed: /run/user/1000/ghc4731_0/libghc_12.so: undefined symbol: FrontendziWidget_staticzq_closure

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug


...done
```

I noticed that this issue can be solved if I remove all the `**/*.hi` and `**/*.o` files, that are probably generated by my `dante` emacs setup. For the time being I disabled `dante` and will rely only on `ob watch` to check errors.

**Comment by eskimor** [comment]
Heads up: If you use cabal new-repl or cabal build, this will trip off `ob run` as well, you need to get rid of that ".ghc..." file.

**Comment by hSloan** [comment]
Should we consider triggering some script whenever this error occurs?

**Comment by 3noch** [comment]
We're now using ghc 8.6 so I wonder if the situation has improved at all.

**Comment by ali-abrar** [comment]
Please reopen if you're still encountering this.
