### ISSUE TITLE
Tab completion can freeze when evaluating handoff obelisk

### ISSUE THREAD

**Issue by 3noch** [obsidiansystems/obelisk#429]
I've found that hitting tab mid-command can cause the terminal to freeze while obelisk tries to evaluate the underlying nix expressions for `.obelisk/impl`. I don't immediately have a better idea, but I think it's worth thinking about how to avoid this.

```shell
ob thunk update srcAlert: Process exited with code 1; 'nix-build' './.obelisk/impl' '-A' 'command' '--no-out-link'
Running\ nix-build\ on\ ./.obelisk/impl\ \[command\]  
Process exited with code 1; 'nix-build' './.obelisk/impl' '-A' 'command' '--no-out-link'
✖ Running nix-build on ./.obelisk/impl [command]
```

**Comment by matthewbauer** [comment]
This is closely related to https://github.com/obsidiansystems/obelisk/issues/296. I think the best behavior here might be to just quit immediately if obelisk detects hashes have changed.

**Comment by kmicklas** [comment]
@matthewbauer Why not just perform tab completion with the non-handed off version?

**Comment by matthewbauer** [comment]
> Why not just perform tab completion with the non-handed off version?

Mostly because it might have different options than the project’s obelisk.

**Comment by alexfmpe** [comment]
I think I ran into this after `nix-collect-garbage`. Was trying to tab complete the directory in a `ob thunk pack`  command. 
Pressing tab would seemingly freeze the terminal with no feedback.
After doing `ob thunk pack my-folder -v` without completion, I saw a lot of dependencies being fetched. After this finished tab completion started working again.

**Comment by madeline-os** [comment]
We will try to handle this in #926
