### ISSUE TITLE
Properly handle `.ghc.environment` files

### ISSUE THREAD

**Issue by mightybyte** [obsidiansystems/obelisk#447]
I recently encountered the following error from `ob run`:

```
<interactive>:22:1-15: error:
    Not in scope: ‘Obelisk.Run.run’
    No module named ‘Obelisk.Run’ is imported.
```

It took me quite some time to figure out that a `.ghc.environment...` file had been created and was causing the error.  The obelisk project template includes a `cabal.project` file which suggests that using `cabal v2-*` commands is a supported workflow.  Ideally `ob run` would just work properly in the presence of these environment files.  But at the very least it should display an informative error message so the user can fix the problem.

**Comment by ApolloUnicorn** [comment]
Tested on https://github.com/obsidiansystems/obelisk/commit/ba0e28fcf28daf77424b26dba4565c5c07ae8daa
