### ISSUE TITLE
Exe app/ghcjs causes mem leak/crash with prerender

### ISSUE THREAD

**Issue by dfordivam** [obsidiansystems/obelisk#465]
This works fine in `ob run`, but with `nix-build -A exe` app the browser only shows "test" and then it crashes due to memory leak. Could be some issue with hydration.
```
  , _frontend_body = do
      text "test"
      void $ prerender (pure ()) $ do
        text "Welcome to Obelisk!"
        el "p" $ text $ T.pack commonStuff
        elAttr "img" ("src" =: static @"obelisk.jpg") blank
```

**Comment by tomsmalley** [comment]
Strange that this hasn't been more obvious. I've bisected it back to https://github.com/obsidiansystems/obelisk/commit/fe9bad09e05a760f0708e8d9aa7007372fa256f7

**Comment by tomsmalley** [comment]
Looks to be an underflow of `Word` here https://github.com/obsidiansystems/obelisk/blob/develop/lib/executable-config/lookup/src-ghcjs/Obelisk/ExecutableConfig/Lookup.hs#L38
