### ISSUE TITLE
performRequestAsync's response event fires three time per request

### ISSUE THREAD

**Issue by tshinohara** [obsidiansystems/obelisk#467]
title: performRequestAsync's response event fires three time per request

NOTE: It looks rather a reflex-dom's issue, but I posted here since don't know how to build/run reflex-dom individually.

When I was creating a simple GET API with background route, I noticed the result event of `performRequestAsync` was firing three times per request. I first thought its was firing evertytime XHR status changes, but after looking at `performRequestAsync` code (https://github.com/reflex-frp/reflex-dom/blob/develop/reflex-dom-core/src/Reflex/Dom/Xhr.hs#L269), my understanding is that the result should fire once per request.

Created a small repository to reproduce the problem.
https://github.com/kamoii/obelisk-ping-test

 * Simple backend api "ping" (it just responds with "pong")
 * From the frontend, ping the API everytime the buttons is pressed
 * Show how many times send request and received response

Here's the main part of front end code.
```haskell
frontend :: Frontend (R FrontendRoute)
frontend = Frontend
  { _frontend_head = el "title" $ text "Obelisk Minimal Example"
  , _frontend_body = prerender_ blank $ do
      el "h1" $ text "Backend request test."
      evBtn <- el "div" $ button "ping"
      dyPingCount <- count evBtn
      el "div" $ do
        text "ping count: "
        dynText $ T.pack . show <$> dyPingCount
      evPong <- ping evBtn
      dyPongCount <- count evPong
      el "div" $ do
        text "pong count: "
        dynText $ T.pack . show <$> dyPongCount
      pure ()
  }

ping :: _ => Event t () -> m (Event t ())
ping evInput = do
  res <- getApi BackendRoute_Ping evInput
  pure $ () <$ res

getApi
  :: _
  => BackendRoute param
  -> Event t param
  -> m (Event t XhrResponse)
getApi r evInput = performRequestAsync $ fmap mkXhrReq evInput
  where
    mkXhrReq param =
      let url = renderBackendRoute _enc (r :/ param)
      in xhrRequest "GET" url def

    _enc :: Encoder Identity Identity _ _
    Right _enc = checkEncoder backendRouteEncoder
```
Expected ping count and pong count to be same, but actually pong count increments by 3 per ping request. Following is as gif I captured using chromium with developer tools open so you can see the ping request.
![screencast-2019-06-25T02:35:38](https://user-images.githubusercontent.com/64248/60153210-8d629600-981e-11e9-9d19-a3f5ad04d7df.gif)

NOTE: The repo above uses `develop` branch.
```
$ cat .obelisk/impl/github.json
{
  "owner": "obsidiansystems",
  "repo": "obelisk",
  "branch": "develop",
  "rev": "86a9584c6d7648bd5324ef57d62421fed1bf1978",
  "sha256": "1lbii87j5530ncm6brfbzkd3wg16mgxazsf3l56zzv4c8cydilmh"
}
```

**Comment by alexfmpe** [comment]
Related to https://github.com/reflex-frp/reflex-dom/pull/255, I think

**Comment by tshinohara** [comment]
@alexfmpe Thank you. Thats definitley related. 
So its a reflex-dom, or more strictly ghcjs-dom/jsaddle issue. 
Should I close this issue?

**Comment by eskimor** [comment]
Not just related, but same issue ;-)

**Comment by tomsmalley** [comment]
This was fixed by https://github.com/reflex-frp/reflex-dom/pull/399
