### ISSUE TITLE
prerender and CORS preflight check

### ISSUE THREAD

**Issue by janat08** [obsidiansystems/obelisk#468]
After adding prerender_, the CORS preflight check errors began appearing. I would rather not have to disable CORS checks. I presume to be not an outlier.

**Comment by ohri-anurag** [comment]
@janat08 Can you provide more details around this issue? It would help us a lot if could detail the steps to reproduce the issue.

**Comment by janat08** [comment]
I might have been working in cloud ide to trigger cors, as they proxy local host.

**Comment by ohri-anurag** [comment]
Closing due to lack of reproducible steps.

**Comment by ohri-anurag** [comment]
@janat08 In case you feel that this is still an issue, do let us know. We'll be more than happy to investigate.
