### ISSUE TITLE
Add config files to mobile apps

### ISSUE THREAD

**Issue by srid** [obsidiansystems/obelisk#47]
Mobile apps currently only have `static` assets included in their assets. We should include `config` files as well.

Implementation note:
- use `exeConfig.platforms.{android, ios}.inject` (which already adds `config` to assets, but just not used in our `default.nix`) in the context of `reflexPlatform.ios.buildApp`.

**Comment by luigy** [comment]
this seems covered by which is now merged https://github.com/obsidiansystems/obelisk/pull/219
