### ISSUE TITLE
Obelisk Deploy uses wrong config when generating android apk

### ISSUE THREAD

**Issue by hSloan** [obsidiansystems/obelisk#470]
`ob deploy test android` uses config inside of src folder instead of the config within the deployment directory.

**Comment by matthewbauer** [comment]
@hSloan I am not seeing this with current develop. `ob deploy test android` is running:

```
nix-build -E 'with (import ./src {});android.frontend.override (drv: { releaseKey = (if builtins.isNull drv.releaseKey then {} else drv.releaseKey) // { keyAlias = "obelisk"; keyPassword = "123456"; storeFile = ./android_keystore.jks; storePassword = "123456"; }; staticSrc = (passthru.__androidWithConfig ./config).frontend.staticSrc;})'
```

Since `ob deploy test android` is running in the "deploy" directory it gets the right src and config.
