### ISSUE TITLE
Make shell escaping more robust

### ISSUE THREAD

**Issue by 3noch** [obsidiansystems/obelisk#476]
As @vaibhavsagar pointed out in #475 we should do better escaping shell arguments.

**Comment by 3noch** [comment]
Libraries @vaibhavsagar found that might help:
  * http://hackage.haskell.org/package/shell-escape
  * http://hackage.haskell.org/package/posix-escape

**Comment by 414owen** [comment]
So for the actual commands we're running, we're not going through a shell, we're launching processes directly (the difference is between calling System.Process.proc vs System.Process.shell), so this escaping is just necessary to show a process and its args as if it had been launched through a shell.

**Comment by madeline-os** [comment]
This seems to have been implemented. Let me know if I am misunderstanding.
