### ISSUE TITLE
`ob run` doesn't run with latest version of code

### ISSUE THREAD

**Issue by mightybyte** [obsidiansystems/obelisk#478]
Steps to reproduce:

1. Clone https://gitlab.com/mightybyte/zeus/
2. Check out commit 6f180cb2063e76f72213bc387d425d6a2fdf59ce
3. Run the app with `ob run`.
4. After it is running you should see the message `***************** getNextJob returned Nothing` printed to the console every 5 seconds.
5. Now delete line 73 in `backend/src/Backend/Build.hs` (https://gitlab.com/mightybyte/zeus/commit/6f180cb2063e76f72213bc387d425d6a2fdf59ce#9d8928888ce290022cf33404498f82c98329d32b_86_73)

Expected result:

`ob run` will rebuild and re-run the app and the `getNextJob` debug line will no longer be printed.

Actual result:

`ob run` rebuilds and reruns the app, but the `getNextJob` lines are still printed.

**Comment by ohri-anurag** [comment]
@mightybyte Is there a specific version of Obelisk that you are referring to in this issue?

I tried the following steps:
1. Checked out zeus: https://github.com/mightybyte/zeus
2. Checkout out commit 6f180cb2063e76f72213bc387d425d6a2fdf59ce.
3. Ran `ob run`.

Here is what I got:
![image](https://user-images.githubusercontent.com/10478280/166436032-5e736a3e-d538-4c41-a4e8-aac175c60b01.png)

**Comment by ohri-anurag** [comment]
Closing for now since repro steps don't produce the issue.
