### ISSUE TITLE
Make backend stdout and stderr go to journalctl instead of files

### ISSUE THREAD

**Issue by mightybyte** [obsidiansystems/obelisk#484]
Since the `backend` process is managed by systemd, my default assumption was that stdout and stderr would be in journalctl.  Having that output stored in files is harder to work with.  Was there a particular reason files were chosen?  If so, perhaps we could have it be a configurable option?

**Comment by dfordivam** [comment]
There is already a PR to fix this #453

**Comment by vaibhavsagar** [comment]
Can this be closed now?

**Comment by 3noch** [comment]
Closed by #453
