### ISSUE TITLE
Site built with nix-build will cause the page to crash (out of memory), even when the ob run site works fine.

### ISSUE THREAD

**Issue by blargg** [obsidiansystems/obelisk#498]
# Issue
When building with `nix-build -A exe`, and opening the page, the page will eventually cause the tab to crash. This is because of something running in the javascript that eventually eats up all available memory.

This is strange, because running the same server with `ob run` will not have this issue. This can be reproduced with simple examples, like the example generated with `ob init` on affected versions.

# To reproduce
`ob init` a new project
Set the contents of `.obelisk/impl/github.json` to the following (for my version, this is what is created by `ob init`)
```json
{
  "owner": "obsidiansystems",
  "repo": "obelisk",
  "branch": "master",
  "rev": "de99fc6178fe64f6ea3176746e9c273c92fb8e45",
  "sha256": "1g75262rckkpsm7d3km3wd9pch313qv1hy6kq37v96spi3byg2s9"
}
```
Build with `nix-build -A exe`
Run the backend `cd result; ./backend`
Open localhost:8000
View cpu and memory usage statistics
It should be using heavy cpu, and increasing memory until the process fails.

# Other Info
Switching to some earlier version fixed the issue for me, for example
```json
{
  "owner": "obsidiansystems",
  "repo": "obelisk",
  "branch": "master",
  "rev": "61dce9bee472a250195f2b43ee0dee31986043f5",
  "sha256": "08kazzb3a3lr8l7nspmylb9avxj97i7xkw9cpr7k2a35bq2fjb9y"
}
```

**Comment by tomsmalley** [comment]
Hi, this is probably caused by the bug fixed in https://github.com/obsidiansystems/obelisk/pull/482

Could you try that branch and see if your problem is fixed?

**Comment by blargg** [comment]
I tried again with
```json
{
    "owner": "obsidiansystems",
    "repo": "obelisk",
    "rev": "13ec4443401a6c1eef1b0ec7ee7bfbcae805fb2a",
    "sha256": "1gwa4plp8f0ki7c7a33f69gwz6vlzka4inkhjxhimhjv473487dh"
}
```

I still had the same issue.

**Comment by 3noch** [comment]
Another fix might help: https://github.com/obsidiansystems/obelisk/pull/466

**Comment by 3noch** [comment]
I've run into this before too when I didn't have a `config/common/route` file next to `backend` executable. That file should contain something like `http://localhost:8000`.

**Comment by blargg** [comment]
Ah, thanks. That was it. With #466 it's running correctly. Sorry about that, I didn't find #465 when I was searching for the issue.

Marking this one as closed.
