### ISSUE TITLE
404 Not Found for /ghcjs/all.js

### ISSUE THREAD

**Issue by MazeChaZer** [obsidiansystems/obelisk#499]
After running `nix-build -A exe -o result-exe` and then `result-exe/backend`, the page loads but I get a 404 on `/ghcjs/all.js` which means that nothing happens in the UI, events are not processed. It's a simple project where I just did an `ob init` and then added a `button` and a `dynText`. I installed Obelisk via `nix-env -f https://github.com/obsidiansystems/obelisk/archive/master.tar.gz -iA command`.

**Comment by MazeChaZer** [comment]
Nevermind, I didn't `cd` into `result-exe` and just ran `result-exe/backend`  :sweat_smile:

**Comment by bidigo** [comment]
I've just ran into this after upgrading to obelisk 0.9.0.0. Building the skeleton app and deploying locally gives back 404 when requesting /ghcjs/all.js. Tested in Firefox and Chrome.

**Comment by tomsmalley** [comment]
This should be fixed by https://github.com/obsidiansystems/obelisk/pull/810

**Comment by ali-abrar** [comment]
Resolved in release 0.9.0.1
