### ISSUE TITLE
Performing IO actions in an ObeliskWidget

### ISSUE THREAD

**Issue by MazeChaZer** [obsidiansystems/obelisk#502]
So I created a simple project using `ob init` and tried to use `performEvent` to perform IO actions over an event. However I only get the following error when I try the method described in the Reflex documentation:

```
frontend/src/Frontend.hs:25:55-76: error:
    • Could not deduce (Control.Monad.IO.Class.MonadIO (Performable m))
        arising from a use of ‘liftIO’
      from the context: ObeliskWidget js t (R FrontendRoute) m
        bound by a type expected by the context:
                   forall js t (m :: * -> *).
                   ObeliskWidget js t (R FrontendRoute) m =>
                   Obelisk.Route.Frontend.RoutedT t (R FrontendRoute) m ()
        at frontend/src/Frontend.hs:(21,12)-(27,3)
    • In the expression: liftIO UUID.nextRandom
      In the second argument of ‘($)’, namely
        ‘\ () -> liftIO UUID.nextRandom’
      In the first argument of ‘performEvent’, namely
        ‘(ffor clicks $ \ () -> liftIO UUID.nextRandom)’
   |
25 |       uuidEvent <- performEvent (ffor clicks $ \() -> liftIO UUID.nextRandom)
   |                                                       ^^^^^^^^^^^^^^^^^^^^^^
```

Looking into the definition of `ObeliskWidget`, there really is no instance of `MonadIO` specified. How can I do this? I've been searching around for some time now and would greatly appreciate if someone could give me a pointer where to look. Below is the `Frontend.hs` that doesn't work for me.

```hs
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
module Frontend where

import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import Obelisk.Frontend
import Obelisk.Configs
import Obelisk.Route
import Reflex.Dom.Core

import Common.Api
import Common.Route
import Obelisk.Generated.Static
import qualified Data.UUID.V4 as UUID
import Data.UUID (UUID)
import Control.Monad.IO.Class (liftIO)

frontend :: Frontend (R FrontendRoute)
frontend = Frontend
  { _frontend_head = el "title" $ text "Obelisk Minimal Example"
  , _frontend_body = do
      clicks <- button "Click me!"
      uuidEvent <- performEvent (ffor clicks $ \() -> liftIO UUID.nextRandom)
      return ()
  }
```

Thanks in advance! :heart:

**Comment by cgibbard** [comment]
Obelisk does prerendering of your widgets on the backend, and performing unrestricted IO actions there was considered too surprising / a bit of a security issue if you don't expect it. However, presumably you only care about these actions live on the frontend, and the Client monad inside a prerender has MonadIO. You can do something like this:

    uuidEvent <- fmap (switch . current) . prerender (return never) $ performEvent (ffor clicks $ \() -> liftIO UUID.nextRandom)

The `prerender :: Prerender js t m => m a -> Client m a -> m (Dynamic t a)` is a way of switching between one widget used during prerendering on the backend, and another once the Javascript on the frontend loads and the page is actually live.

**Comment by MazeChaZer** [comment]
That works, thank you! The prerender feature is great, I will look more into how that actually works :)
