### ISSUE TITLE
The `exe` attribute seems to have subtle differences from `ghc.backend` and `ghc.frontend`

### ISSUE THREAD

**Issue by mightybyte** [obsidiansystems/obelisk#506]
I can do `nix-build -A exe` and the result will come completely from cache.  But then I follow that up with `nix-build -A ghc.backend` or `nix-build -A ghc.frontend` and the result is not cached.  Shouldn't the former have already built the latter?

**Comment by 3noch** [comment]
`ghc.backend` is not statically linked. `ghc.frontend` is not a GHCJS build. But... I also would like access to the thing that `exe` is *actually* using..

**Comment by 3noch** [comment]
`ghcjs.frontend` is not closure compiled, so even that won't get you the same derivation.

**Comment by 3noch** [comment]
@mightybyte Please try #507

**Comment by ali-abrar** [comment]
@mightybyte I'd recommend having a nix file that you build that lists all of the attributes you'd like to cache. 

For example, you could do something like:

```
{ }:
let
  myProject = import ./. {};
in {
  android = myProject.android.frontend; # Android application
  exe = myProject.exe;                  # Compiled backend and ghcjs frontend
  shell = myProject.shells.ghc;         # Project shell
}
```
and put that somewhere (perhaps `release.nix`). This gives you direct control over what's built and cached. 

To see what else can be added to this list, run `nix repl` in your project directory and try: `a = import ./. {}` then look at the value of `a` to see the components of your obelisk project.

**Comment by mankyKitty** [comment]
I've updated the FAQ to cover some of these points here and provide a brief explanation on cherry picking individual derivations to allow for more fine grained caching in the nix store.
