### ISSUE TITLE
GHCJS 8.6 runtime exceptions

### ISSUE THREAD

**Issue by tomsmalley** [obsidiansystems/obelisk#508]
```uncaught exception in Haskell thread: ReferenceError: h$baseZCGHCziBaseziJust_con_e is not defined```

Duplicating here for visibility. This happens in the skeleton (`nix-build -A exe`) with and without using the closure compiler.

The upstream issue is here: https://github.com/ghcjs/ghcjs/issues/760

**Comment by 3noch** [comment]
I guess it's a good thing we haven't officially released GHC 8.6 support to `master` yet...but this is a pretty bad state for `develop` to be in too.

**Comment by ali-abrar** [comment]
https://github.com/obsidiansystems/obelisk/pull/509

**Comment by tomsmalley** [comment]
Closing this since the PR was merged
