### ISSUE TITLE
`ob` commands should accept -vv not just -v

### ISSUE THREAD

**Issue by ORESoftware** [obsidiansystems/obelisk#516]
I ran:

```bash
ob deploy update -vv
```

but it doesn't like the -vv, this works though:

```bash
ob deploy update -v
```

since -vv is such a common thing, probably should support it even if it's just a no-op (-vv and -vvv might be equivalent to -v)

**Comment by ryantrinkle** [comment]
Sounds reasonable to me.

**Comment by 3noch** [comment]
But then people may think that `-vv` is *more* logging that just `-v` when it's actually not. Perhaps just erroring out and saying "Did you meant -v?" would be better.

**Comment by ryantrinkle** [comment]
I think that could be a warning, probably

**Comment by ORESoftware** [comment]
-vv -vvv -vvvv could be no-ops and just mean -v, until later on if you wanted to implement lower level logging etc

**Comment by 3noch** [comment]
A warning seems ok. I just don't want to be the guy who keeps adding more `v`s expecting it will help only to discover by accident that the logs are not actually getting any better.

**Comment by 3noch** [comment]
If we end up adding multiple layers of `-v` we'll go this route. Until then we'll let `-vv` signal that it's not meaningful.
