### ISSUE TITLE
ob route: more flexible `routeLink` primitive

### ISSUE THREAD

**Issue by ryantrinkle** [obsidiansystems/obelisk#523]
In this code: https://github.com/blargg/Character-Sheet/blob/07d752f24356257e9cab87c3d8ec2e9ef7669504/frontend/src/Frontend.hs#L70

It would be ideal if the click event actually came from the _div_, not from the link, so that the click target matches the hover styling.  However, I don't think there's a clean way to do that at the moment.  Can we generalize `routeLink` to provide a better way?

**Comment by danbornside** [comment]
does anything need to change, actually?  shouldn't this be:

    routeLink (...) $ divClass "..." $ text ....

the "whole point" of the `routeLink` is that it's "as good" as a proper `<a href"...">`.  relying on JS events coming out of it to get things done would mean that there's different ways in which things behave as links depending on how the user interacts with them.

citation: https://stackoverflow.com/questions/4465923/a-href-link-for-entire-div-in-html-css

**Comment by 3noch** [comment]
I think @danbornside is right about this. `routeLink` must be thought of as "equivalent to <a href> minus some details".
