### ISSUE TITLE
'ob init' fails when calling ls-remote

### ISSUE THREAD

**Issue by joprice** [obsidiansystems/obelisk#524]
`ob init` fails when calling `git ls-remote`:

```bash
20:17 $ ob init -v
Starting Obelisk </nix/store/5c3z21f9pasglb9kac83f146qxn7316d-obelisk-command-0.1/bin/.ob-wrapped> args=["init","-v"] logging-level=Debug
Creating process: 'git' 'ls-remote' '--exit-code' '--symref' 'https://github.com/obsidiansystems/obelisk.git' 'refs/heads/master'
git ls-remote maps: (fromList [],fromList [])
Did not find commit for refs/heads/master
Failure for git remote https://github.com/obsidiansystems/obelisk.git
✖ Setting up obelisk
```

But the command runs when I try it directly:

```bash
20:18 $ 'git' 'ls-remote' '--exit-code' '--symref' 'https://github.com/obsidiansystems/obelisk.git' 'refs/heads/master'
a98ad63b88846412f73a43367e496fa58f77c785	refs/heads/master
```

I don't know enough about nix to debug whether that same command fails from within the nix environment though.

I installed ob via `nix-env -f https://github.com/obsidiansystems/obelisk/archive/master.tar.gz -iA command` and tried on both master and develop.

**Comment by 3noch** [comment]
@joprice Can you provide any details about your operating system?

**Comment by joprice** [comment]
Unfortunately, I can't give you more info. I'm not sure what state my system was in at the time. But, I just tried a fresh install and it works! Maybe it was something misconfigured in my nix env.
