### ISSUE TITLE
GHC 8.6.5 support

### ISSUE THREAD

**Issue by DoctorRyner** [obsidiansystems/obelisk#530]
Can I use ghc 8.6.5? And why can't I add record-hasfield to cabal file? I don't know much about nix, sorry
<img width="1440" alt="Screenshot 2019-10-01 at 11 54 43 PM" src="https://user-images.githubusercontent.com/24430919/66000070-5b10a680-e4a7-11e9-827f-e85401df201b.png">

**Comment by ali-abrar** [comment]
reflex-platform uses ghc 8.6.5 as of #500 

Sometimes a particular package or version is too new to be in the pinned package set in reflex-platform. In such cases, you can manually add those packages/versions in default.nix by following the instructions [in the readme](https://github.com/obsidiansystems/obelisk/blob/develop/README.md#adding-package-overrides).

**Comment by ali-abrar** [comment]
Let me know if that fixes the issue for you.

**Comment by DoctorRyner** [comment]
1. Oh, so I can use 8.6.5 by installing it from a develop branch with?
```
nix-env -f https://github.com/obsidiansystems/obelisk/archive/master.tar.gz -iA command
```

2. Yes, thanks, I finally figured out how to add it with overrides

**Comment by ali-abrar** [comment]
To update obelisk inside of your project, you should run:

`ob thunk update .obelisk/impl --branch develop`

**Comment by DoctorRyner** [comment]
Thanks!
