### ISSUE TITLE
template error

### ISSUE THREAD

**Issue by DoctorRyner** [obsidiansystems/obelisk#533]
Template doesn't work with the latest version

<img width="708" alt="Screenshot 2019-10-07 at 10 09 24 PM" src="https://user-images.githubusercontent.com/24430919/66341055-25f4d000-e94f-11e9-89a3-863193c552af.png">

```
backend/src/Backend.hs:14:29-47: error:
    • Couldn't match type ‘Data.Functor.Sum.Sum
                             BackendRoute (Obelisk.Route.ObeliskRoute FrontendRoute)’
                     with ‘Obelisk.Route.FullRoute BackendRoute FrontendRoute’
      Expected type: Obelisk.Route.Encoder
                       (Either Data.Text.Internal.Text)
                       Data.Functor.Identity.Identity
                       (Obelisk.Route.R
                          (Obelisk.Route.FullRoute BackendRoute FrontendRoute))
                       Obelisk.Route.PageName
        Actual type: Obelisk.Route.Encoder
                       (Either Data.Text.Internal.Text)
                       Data.Functor.Identity.Identity
                       (Obelisk.Route.R
                          (Data.Functor.Sum.Sum
                             BackendRoute (Obelisk.Route.ObeliskRoute FrontendRoute)))
                       Obelisk.Route.PageName
```

**Comment by alexfmpe** [comment]
By any chance was this template generated by a months-old obelisk? 
When `FullRoute` was added, the skeleton was also updated to use it: https://github.com/obsidiansystems/obelisk/commit/b6da186353c525aaf674e16933b48311dca5a1d3#diff-74f0557b71855f6d339b789317ca8ad6R14

**Comment by DoctorRyner** [comment]
Hm, I did reinstall ob beforehand, I will try it again

**Comment by 3noch** [comment]
Yeah if you run `ob init` and then later `ob thunk update .obelisk/impl` then your template can be out-of-sync with the version of obelisk you just upgraded to.

**Comment by DoctorRyner** [comment]
Ok, it does work but `nix-shell -A shells.ghc` gives me
```
error: attribute 'shells' in selection path 'shells' not found
```

**Comment by DoctorRyner** [comment]
Thanks, it works fine
