### ISSUE TITLE
'callHackageDirect' not defined in Adding Packages example

### ISSUE THREAD

**Issue by patrickmn** [obsidiansystems/obelisk#549]
error: attribute 'callHackageDirect' missing, at /home/patrick/ob/default.nix:21:18
(use '--show-trace' to show detailed location information)

**Comment by 3noch** [comment]
Can you show what command you ran to get this error?

**Comment by 3noch** [comment]
Are you using `master` branch of obelisk? Try `ob thunk .obelisk/impl --branch develop` to use develop instead and see if this happens.

**Comment by patrickmn** [comment]
Thanks for the quick response!

`ob run` after following the instructions in the readme, i.e. master: `nix-env -f https://github.com/obsidiansystems/obelisk/archive/master.tar.gz -iA command`

```
# ob run -v
Starting Obelisk </nix/store/ryihixldr6wb22ypp8hxvscivagvb9b1-obelisk-command-0.1/bin/.ob-wrapped> args=["run","-v"] logging-level=Debug
Handing off to ./.obelisk/impl/.attr-cache/command.out/bin/ob
Starting Obelisk </nix/store/ryihixldr6wb22ypp8hxvscivagvb9b1-obelisk-command-0.1/bin/.ob-wrapped> args=["--no-handoff","run","-v"] logging-level=Debug
Creating process runNixShellAttr: 'nix-shell' '-A' 'shells.ghc' '--run' '/nix/store/ryihixldr6wb22ypp8hxvscivagvb9b1-obelisk-command-0.1/bin/.ob-wrapped --no-handoff --verbose internal run-static-io 01489bf44eb91e7f793dea3f236c5989'
error: attribute 'callHackageDirect' missing, at /home/patrick/ob/default.nix:43:18
(use '--show-trace' to show detailed location information)
```

After doing the thunk update everything seems to be working as expected.

**Comment by 3noch** [comment]
This isn't the first time that the mismatch between obelisk's default of using `master` and the GitHub configuration's default showing `develop` has caused confusion. Perhaps we should consider changing that.
