### ISSUE TITLE
Use fetchFromGitLab

### ISSUE THREAD

**Issue by Ericson2314** [obsidiansystems/obelisk#550]
Just like fetchFromGitHub, but for GitLab.

**Comment by matthewbauer** [comment]
Why can't we just use the normal fetchGit handling?

**Comment by 3noch** [comment]
`builtins.fetchGit` has some serious issues (perhaps they've been addressed in more recent nix version?) so we avoid it. I imagine `fetchFromGitLab` has some features that help with private repos?

**Comment by puffnfresh** [comment]
fetchFromGitLab doesn't support submodules, something to watch out for.

**Comment by 3noch** [comment]
So the advantage would be for private repos only?

**Comment by 3noch** [comment]
This doesn't seem to have any advantage. In fact, I'd prefer to get rid of special handling for GitHub.
