### ISSUE TITLE
ob run fails on latest develop

### ISSUE THREAD

**Issue by kmicklas** [obsidiansystems/obelisk#562]
After updating to revision 0722c55fcc1d31e43fefd1f3d8b826f341c031a5:

```
> ob run 
.ob-wrapped: nix: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

However other commands such as `ob repl` and `ob watch` work.

**Comment by ali-abrar** [comment]
Should be fixed by #561
