### ISSUE TITLE
Error messages sometimes get eaten

### ISSUE THREAD

**Issue by lpsmith** [obsidiansystems/obelisk#563]
I stumbled across a sharp edge recently,  that I'd set a soft `ulimit` on my machine that restricts the amount of memory that a single process can map,  and then the error message that reminded me about the `ulimit` never gets displayed.   A demo:

```
$ mkdir demo-error
$ ob init
$ ulimit -S -v 12000000
$ ob run
```

At this point there's a couple of error messages one could possibly get,  more commonly:

```
.ob-wrapped: callCommand: ghcid -W --command='ghci -Wall -ignore-dot-ghci -fwarn-redundant-constraints -no-user-package-db -ghci-script /run/user/1000/ob-ghci-69b85b0cc79a5ee5/.ghci'  --reload=config --outputfile=ghcid-output.txt --test='Obelisk.Run.run 45165 (runServeAsset "/home/lpsmith/ob/four-function-calculator/static") Backend.backend Frontend.frontend' (exit 1): failed
```

Less commonly,  a call to `dlopen` will fail:  (which particular shared object it fails on is nondeterministic)

```
can't load .so/.DLL for: /nix/store/q6sdxxb5xj2j5av7wsf7zhkjri23gr0l-memory-0.14.18/lib/ghc-8.6.5/x86_64-linux-ghc-8.6.5/libHSmemory-0.14.18-9cZN4KO0sHc84TFjg4stB9-ghc8.6.5.so (/nix/store/q6sdxxb5xj2j5av7wsf7zhkjri23gr0l-memory-0.14.18/lib/ghc-8.6.5/x86_64-linux-ghc-8.6.5/libHSmemory-0.14.18-9cZN4KO0sHc84TFjg4stB9-ghc8.6.5.so: failed to map segment from shared object)
```

The error message that finally oriented me in the right direction, I found via `strace -f -s 1024`:   (though arguably,  I should have been reminded of the `ulimit` after discovering the previous message,  because it does mention `mmap` failing, but the dynamic linking sent me in the wrong direction at first.)

```
2569  <... read resumed> "ghc: failed to create OS thread: Cannot allocate memory\n", 8192) = 56
```
For whatever reason(s),  this error message was never displayed,  instead you seem to always get one of the previous two types of messages.

**Comment by matthewbauer** [comment]
It looks like the exact number that hits this could be variable, depending on your obelisk version & hardware. For me `ulimit -S -v 12000000` works fine, but `ulimit -S -v 1200000` immediately fails with "Cannot allocated memory". `ulimit -S -v 10000000` reproduces the same error you are describing.

**Comment by matthewbauer** [comment]
It looks like ghcid is just throwing this away right now:

https://github.com/ndmitchell/ghcid/blob/25faf559b6f5e8fdef8e1ca2aaf557644a57a165/src/Ghcid.hs#L187

We probably should use ghcid as a library to fix this.

**Comment by matthewbauer** [comment]
Actually using ghcid as a library is really difficult because we have to reimplement a ton of the terminal buffering logic it does because that isn't exposed in the library. Easier to just patch ghcid to show the error as well.

**Comment by ryantrinkle** [comment]
We could also patch ghcid to expose the terminal buffering logic.  Either way, let's plan to upstream any patching we do.

**Comment by matthewbauer** [comment]
> We could also patch ghcid to expose the terminal buffering logic. Either way, let's plan to upstream any patching we do.

Yeah sounds good. To be more clear, the issue is that lots of the feature we need are not exposed in the library. `runGhcid` is what we want: https://github.com/ndmitchell/ghcid/blob/master/src/Ghcid.hs#L253-L386

Anyway, I've discovered that it's a bit more complicated than I originally expected. The details are not in the UnexpectedExit error above as I thought originally. They are viewable however if you enable `-v`:

```
%OS: linux
%ARCH: x86_64
%VERSION: 0.7.7
Loading ghci -Wall -ignore-dot-ghci -fwarn-redundant-constraints -no-user-package-db -ghci-script /run/user/1000/ob-ghci-cfccd5f35879f18a/.ghci ...
%STDOUT: GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
%STDOUT2: GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
%STDIN: import qualified System.IO as INTERNAL_GHCID
%STDIN: :unset +t +s
%STDIN: :set prompt #~GHCID-START~#
%STDIN: :set -fno-break-on-exception
%STDIN: :set -fno-break-on-error
%STDIN: :set -v1
%STDIN: :set -fno-hide-source-paths
%STDIN: INTERNAL_GHCID.putStrLn ['#','~','G','H','C','I','D','-','F','I','N','I','S','H','-','1','~','#']
INTERNAL_GHCID.hPutStrLn INTERNAL_GHCID.stderr ['#','~','G','H','C','I','D','-','F','I','N','I','S','H','-','1','~','#']
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
%STDOUT: Prelude> Prelude> Prelude INTERNAL_GHCID> Prelude INTERNAL_GHCID> #~GHCID-START~##~GHCID-START~##~GHCID-START~##~GHCID-START~##~GHCID-START~##~GHCID-FINISH-1~#
%STDERR: #~GHCID-FINISH-1~#
%STDIN: :show modules
%STDIN: INTERNAL_GHCID.putStrLn ['#','~','G','H','C','I','D','-','F','I','N','I','S','H','-','2','~','#']
INTERNAL_GHCID.hPutStrLn INTERNAL_GHCID.stderr ['#','~','G','H','C','I','D','-','F','I','N','I','S','H','-','2','~','#']
%STDOUT: #~GHCID-START~##~GHCID-START~##~GHCID-START~##~GHCID-FINISH-2~#
%STDERR: #~GHCID-FINISH-2~#
%STDIN: 
%STDIN: INTERNAL_GHCID.putStrLn ['#','~','G','H','C','I','D','-','F','I','N','I','S','H','-','3','~','#']
INTERNAL_GHCID.hPutStrLn INTERNAL_GHCID.stderr ['#','~','G','H','C','I','D','-','F','I','N','I','S','H','-','3','~','#']
%STDOUT: #~GHCID-START~##~GHCID-START~##~GHCID-START~##~GHCID-FINISH-3~#
%STDERR: #~GHCID-FINISH-3~#
%STDIN: :set -ferror-spans
:set -j
:set -fdiagnostics-color=always

%STDIN: INTERNAL_GHCID.putStrLn ['#','~','G','H','C','I','D','-','F','I','N','I','S','H','-','4','~','#']
INTERNAL_GHCID.hPutStrLn INTERNAL_GHCID.stderr ['#','~','G','H','C','I','D','-','F','I','N','I','S','H','-','4','~','#']
%STDERR: ghc: failed to create OS thread: Cannot allocate memory
%STDERR: ghc: failed to create OS thread: Cannot allocate memory
%STDOUT: #~GHCID-START~##~GHCID-START~##~GHCID-START~##~GHCID-START~##~GHCID-START~##~GHCID-START~#
%STDIN: :quit
Command "ghci -Wall -ignore-dot-ghci -fwarn-redundant-constraints -no-user-package-db -ghci-script /run/user/1000/ob-ghci-cfccd5f35879f18a/.ghci" exited unexpectedly
```

So it looks like we just need to record the "%STDERR" error part.

**Comment by matthewbauer** [comment]
Done in https://github.com/ndmitchell/ghcid/pull/288, try it out in obelisk with https://github.com/obsidiansystems/obelisk/pull/566.
