### ISSUE TITLE
Add `ob deploy prepare`

### ISSUE THREAD

**Issue by 3noch** [obsidiansystems/obelisk#59]
This should be a subset of `ob deploy push` that only runs the `nix-build` of the final derivation. It should also keep the VM builder integration so that it can build the correct binaries when run on non-Linux host.

**Comment by alexfmpe** [comment]
Yeah this would also be a part of `ob deploy` that can be tested without providing an upstream repo or a AWS instance.

**Comment by 3noch** [comment]
While this predates it, we'll mark this as duplicate of another ticket that got more attention: https://github.com/obsidiansystems/obelisk/issues/368
