### ISSUE TITLE
Selftest incoherent about handling skeleton

### ISSUE THREAD

**Issue by alexfmpe** [obsidiansystems/obelisk#590]
```shell
$ rm -rf skeleton
$ nix-build -A selftest
$ ./result

ob init
  works with symlink FAILED -- expected failure
obelisk project
  can build obelisk skeleton FAILED -- expected failure

blank initialized project
  can build ghc.backend -- should have failed
  can build ghcjs.frontend -- should have failed
  can build android after accepting license -- should have failed
```

If I mess up the skeleton, `ob init` won't see it since it uses an upstream skeleton, while `--symlink` via the environment variable `OBELISK_IMPL` now fails. The other expected failure also lookups the environment variable

**Comment by 3noch** [comment]
This will be fixed when https://github.com/obsidiansystems/obelisk/pull/594 is merged.

**Comment by alexfmpe** [comment]
#594 has made its way to develop now, and removing skeleton has no effect on the selftest. 
Shouldn't it?

**Comment by 3noch** [comment]
What do you mean by "removing skeleton"?

**Comment by alexfmpe** [comment]
`$ rm -rf skeleton` from the original comment

**Comment by 3noch** [comment]
Oh of course. I'll try that.
