### ISSUE TITLE
Does ob install everything for each ob project?

### ISSUE THREAD

**Issue by DaweiLiuFrance** [obsidiansystems/obelisk#596]
I'm learning the obelisk eco system.
In my `./ob` directory, I have two folders.

One is cloned from the official sample project.

Another one is the calculator example.

I run `ob run` in each project and it seems that they each install a huge number of dependencies which are redundant, including the ghc!

Is this normal?

**Comment by 3noch** [comment]
Is obelisk *building* GHC or just downloading it? Can you tell? Obelisk uses Nix for all package management, so it won't reuse any libraries/tools you've installed through some other package system or stack or manually, etc.

**Comment by 3noch** [comment]
Also, be sure you're using the Nix caches as described in https://github.com/obsidiansystems/obelisk#installing-obelisk

You shouldn't be *building* anything other than the last few dependencies in the tree as most things are cached.

However, if you are building two different projects, they may depend on different versions of GHC so you would, theoretically, be building GHC twice, once for each version. But practically you should always be getting those from the cache.

Let me know if this isn't clear and I'll repoen!
