### ISSUE TITLE
First build text dependency error

### ISSUE THREAD

**Issue by johnny555** [obsidiansystems/obelisk#66]
Hi,

After running a fresh `ob init` then `ob run` I get the following error message:

```
frontend/src/Frontend.hs:18:23: error:
    • Couldn't match expected type ‘text-1.2.2.2:Data.Text.Internal.Text’
                  with actual type ‘T.Text’
      NB: ‘T.Text’
            is defined in ‘Data.Text.Internal’ in package ‘text-1.2.3.0’
          ‘text-1.2.2.2:Data.Text.Internal.Text’
            is defined in ‘Data.Text.Internal’ in package ‘text-1.2.2.2’
    • In the second argument of ‘($)’, namely ‘T.pack commonStuff’
      In the second argument of ‘($)’, namely ‘text $ T.pack commonStuff’
      In a stmt of a 'do' block: el "p" $ text $ T.pack commonStuff
```
looks like a library incompatibility, I tried looking through the `frontend.cabal` and `backend.cabal` files and trying to force all the text libraries to be 1.2.2.2 but it didn't seem to work. 

John

**Comment by tomsmalley** [comment]
Hi, this looks the same as #3. Could you see if following Ryan's comment fixes it?

**Comment by johnny555** [comment]
Hi, 

Yes that fixed it. Sorry I didn't see #3 when I was looking for issues. 

Cheers,

John
