### ISSUE TITLE
Avoid Prerender constraint in routeLink

### ISSUE THREAD

**Issue by mightybyte** [obsidiansystems/obelisk#667]
It looks like `routeLink` was modified a bit ago to make it scroll to the top of the page.  That's all well and good, but the change added a `Prerender` constraint to the type signature.  This is fine too except that the old version without the `Prerender` constraint is no longer exported.  Since this impacts how users can call the function it seems like it would be worth exporting the version without the `Prerender` constraint.

**Comment by alexfmpe** [comment]
That's what I was going for with https://github.com/obsidiansystems/obelisk/pull/542/files#diff-e2f971c233ea88bb63084b678166dc62R548

**Comment by mightybyte** [comment]
Oh nice, looks like that would do the trick.

**Comment by 3noch** [comment]
We could rename the `Impl` to `routeLinkNoScrollToTop` and export it. I'm curious what the use case is?

**Comment by mightybyte** [comment]
It's mainly that adding `Prerender` constraints to existing uses of `routeLink` is pretty onerous and also impacts the ability of widgets to be rendered server-side.

**Comment by 3noch** [comment]
> impacts the ability of widgets to be rendered server-side

Do mean, "reuse widgets that are meant to be rendered *only* on the server" with a static renderer or something? If not I'm a bit confused. `Prerender` means that the widget *can* be rendered on the server.

**Comment by 3noch** [comment]
Actually even static builder has an instance for `Prerender` so I'm not sure what environment you could conjure up that *wouldn't* support this.

**Comment by mightybyte** [comment]
Hmmm, maybe I just don't fully understand `Prerender`.  In any case, being forced to change the type signatures all the way up your hierarchy is pretty painful and in this case completely unnecessary.

**Comment by 3noch** [comment]
Why is it unnecessary? Without the Prerender constraint we can't ensure your link will behave the same before and after hydration.

**Comment by mightybyte** [comment]
Because before this change it was unnecessary.  Adding the scroll to top behavior adds the `Prerender` constraint.  Therefore I can use `routeLink` in strictly fewer places than before the scroll to top behavior was added and `routeLink` had no `Prerender` constraint.  This is a pretty basic API stability concern.  Don't change type signatures unnecessarily.

**Comment by 3noch** [comment]
While the new `Prerender` constraint actually was *necessary* to get consistent behavior in both prerendered and post-hydration contexts, we figured out a way to actually maintain consistent behavior without imposing a `Prerender` constraint by adding the "scroll-to-top" feature to `SetRoute` instead. We will use this ticket as a request for that change.

**Comment by mightybyte** [comment]
What was the inconsistency?

**Comment by 3noch** [comment]
The `Prerender` constraint is necessary because we added a new `performEvent` whenever a link is clicked that *also* scrolls you to the top of the page. This "scroll-to-top" is the only way to make JS-based links behave the same as `<a href>` which is the entire point of `routeLink`. However, centralizing that `performEvent` to the place that also sets `window.location` (via `SetRoute`) is probably a better design anyway and avoids `Prerender` at each use site.

**Comment by mightybyte** [comment]
Ahh, ok.  I guess I just never noticed the old behavior.  At any rate, I think we've discussed it enough for you all to make an appropriate decision.  If a `Prerender` constraint is required to avoid that unexpected behavior, that makes sense to me.  I'll leave this open for now in case you want it but feel free to close.
