### ISSUE TITLE
The `static` directory cannot be a symlink

### ISSUE THREAD

**Issue by dalaing** [obsidiansystems/obelisk#67]
I don't know if `static` _should_ be allowed to be a symlink, but I know I'd find it really handy if it could be.

At the moment I'm trying to use a symlink to a nix derivation as the `static` directory, so that I can do various odd things to prepare my static assets.

If this is out of scope for Obelisk I completely understand, but I figured I'd note it here.  If you're open to it, great.  If you're not open to it, it'll save someone else from asking or filing an issue about it.

**Comment by ryantrinkle** [comment]
Would it make sense, instead, to have a way that you can configure obelisk so that your static files are represented by a nix *expression*?  That way, it could be automatically rebuilt for you whenever it changes.  We could just set the default expression to be `./static`.

**Comment by dalaing** [comment]
That sounds great to me :)

**Comment by ali-abrar** [comment]
Fixed via #71
