### ISSUE TITLE
Would it be possible to add a build product to provide a local hoogle server?

### ISSUE THREAD

**Issue by dalaing** [obsidiansystems/obelisk#68]
At the moment hoogle database generation is disabled, which makes a lot of sense.

It would be nice to be able to get to a nix-shell with the local hoogle database generated for Obelisk, my overrides, and all of their dependencies, along with the hoogle executable so I can run the local server.

This is a minor thing, but it can be pretty nice if hoogle is part of your workflow.

**Comment by ryantrinkle** [comment]
That would be great! Also: ob run should run it.

**Comment by cah6** [comment]
+1 for this! Btw is there a way to manually edit the nix file or `nix-shell -A shells.ghc` command to get some sort of temporary solution for a local hoogle db until this is provided by the framework?

**Comment by dfordivam** [comment]
Adding `withHoogle = true;` to `default.nix` and doing `nix-shell -A shells.ghc` creates the shell with hoogle.

**Comment by cah6** [comment]
Thanks! That sort of worked...after entering the shell I could access Hoogle with `hoogle server --port=8080 --local --haskell` and get MOST packages, but not all. For instance, reflex-0.5 was there, but notably missing was reflex-dom (which was the package I was most wanting to be able to use). Do you have any idea why that wasn't included / how I could do so?

**Comment by dfordivam** [comment]
@cah6 it is a recent unrelated issue https://github.com/reflex-frp/reflex-platform/issues/419

**Comment by cah6** [comment]
Oh interesting. Thanks for the quick update. Btw it might be good to add to the docs that you can add that line to enable Hoogle? I knew about this prop from reflex-platform but didn't know that it would get passed through. I don't think that's immediately obvious without following the nix derivations through manually.

I'm assuming that all props in https://github.com/reflex-frp/reflex-platform/blob/92f235e0533b9722be729d785a033faf21e81872/project/default.nix are valid? It could be good to even link to that in the notes and indicate that you can put those in obelisk `default.nix` too.

**Comment by ali-abrar** [comment]
Added to readme.

**Comment by maralorn** [comment]
I am having a bit of a problem with wrapping my head around this. If I follow the advise in the Readme it plainly does not work:

    nix-shell -A shells.ghc --arg withHoogle true
    [nix-shell:~/git/my-project]$ hoogle
    hoogle: command not found

**Comment by alexfmpe** [comment]
Also happening for me on latest master.
Relatedly: maybe we should add an `ob hoogle` or `ob run hoogle` command that launches the hoogle server within the mentioned (seemingly broken) nix shell?

> That would be great! Also: ob run should run it.

Oh, or this earlier suggestion

**Comment by srid** [comment]
`ob run --with[out]-hoogle`?
