### ISSUE TITLE
Can this be used to build a single page application (SPA)?

### ISSUE THREAD

**Issue by malte-v** [obsidiansystems/obelisk#683]

**Comment by cgibbard** [comment]
Yes. For one, you could have just a single frontend route, and then depending on your needs, some backend routes, maybe one to serve a websocket, and some for XHRs.

Moreover, once your Obelisk application is loaded, if you use routeLink and related widgets to change between frontend routes, even though the browser history and URL bar will be adjusted, the application won't reload, and instead the frontend will simply adjust its current state -- so in some sense, Obelisk is specifically geared toward producing single-page applications (along with their mobile counterparts). If any of the frontend routes are loaded, the same application is served, and the state that is reflected in the URL is automatically restored accordingly.

**Comment by malte-v** [comment]
Great, thanks!
