### ISSUE TITLE
[Nix] Packaging of local dependencies

### ISSUE THREAD

**Issue by fabianhjr** [obsidiansystems/obelisk#684]
I am starting an obelisk project for a webstore and erp, however since there will be two obelisk sites I am opting for creating a local package which would be a common dependency.

```
local-library (schema, library-functions, etc)
public-site [obelisk] (no admin routes)
- backend
- common
- frontend
private-site [obelisk] (no public routes)
- backend
- common
- frontend
```

However, when adding such a dependency to the cabal.project files

```
packages =
  backend
  common
  frontend
 ../local-library
```

`ob run` et al. fail with a nix error:

```
 ~/D/L/LaTiendita   package-doubt  latiendita-web  ob run                                                   17s  Thu 26 Mar 2020 12:36:19 PM CST
error: anonymous function at /nix/store/fw7m0a5y7ywzr227bkc9aw32bgrmksr7-cabal2nix-backend/default.nix:1:1 called without required argument 'local-library', at /nix/store/ws6z2fm6q4wpw89rygxvrh08g104ixzw-source/pkgs/development/haskell-modules/make-package-set.nix:87:27
(use '--show-trace' to show detailed location information)
```

With verbose, it seems like `argstr` should take into consideration extra dependencies and currently doesn't:

```'--argstr' 'pkgs' '{"backend":"/home/fabian/Development/LibreCybernetics/LaTiendita/latiendita-web/backend","common":"/home/fabian/Development/LibreCybernetics/LaTiendita/latiendita-web/common","frontend":"/home/fabian/Development/LibreCybernetics/LaTiendita/latiendita-web/frontend"}```

As a workaround, I moved local-library into one of the sites to start learning some obelisk. It seems like a packaging issue of local libraries however I am not familiar enough with neither nix nor obelisk to further debug the issue or open a Merge Request. (Though I will be reading the obelisk code to see if I can find something)

Real World Example:

Attempted structure: https://gitlab.com/LibreCybernetics/LaTiendita/-/tree/639299c70d08901d1afddbae1a0f6cb6023915b7
Current workaround: https://gitlab.com/LibreCybernetics/LaTiendita/-/tree/1fac2a5d80f1be429d66d73b5903149c3b0f7383

I see in #108 that there is a way to override the hackage/nix dependencies in case of incompatibility and that instructions for fetching from hackage were added to the readme ( https://github.com/obsidiansystems/obelisk/blob/develop/README.md#adding-package-overrides ) however it would be a bit annoying to be pinning the version/hash of the common library assuming it would be changing as often as the obelisk code (And as such would be desirable for the time being to host on a single git repo).

```
  overrides = self: super: {
    time-recurrence = pkgs.haskell.lib.doJailbreak super.time-recurrence;
  };
```

However I am still unfamiliar with using nix to bring in local extra dependencies. :C

**Comment by 3noch** [comment]
Thanks for the detailed report! There is a bug with `ob run` where it won't find local packages that are in a parent directory. As a workaround make a symlink in each of your sub-obelisk-projects to the library. This way `ob run` will find them. Let me know how that goes. We are trying to make `ob run` handle this case properly by reading the paths directly from your nix instead.

**Comment by fabianhjr** [comment]
Oh, the symlink was one of the things I tried and nix won't package it either. :C

**Comment by 3noch** [comment]
Can you paste your `default.nix` for one of the obelisk projects that's not working? I suspect you need to add this library to the nix set of packages too.

**Comment by fabianhjr** [comment]
```
{ obelisk ? import ./.obelisk/impl {
    system = builtins.currentSystem;
  }
}:
with obelisk;
project ./. ({ ... }: {})
```

**Comment by 3noch** [comment]
Try something like this:

```nix
{ obelisk ? import ./.obelisk/impl {
    system = builtins.currentSystem;
  }
}:
with obelisk;
project ./. ({ ... }: {
  packages = {
    my-package = ../my-package;
  };
})
```

**Comment by fabianhjr** [comment]
Oh that fixed it, thanks for the support @3noch. ^_^

**Comment by 3noch** [comment]
Clearly this needs to be documented better! Thanks for the feedback!

**Comment by 3noch** [comment]
Note that the comment I made about symlinks *still applies* if you want `ob run` to load your package for live feedback. Without the symlink I believe it will try to build your common package once with nix and any changes will require you to restart `ob run`.
