### ISSUE TITLE
Document how to add dependencies to project

### ISSUE THREAD

**Issue by 3noch** [obsidiansystems/obelisk#685]
#684 exposed that we need to document this better. I think putting a commented-out example in the skeleton default.nix might work well.

**Comment by fabianhjr** [comment]
Hey, may I work on this or have you started already? Will have some time over the weekend

**Comment by 3noch** [comment]
Your contribution would be most welcome! No one has started on this.

**Comment by ali-abrar** [comment]
Covered here https://github.com/obsidiansystems/obelisk#adding-package-overrides
