### ISSUE TITLE
ob run/watch/repl cannot load dependency which contains Cabal internal library

### ISSUE THREAD

**Issue by kmicklas** [obsidiansystems/obelisk#701]
Upstream bug: https://gitlab.haskell.org/ghc/ghc/issues/16228

Importing a module from a library whose package has an internal library (e.g. `typerep-map`) does not work in the Obelisk GHCI session:

```
    Could not load module ‘Data.TypeRepMap’
    It is a member of the hidden package ‘typerep-map-0.3.2’.
    You can run ‘:set -package typerep-map’ to expose it.
    (Note: this unloads all the modules in the current scope.)
    Use -v to see a list of the files searched for.
   |
25 | import Data.TypeRepMap
   | ^^^^^^^^^^^^^^^^^^^^^^
```

There is no problem with `cabal new-build` in the shell or `nix-build`ing the package.

Until we are on a new enough GHC to have the fix, this could be worked around the same way that makes it work in Cabal: passing `-package` flags to `ghci` for all the dependencies of the loaded packages. Since the Cabal files are already parsed to get extensions, options, etc., this shouldn't be too hard to add.

Feel free to push back since this is relatively obscure (?) and will be fixed automatically at some point in the future.

**Comment by 3noch** [comment]
Thanks for the detailed report. 

> Feel free to push back since this is relatively obscure (?) and will be fixed automatically at some point in the future.

We certainly won't push back any PRs that might be submitted :wink:. But you're right that this does seem pretty easy so long as the cabal parser exposes these internal libraries in a straightforward way.

**Comment by kmicklas** [comment]
@3noch It's actually easier than that; we just need to get all the dependencies from `frontend`, `backend`, and `common` (and whatever other shell packages) and pass corresponding `-package` flags. We don't need to parse those packages themselves to look for internal libraries.

**Comment by ohri-anurag** [comment]
@kmicklas The [upstream bug](https://gitlab.haskell.org/ghc/ghc/-/issues/16228) has been fixed, is this still an issue?

**Comment by ohri-anurag** [comment]
Tested with Obelisk commit e3ec75f6988eed47189dd20f8c8514748b33ea81 in a new Obelisk project:

**typerep-map v0.4.0.0** - overridden using default.nix
All three commands, ob run/watch/repl succeeded.

**Using commit [4527db61961faad0f890d04b42109bb194c8ccc8](https://github.com/kowainik/typerep-map/commit/4527db61961faad0f890d04b42109bb194c8ccc8) for nix-thunk** - again overridden using default.nix
All three commands, ob run/watch/repl succeeded.
