### ISSUE TITLE
`ob run` does not reload

### ISSUE THREAD

**Issue by srid** [obsidiansystems/obelisk#707]
I changed `Frontend.hs`, but `ob run` doesn't reload it. Even killing and starting it again uses the old frontend somehow. I did saw this warning:

![image](https://user-images.githubusercontent.com/3998/79710372-cd55a680-8292-11ea-86d2-c77732a8a078.png)

```
Packages named 'backend' appear in 2 different locations: .attr-cache/skeleton.out/backend/backend.cabal, backend/backend.cabal; Picking .attr-cache/skeleton.out/backend/backend.cabal
Packages named 'common' appear in 2 different locations: common/common.cabal, .attr-cache/skeleton.out/common/common.cabal; Picking common/common.cabal
Packages named 'frontend' appear in 2 different locations: .attr-cache/skeleton.out/frontend/frontend.cabal, frontend/frontend.cabal; Picking .attr-cache/skeleton.out/frontend/frontend.cabal
```
This was from using develop branch of obelisk at 6df4924 - and a newly created skeleton using it.

**Comment by srid** [comment]
Workaround: `rm -rf ./.attr-cache`.

**Comment by tomsmalley** [comment]
Hey Srid, is your project `.obelisk/impl` also pointing at that commit? I guess you are at some point behind https://github.com/obsidiansystems/obelisk/pull/693 being included. Bear in mind that `ob init` will point to `master` by default.

Perhaps that fix needs backporting? cc @3noch 
I thought this bug was only on develop.

**Comment by 3noch** [comment]
This has been fixed in `develop`. It's possible it was present in older versions though. Thankfully the warning tells you what's going on. Closing since it's fixed in develop. We have a release in the pipeline.
