### ISSUE TITLE
`ob run` yields `obeliskApp: jsaddle got a bad URL`

### ISSUE THREAD

**Issue by darcykimball** [obsidiansystems/obelisk#729]
From a fresh project via `ob init`, I added this to `frontend/src/Frontend.hs`, in the `do` block for `_frontend_body`:

```haskell
      el "div" $ do
        eClick <- button "Click Me"
        dCount <- count eClick
        display dCount
```
Running `ob run` and trying it out on chromium 73.0.3683.75, I can see the example page with the button added, but every time I click it, this request is made:

```
Request URL: http://0.0.0.0:9999/jsaddle/sync/-3190456517527409488
Request Method: OPTIONS
Status Code: 500 Internal Server Error
Remote Address: 0.0.0.0:9999
Referrer Policy: no-referrer-when-downgrade
```

...which gets the response `obeliskApp: jsaddle got a bad URL`. Am I missing something obvious? Also, I'm not very familiar with javascript and the like, so sorry if it was something obvious there, or if the problem is not with obelisk.

**Comment by tomsmalley** [comment]
It looks like you're visiting `0.0.0.0:9999`: did you change the route config `config/common/route`?

The default route is `http://localhost:8000`, which gives me that same error if I visit `0.0.0.0:8000` in the browser instead of `localhost:8000`.

**Comment by darcykimball** [comment]
Yes; the contents of my `config/common/route` are
```
http://0.0.0.0:9999
```

**Comment by darcykimball** [comment]
Er, FWIW: in the browser address bar, I do use `http://localhost:9999`, since `ob run` is being run in a VM where the host port is forwarded to guest's `9999`; I put `0.0.0.0` in `route` because I wanted the server to bind to all addresses (out of laziness).

**Comment by tomsmalley** [comment]
We currently have no provision for dealing with these CORS errors, I think you have to visit the same URL as is in the config.

**Comment by darcykimball** [comment]
Alright, thanks. Should I close this?

P.S. As an extra sanity check, I built a local server and served via `backend -p 9999`, and it worked fine.

**Comment by 3noch** [comment]
We should make this a bit easier to use.

**Comment by madeline-os** [comment]
Thank you for the excellent bug report. I will ensure that this CORS consideration is mentioned in the FAQ.
