### ISSUE TITLE
Recommended way to build additional developer tools?

### ISSUE THREAD

**Issue by cah6** [obsidiansystems/obelisk#74]
First of all, would like to say that Obelisk is working really well (on NixOS) for what you guys advertise: setting up a project, continuously building, and deploying it without hassle. 

My main question here is my next biggest painpoint: how do you set up tools required for an IDE like Atom, ex ghc-mod, hindent, hlint, whatever. I'm used to stack-based projects where you can do something like:
```
stack build
stack build intero
stack build ghc-mod
... etc
```
and have all the tools ready on a per-project basis.

From following along with something like https://github.com/Gabriel439/haskell-nix/blob/master/project0/README.md I more or less understand how to: generate nix files from cabal, make a nix file that uses these, and use that to get into a nix-shell that contains all this -- but I'm not sure how to integrate this type of workflow into an obelisk project, considering your library does a lot of the nix stuff behind the scenes (i.e. when you `ob init` a project, the only nix file is a barebones `default.nix`). 

Do you have any examples of how to customize the nix environment / build for an obelisk project? Or how do you guys handle building tooling needed for a project (preferably on a per-project basis using something like `nix-shell`)? Or do you just skip checking all this in an IDE and use ghcid to catch compile errors?

**Comment by srid** [comment]
@cah6 A couple of things that might help here:

1. Most often I find myself wanting to add or customize a Haskell package. Obelisk's Nix infrastructure abstracts this part using `overrides`, which is not yet officially documented, but you can find [an example here](https://github.com/obsidiansystems/obelisk/pull/62/files).

2. In regards to IDE support, you might find that `ghcid` alone is useful. `ob run` uses ghcid under the hood, and writes any compiler errors/ warnings to a file called `ghcid-output.txt` in addition to displaying them on the console. There is [an extension for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=ndmitchell.haskell-ghcid) that uses this file to automatically highlight errors and warnings on the fly.

**Comment by cah6** [comment]
Ah, thank you! Yeah this question was pretty generic, just wanted to get a feel for what others use to get feedback while coding (feel free to close this so you don't have a vague open ticket). I'll try those out though!

**Comment by ElvishJerricco** [comment]
@srid I think that might be something a little different. Seems like @cah6 is asking for a way to get tools installed. The proper way is with the `tools` option from reflex-platform's `project`, but I don't know if that's available in obelisk.

**Comment by ryantrinkle** [comment]
`obelisk` has a rather tin shell around `reflex-platform`'s `project`, so
if it's not supported right now, it should be quite easy to add (in
obelisk/default.nix)

**Comment by ali-abrar** [comment]
Fixed via https://github.com/obsidiansystems/obelisk/commit/631917494c79733bd2d5f6be56fdba2928ed90b4. 

For example:
```
{ system ? builtins.currentSystem # TODO: Get rid of this system cruft
, iosSdkVersion ? "10.2"
}:
with import ./.obelisk/impl { inherit system iosSdkVersion; };
project ./. ({ ... }: {
  android.applicationId = "systems.obsidian.obelisk.examples.minimal";
  android.displayName = "Obelisk Minimal Example";
  ios.bundleIdentifier = "systems.obsidian.obelisk.examples.minimal";
  ios.bundleName = "Obelisk Minimal Example";
  tools = ghc: with ghc; [ hpack ];
})
```

Usage example:
```
$ nix-shell -A shells.ghc

[nix-shell]$ hpack
package.yaml: Yaml file not found: package.yaml
```

**Comment by ElvishJerricco** [comment]
@ali-abrar `project` in `reflex-platform` also has `toolOverrides`, which I think is slightly better. Would be good to support that too.

**Comment by ElvishJerricco** [comment]
@ali-abrar I think `shellToolOverrides` is what I meant to type :P

**Comment by ali-abrar** [comment]
Added as of c91f143
