### ISSUE TITLE
thunk unpacking does not preserve semantics of ob run

### ISSUE THREAD

**Issue by maralorn** [obsidiansystems/obelisk#747]
Thanks to your recent fixes my `ob run` is now working again.

But after

    ob thunk unpack .obelisk/impl

I get

    common/src/Prelude.hs:73:1: error:
        Ambiguous module name ‘Data.String.Interpolate’:
          it was found in multiple packages:
          interpolate-0.2.0 string-interpolate-0.1.0.1
       |
    73 | import           Data.String.Interpolate        ( i )
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

I guess I can work around that myself. Probably your choice of interpolation lib is better than mine. But still I think this not something that should happen, should it?

**Comment by madeline-os** [comment]
There is a work-around for this, package-qualified imports: https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/package_qualified_imports.html

Since this is surprising, I will document it in the FAQ.
