### ISSUE TITLE
ghcide stopped working

### ISSUE THREAD

**Issue by srid** [obsidiansystems/obelisk#751]
I don't know how, but ghcide has stopped working on my obelisk project since some days ago. I see this in the Problems panel of vscode. Those errors are strange; it cannot match `Text` with itself; probably two `text` packages are being used somehow? FWIW, one of the dep thunks [itself uses reflex-platform](https://github.com/srid/neuron/blob/master/project.nix) ....

Cleaning up ./dist-newstyle had no effect.

![image](https://user-images.githubusercontent.com/3998/83082053-4ee9e280-a050-11ea-8450-b4718ac11ac2.png)

**Comment by kmicklas** [comment]
What happens if you run `ob shell ghcide`? That should help determine if it's a problem with ghcide, obelisk, or VS Code.

**Comment by srid** [comment]
It displays the same errors (and more). Closing, because I can't see what obelisk can do this fix this ...
