### ISSUE TITLE
Android back button doesn't do its thing

### ISSUE THREAD

**Issue by srid** [obsidiansystems/obelisk#754]
In the android app, I'd expect the back gesture (traditionally, the back button) to "go back" to the previous route, but the obelisk app does not respond to that gesture.

**Comment by ali-abrar** [comment]
@jecaro I believe this is fixed in reflex-dom 0.6.3.0 https://hackage.haskell.org/package/reflex-dom-0.6.3.0/changelog - for the moment you could override reflex-dom manually and try it. Obelisk should be getting an update to that version of reflex-dom soon.

**Comment by ali-abrar** [comment]
Here's a PR that includes reflex-dom 0.6.3.0: https://github.com/obsidiansystems/obelisk/pull/1045

**Comment by ali-abrar** [comment]
Fixed in https://github.com/obsidiansystems/obelisk/releases/tag/v1.2.0.0

**Comment by jecaro** [comment]
works fine thx :+1:
