### ISSUE TITLE
ob run loses GHC warnings

### ISSUE THREAD

**Issue by 3noch** [obsidiansystems/obelisk#76]
`ob run` does not show GHC warnings. Even if it did, the running app may produce logging output that could quickly hide them in the terminal window. This may indicate we need a different command that focuses on error reporting over running the app. Or we need something more advanced.

**Comment by ryantrinkle** [comment]
`ob run` should handle these situations.

**Comment by srid** [comment]
> the running app may produce logging output that could quickly hide them in the terminal window.

This is a general inconvenience with using ghcid and nothing specific to obelisk per se. I think obelisk could handle it better though; for example, `ob run` could _capture_ the standard output (of `frontend` and `backend` libraries) and display them somehow ensuring (not sure yet how) that it doesn't scroll out the ghcid output.

**Comment by ryantrinkle** [comment]
Yep.  This isn't a top priority, but it's well within the scope of `ob run`.

**Comment by 3noch** [comment]
Note that by default `ghcid` doesn't run the `--test` if there are warnings. This must be enabled with `-W`. A very simple (and also not very satisfactory) solution would be to remove that (see https://github.com/obsidiansystems/obelisk/blob/8dca44efd8b8b5d638b178c1be4ced9b3e3fd16c/lib/command/src/Obelisk/Command/Run.hs#L121) and/or provide an option for `ob run` that decides.

**Comment by 3noch** [comment]
#86 is a better title. ;)
