### ISSUE TITLE
libstore: nar-info-disk-cache.cc: Assertion `hashPart == storePathToHash(info->path)' failed. [

### ISSUE THREAD

**Issue by k-bx** [obsidiansystems/obelisk#768]
I was following zeus's installation instructions https://github.com/mightybyte/zeus , and when I got to obelisk installation I got this error:

```
$ nix-env -f https://github.com/obsidiansystems/obelisk/archive/master.tar.gz -iA command
installing 'obelisk-command-0.8.0.0'
nix-env: src/libstore/nar-info-disk-cache.cc:233: nix::NarInfoDiskCacheImpl::upsertNarInfo(const string&, const string&, std::shared_ptr<nix::ValidPathInfo>)::<lambda()>: Assertion `hashPart == storePathToHash(info->path)' failed.
[1]    2798858 abort (core dumped)  nix-env -f https://github.com/obsidiansystems/obelisk/archive/master.tar.gz  
```

Ubuntu 20.04.

Is there any more info I can provide to resolve this? Thank you!

**Comment by Ericson2314** [comment]
You'll want to try to to figure out which narinfo file/entry/whatever is hitting the assertion, so we can figure out whether it's a bug in Nix, corruption in somebodies cache whence the binaries are downloaded, or corruption just on your local machine.

**Comment by NinjaTrappeur** [comment]
FYI, I have been hitting the exact same issue: 

```
>> nix-build -A htop                                                                                                        
error: unexpected end-of-file


-------- From the daemon logs:

juin 21 09:57:05 xxx nix-daemon[1382]: accepted connection from pid 2826, user ninjatrappeur (trusted)
juin 21 09:57:05 xxx nix-daemon[1382]: nix-daemon: src/libstore/nar-info-disk-cache.cc:233: nix::NarInfoDiskCacheImpl::upsertNarInfo(const string&, const string&, std::shared_ptr<nix::ValidPathInfo>)::<lambda()>: Assertion `hashPart == storePathToHash(info->path)' failed.
juin 21 09:57:06 xxx systemd-coredump[2848]: Process 2843 (nix-daemon) of user 0 dumped core.
```

Removing @mightybyte's binary cache from my nix config fixed the issue. I'm not 100% sure what's happening here though :/

It seems like this assertion has recently been removed from Nix: https://github.com/NixOS/nix/commit/bbe97dff8b3054d96e758f486f9ce3fa09e64de3#diff-344e60954a1276f65f2d40b1b704030fR230

There's sadly no context regarding this particular assertion in the commit message.

**Comment by k-bx** [comment]
@NinjaTrappeur thank you, moving out the issue into https://github.com/mightybyte/zeus/issues/31 then
