### ISSUE TITLE
Utils.git ignores failing commands

### ISSUE THREAD

**Issue by srid** [obsidiansystems/obelisk#78]
For example,

```haskell
        git obImpl
        [ ["checkout", T.unpack gitBranch]
        , ["pull"]
        ]
```

If the `checkout` command fails, this merrily continues on without failing immediately.

**Comment by 3noch** [comment]
Here's why https://github.com/obsidiansystems/obelisk/blob/master/lib/command/src/Obelisk/Command/Utils.hs#L28

We should just get the `wrapProgram` stuff over so we can stop using the awkward nix-shell at runtime.
