### ISSUE TITLE
Publish Obelisk packages on Hackage

### ISSUE THREAD

**Issue by ingenieroariel** [obsidiansystems/obelisk#794]
Are there any plans to publish Obelisk's Haskell code on Hackage the way reflex-frp is published there?

This could provide a gentle path for people who like reflex-frp and want to try Routes or other components but do not want to lose control over how the code is deployed.

**Comment by madeline-os** [comment]
I can answer this question now: There is a long, long road where obelisk and its underlying dependencies can be more easily published outside of the mess of nix that keeps them stable. There is no specific plan, but it is a consideration that we take into account on a regular basis.
