### ISSUE TITLE
Unexpected implicit imports

### ISSUE THREAD

**Issue by rprije** [obsidiansystems/obelisk#795]
The `ob` command suite seems to implicitly load modules I don't ask for in my `.cabal` files.

For example, if I fail to add `jsaddle-dom` or `ghcjs-dom` to `frontend.cabal` and add this import to `frontend/src/Frontend.hs`:

```
import GHCJS.DOM.Document (getCookie, setCookie)
```

I get the following error in `ob run` and `ob repl`:

```
frontend/src/Frontend.hs:19:1: error:
    Ambiguous module name ‘GHCJS.DOM.Document’:
      it is bound as JSDOM.Generated.Document by a reexport in package jsaddle-dom-0.9.4.0
      it is bound as ghcjs-dom-0.9.4.0:GHCJS.DOM.Document by package ghcjs-dom-0.9.4.0
   |
19 | import           GHCJS.DOM.Document          (getCookie, setCookie)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Failed, three modules loaded.
```

For comparison, if I go into a nix shell with `ob shell` and run `cabal new-repl frontend` I get the sort of error I'm expecting:

```
src/Frontend.hs:19:1: error:
    Could not load module ‘GHCJS.DOM.Document’
    It is a member of the hidden package ‘jsaddle-dom-0.9.4.0’.
    Perhaps you need to add ‘jsaddle-dom’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘ghcjs-dom-0.9.4.0’.
    Perhaps you need to add ‘ghcjs-dom’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
   |
19 | import           GHCJS.DOM.Document          (getCookie, setCookie)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Failed, no modules loaded.
```

In this case I seem to have no way of importing `GHCJS.DOM.Document` that will satisfy tools such as `ob run` due to the conflicting implicit imports.

Another problem is that in cases where obelisk loads non-conflicting packages my failure to add the needed package to my `.cabal` file is hidden from me by tools such as `ob run` and I won't learn of my mistake until I try to build my package and encounter failures.

**Comment by 3noch** [comment]
How many `.cabal` or `package.yaml` files can be reached from your obelisk project? Obelisk tries to automatically load all source packages into the same session which can cause this kind of error. `ob run` etc have a `--no-interpret` option to disable this behavior for a given directory and it's children.

**Comment by 3noch** [comment]
At the very least obelisk should report what packages it's including in the session.

**Comment by 3noch** [comment]
(That is to say, that's an improvement we need that is already a result of your ticket regardless of what happens next.)

**Comment by rprije** [comment]
> How many `.cabal` or `package.yaml` files can be reached from your obelisk project? Obelisk tries to automatically load all source packages into the same session which can cause this kind of error. `ob run` etc have a `--no-interpret` option to disable this behavior for a given directory and it's children.

This was reproduced in a fresh, empty directory where I ran `ob init` and where the only change I made was to the `Frontend.hs` file. `ghcjs-dom` nor `jsaddle-dom` is not referenced by any file in the directory.

**Comment by 3noch** [comment]
@rprije Oh wow very odd. Can you tell me the contents of `.obelisk/impl/github.json`? Also, do you have ghcjs-dom or jsaddle-dom installed in some global package set perhaps for ghc or ghcjs?

**Comment by rprije** [comment]
Oh, I take it it doesn't behave the same way for you? That's troubling.

> @rprije Oh wow very odd. Can you tell me the contents of `.obelisk/impl/github.json`?

```
{
  "owner": "obsidiansystems",
  "repo": "obelisk",
  "branch": "master",
  "private": false,
  "rev": "4f2d3f1c1312d833ae814b7a86cf7b65ea0614ec",
  "sha256": "1shk8yy5pbakcw8aq6b8s3g2xblzf24l78mq0ca0asnvifnp83yb"
}
```

> Also, do you have ghcjs-dom or jsaddle-dom installed in some global package set perhaps for ghc or ghcjs?

No, this is a NixOS system which kept very clean with no global haskell environment other than a basic `ghc` with NixOS default packages and some tools like `cabal-install` and `hlint`. The ghc environment should be coming entirely from the nix closure described in the default Obelisk skeleton. The Obelisk command `ob` is coming from https://github.com/obsidiansystems/obelisk/archive/master.tar.gz.
which ends up in `/nix/store/gd99xxp41i5dllhpx341rxscgbyzlpqn-obelisk-command-0.8.0.0/bin/ob` in my Nix store.

For completeness:

```
$ ghc-pkg list | less
/nix/store/ng4jlh9dcbcihb9yb2f3x5bsacdpnj14-ghc-8.6.5/lib/ghc-8.6.5/package.conf.d
    Cabal-2.4.0.1
    array-0.5.3.0
    base-4.12.0.0
    binary-0.8.6.0
    bytestring-0.10.8.2
    containers-0.6.0.1
    deepseq-1.4.4.0
    directory-1.3.3.0
    filepath-1.4.2.1
    (ghc-8.6.5)
    ghc-boot-8.6.5
    ghc-boot-th-8.6.5
    ghc-compact-0.1.0.0
    ghc-heap-8.6.5
    ghc-prim-0.5.3
    ghci-8.6.5
    haskeline-0.7.4.3
    hpc-0.6.0.3
    integer-gmp-1.0.2.0
    libiserv-8.6.3
    mtl-2.2.2
    parsec-3.1.13.0
    pretty-1.1.3.6
    process-1.6.5.0
    rts-1.0
    stm-2.5.0.0
    template-haskell-2.14.0.0
    terminfo-0.4.1.2
    text-1.2.3.1
    time-1.8.0.2
    transformers-0.5.6.2
    unix-2.7.2.2
    xhtml-3000.2.2.1
```

**Comment by madeline-os** [comment]
I am closing with the understanding that the referenced, merged PR did fix this issue. Let me know if I am mistaken.
