### ISSUE TITLE
Android app opens all links in-app

### ISSUE THREAD

**Issue by srid** [obsidiansystems/obelisk#802]
I'd expect URLs to be opened in the browser, however even with `target=blank`, when the user taps them obelisk opens these URLs *in* the app itself. What's worse is that once the external page is loaded, there is no way whatsoever to go back to the app (swipe gesture does nothing). You have to completely quit the app and launch again.

**Comment by 3noch** [comment]
This is more properly an issue with reflex-platform since all the mobile integration is there. I think we may have a fix already incoming for this but I'd need to check.

**Comment by o1lo01ol1o** [comment]
Has there been any update on the state of this in `reflex-platform`?

**Comment by ali-abrar** [comment]
This is now the default behavior. This behavior is controlled by [MainWidget.java in reflex-dom](https://github.com/reflex-frp/reflex-dom/blob/develop/reflex-dom/java/org/reflexfrp/reflexdom/MainWidget.java#L88) and can be overridden in your application by setting `android.javaSources` as described [here](https://github.com/reflex-frp/reflex-platform/blob/develop/android/default.nix#L112-L119).
