### ISSUE TITLE
Disable Haddock for project componenets?

### ISSUE THREAD

**Issue by o1lo01ol1o** [obsidiansystems/obelisk#803]
I have a deployment that is failing because of a haddock error on my `frontend` component: 

```
haddock: internal error: internal: extractDecl
CallStack (from HasCallStack):
  error, called at utils/haddock/haddock-api/src/Haddock/Interface/Create.hs:1116:12 in main:Haddock.Interface.Create
builder for '/nix/store/b45i6fgbip5hsgzpkv9vabm4hhv10wcl-frontend-0.1.drv' failed with exit code 1
cannot build derivation '/nix/store/m392awlj9qnkryac43fvl0ams3l8nsmm-backend-0.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/l6np5wpyhwdk0vs6kh00yi1qjh9bqaiq-serverExe.drv': 1 dependencies couldn't be built
error: build of '/nix/store/l6np5wpyhwdk0vs6kh00yi1qjh9bqaiq-serverExe.drv' failed
```

I've encountered this error before on a `reflex-platform` project and ultimately had to disable haddocks on `frontend` as I was unable to pin down the source of the error.  

In the current project, I'm not quite sure what the problem is as I've removed all haddock markup (I believe . . .) from the `frontend` source tree.  

Is there a way to disable haddocks for components in the `serverExe` derivation in `obelisk`?

**Comment by o1lo01ol1o** [comment]
IIRC, my previous research ended at these two issues: 
- https://github.com/haskell/haddock/issues/979
- https://github.com/tomsmalley/semantic-reflex/issues/40

**Comment by alexfmpe** [comment]
I think you can use [`dontHaddock`](https://github.com/NixOS/nixpkgs/blob/32c8e793bce08a7ec53c9da4d3924a681173c1e0/pkgs/development/haskell-modules/lib.nix#L77) in the [overrides](https://github.com/obsidiansystems/obelisk#adding-package-overrides)
```
overrides = self: super: with pkgs.haskell.lib {
  ... 
  frontend = dontHaddock super.frontend;
  ...
}
```

**Comment by o1lo01ol1o** [comment]
Excellent, that was simpler than I had though.  Thanks!
