### ISSUE TITLE
Installation Issues on NixOs

### ISSUE THREAD

**Issue by adamConnerSax** [obsidiansystems/obelisk#82]
Installing on NixOs I had to set different environment variables for hub/git than described in the docs.
I had to set "GITHUB_USER" and "GITHUB_TOKEN" rather than "NIX_PRIVATE_GITHUB_USERNAME" and "NIX_PRIVATE_GITHUB_PASSWORD".  I figured this out by looking at the man pages for "hub" so it seems sensible.  But I am new to Nix and, obviously, to obelisk, so I am not sure I didn't miss something else that might have made the documented env vars work.

**Comment by 3noch** [comment]
`NIX_PRIVATE_GITHUB_*` is actually for nix's `fetchFromGitHub`. `hub` does not run inside a nix derivation and must learn of the credentials differently. We're hoping to improve the story for this, but currently nix's new `builtins.fetchGit` has some performance issue that need to be fixed or worked around.

However, you've hit upon something that is probably not communicated very well in the docs. `hub` is used for command-line operations that interact with your GitHub repo. `fetchFromGitHub` is used in the nix derivations that build the final deployment. Right now you need to set up both, one for CLI and one for things that actually build your project as a derivation for deployment to another NixOS machine.

**Comment by luigy** [comment]
`hub` dependency has been removed making installation even simpler
