### ISSUE TITLE
`nix-build -A exe` take very long time to run when there're many (about 1586) assets under static directory

### ISSUE THREAD

**Issue by TheKK** [obsidiansystems/obelisk#820]
Here's my obelisk version:
```json
{
  "owner": "obsidiansystems",
  "repo": "obelisk",
  "branch": "master",
  "private": false,
  "rev": "11beb6e8cd2419b2429925b76a98f24035e40985",
  "sha256": "0b4m33b7yyzsbkvfz2kwg4v9hlnvbjlmjikbvwd7pg52vy84and0"
}
```

AFAIK obelisk would create derivation for "every single" files under `static` directory, in my case that number is 1586.

Since I'd like to use [line awesome](https://icons8.com/line-awesome) for my project, is there anything I could do to improve the build/deploy time?

**Comment by rubenmoor** [comment]
I use a custom derivation to build static assets but during deployment, there is still a derivation built for every file. It takes about 20 minutes on my system for ~2000 files (font awesome and some flag icons). So this issue doesn't seem to be addressed by the custom static derivation.
