### ISSUE TITLE
Frontend.frontend is not in scope for "ob run"

### ISSUE THREAD

**Issue by mightybyte** [obsidiansystems/obelisk#838]
Steps to reproduce:

1. Install the latest obelisk with `nix-env -f https://github.com/obsidiansystems/obelisk/archive/master.tar.gz -iA command`
2. Initialize a new obelisk project with `ob init`
3. Set `.obelisk/impl/github.json` as follows:

```
{
  "owner": "obsidiansystems",
  "repo": "obelisk",
  "branch": "develop",
  "private": false,
  "rev": "ea9bede156262590249d879181a3b47ad1fae0cf",
  "sha256": "0cdrag2y3lq72c7dfm55b17n2d74j15ffrh2jqnbgyrvvb1856ki"
}
```

4. Run `ob run`

Expected outcome: The project builds and runs locally
Actual outcome: The project seems to build fine but then fails with the following error:

```
<interactive>:23:97-113: error:
    Not in scope: ‘Frontend.frontend’
    No module named ‘Frontend’ is imported.
```

Note that the above commit isn't quite the most recent commit on `develop`.  There have been two commits since then.  If I upgrade to the most recent commit (rev `53957d70d45fc8874bfbae2b35d3a42dc4477ac6`), `ob run` fails before building with:

```
error: Android builds are not supported on this platform.
ob: fd:12: hGetLine: end of file
```

**Comment by alexfmpe** [comment]
#843 is a possible fix for the second issue. I ran into something similar looking to the first which required mirroring the changes in
https://github.com/obsidiansystems/obelisk/commit/281195a17c67bd19da3e4c4a1833016dc627b448#diff-91d8d0b0349e1ac0a121404e1eef602f1e5c28a0684d61d5c24dd5614de41301

**Comment by emmanueldenloye** [comment]
I'm getting something similar.

```
<interactive>:23:109-123: error:
    Not in scope: ‘Backend.backend’
    No module named ‘Backend’ is imported.

...done
````

Unfortunately, I'm not able to modify my `.obelisk/impl/github.json`. It is currently


```
{
  "owner": "obsidiansystems",
  "repo": "rhyolite",
  "branch": "develop",
  "private": false,
  "rev": "799db20745c337446b45bca720c9b454a93eb9e7",
  "sha256": "05my3ipzbaf85gjhjwf86qkwhsscq499w5p1msn5r9l6r18hmfgf"
}
```

**Comment by ali-abrar** [comment]
@mightybyte can you try now that #843 is merged?

**Comment by mightybyte** [comment]
@ali-abrar I'm still seeing the same behavior.  To test, I started with the steps to reproduce above and got the same outcome.  Then I ran `nix-thunk update .obelisk/impl`.  After this, `.obelisk/impl/github.json` contained this:

```
{
  "owner": "obsidiansystems",
  "repo": "obelisk",
  "branch": "develop",
  "private": false,
  "rev": "60d56bc119a52ba8bcd6cd847d70edfaf781e60a",
  "sha256": "1ld36axr4wkdvyalsa4lvvjd4f9v3r4828j3p1nbxph9iafqfw2c"
}
```

Running `ob run` with this change resulted in the same error.  Then I ran `nix-env -f https://github.com/obsidiansystems/obelisk/archive/master.tar.gz -iA command` to see if that made a difference.  After that, `ob run` still gave the same error.  Then I ran `nix-env -f https://github.com/obsidiansystems/obelisk/archive/develop.tar.gz -iA command` and again got the same error from `ob run`.

**Comment by alexfmpe** [comment]
Between current master and current develop there was a change to the way static assets are loaded. 
It seems to me that'd require a manual [migration](https://github.com/obsidiansystems/obelisk/commit/281195a17c67bd19da3e4c4a1833016dc627b448#diff-874f33563125619a7a5cb567ebe523c59258662d69858d78d24d947b275f9c6cR8) if you're going from old skeleton to new obelisk.
Maybe that's what you're hitting and ghcid is scrolling too much or something, hiding the root error?

**Comment by ohri-anurag** [comment]
@mightybyte I tried running `ob init` and then changed my `.obelisk/impl/github.json` to both the versions that you've mentioned previously, one by one.

In both cases, when I ran `ob run`, it ran successfully. Are you still facing this issue?

**Comment by madeline-os** [comment]
Hi @mightybyte , could you please try running `ob run -v` and paste the log?

**Comment by romefeller** [comment]
This issue is being tackled on PR #934.
