### ISSUE TITLE
How can I switch to a different version of reflex-platform?

### ISSUE THREAD

**Issue by rubenmoor** [obsidiansystems/obelisk#840]
I tried already to check out a local copy of obelisk and then I manipulated `dep/reflex-platform/github.json` ... re-installed that local profile via `nix-env -f . -iA command`, but to know avail. It isn't clear to me, at what point in the process `reflex-platform` gets built or anything. `ob run` does not seem to that, either.

**Comment by alexfmpe** [comment]
The installed `ob` will quickly handoff control to your project's obelisk - you probably want to change the reflex-platform version in `.obelisk/impl` - see https://github.com/obsidiansystems/obelisk/blob/master/CONTRIBUTING.md#hacking-on-obelisk-from-within-an-obelisk-project

**Comment by kmicklas** [comment]
You can override the reflex-platform that obelisk uses by passing `reflex-platform-func` to `import ./.obelisk/impl { ... }`.

**Comment by rubenmoor** [comment]
Indeed, this is well documented already. I failed to find `.obelisk`. Thanks
