### ISSUE TITLE
regular dependency "persistent" fails: do not know how to unpack source archive

### ISSUE THREAD

**Issue by rubenmoor** [obsidiansystems/obelisk#847]
To me, persistent is just any package from hackage. Does it need special treatment?

**Comment by rubenmoor** [comment]
I added `persistent = self.callHackage "persistent" "2.9.2" {};` to the `default.nix` as a workaround; see below. That specific version works and is required for working with `persistent-mysql`.

```
# FILE: default.nix
# ...
with obelisk;
project ./. ({ ... }: {
  android.applicationId = "systems.obsidian.obelisk.examples.minimal";
  android.displayName = "Obelisk Minimal Example";
  ios.bundleIdentifier = "systems.obsidian.obelisk.examples.minimal";
  ios.bundleName = "Obelisk Minimal Example";
  # using hlsSupport (pull request) of reflex-platform
  # shellToolOverrides = ghc: super: { haskell-language-server = unstable.haskell-language-server; };
  overrides = self: super: {
    servant-snap = (import ./dep/servant-snap) self super;
    hspec-snap = (import ./dep/hspec-snap) self super;
    servant-reflex = self.callPackage ../servant-reflex {};
    # persistent = self.callPackage ../persistent/persistent {};
    persistent = self.callHackage "persistent" "2.9.2" {};
  };
})
```

**Comment by ali-abrar** [comment]
When you were getting the "do not know how to unpack source archive" error, did you have any mention of persistent in your default.nix, or was it just in a cabal file?

**Comment by rubenmoor** [comment]
The error is caused when I put persistent in my .cabal file only

**Comment by rubenmoor** [comment]
persistent-2.9.2 isn't in the nixpkgs. `callHackage` only works for haskell package versions that are also in nixpkgs. I would need `callHackageDirect` to select arbitrary haskell packages.
