### ISSUE TITLE
Usage example for `Obelisk.ExecutableConfig`

### ISSUE THREAD

**Issue by rubenmoor** [obsidiansystems/obelisk#848]
There is [basic documentation here](https://github.com/obsidiansystems/obelisk/blob/master/lib/executable-config/README.md).

However, I can only find an outdated example in ` qfpl / reflex-realworld-example` and w/o some example, I am still puzzled about how to pass configuration to my obelisk backend. I want to specify a mysql host, database, user, and password this way.

**Comment by ali-abrar** [comment]
[Here's an up-to-date example](https://github.com/obsidiansystems/obelisk-examples/blob/master/executable-config/README.md)

**Comment by ali-abrar** [comment]
The json example is probably appropriate for your use case.

**Comment by rubenmoor** [comment]
That is indeed what I was looking for!
