### ISSUE TITLE
How to get the current time `IO (UTCTime)` in the frontend?

### ISSUE THREAD

**Issue by rubenmoor** [obsidiansystems/obelisk#849]
I feel, this shouldn't be difficult, but I am perplexed that when using `prerender` for this, I get a `Dynamic` while `prerender_` discards the result entirely.

Is there a obelisk way of getting the current time?

**Comment by xplat** [comment]
How is the UTCTime value going to be used?

When the server statically renders the frontend, the UTCTime it
retrieves will differ from the current time when the frontend "hydrates"
the page.

Depending on how the time value is being used, you could:

* Use one of the functions in Reflex.Time
* Use a `performEvent` to retrieve the current time. The post-build
  event (produced by `getPostBuild`) could be used. E.g.:

```haskell
pb <- getPostBuild
t :: Event t UTCTime <- performEvent $ ffor pb $ const $ liftIO getCurrentTime
```

* Use prerender (though it sounds like that's what you're already doing
  - you could continue building the time-dependent widgets in the
    prerender block, and that would spare you from having to deal with
    the Dynamic).

**Comment by rubenmoor** [comment]
Your suggestion here is exactly what I need.

    pb <- getPostBuild
    -- `fmap const` can be replaced by $>
    postBuildTime <- performEvent $ pb $> liftIO getCurrentTime

`performEvent` seems to be quite handy.

**Comment by rubenmoor** [comment]
I ran into new trouble regarding this and asked on stackoverflow:

https://stackoverflow.com/questions/66820112/how-to-set-input-value-to-current-day-in-reflex

Somehow, the combination of my `postBuildTime` event with `inputElementConfig_setValue` does not work.

**Comment by ali-abrar** [comment]
This may be due to [this issue](https://github.com/reflex-frp/reflex-dom/pull/400/files).
> I ran into new trouble regarding this and asked on stackoverflow:
> 
> https://stackoverflow.com/questions/66820112/how-to-set-input-value-to-current-day-in-reflex
> 
> Somehow, the combination of my `postBuildTime` event with `inputElementConfig_setValue` does not work.

**Comment by rubenmoor** [comment]
I have a minimal working example (well, based on `ob run`, thus not quite minimal) in which I selected the `ts-ssr-value` branch for `reflex-dom` but the issue persists.

Cf. https://github.com/rubenmoor/reflex-bug-pbtime/tree/ts-ssr-value
