### ISSUE TITLE
Secure websockets broken on Safari 13 and iOS 13

### ISSUE THREAD

**Issue by o1lo01ol1o** [obsidiansystems/obelisk#851]
When deploying an obelisk project that relies on letsencrypt secure websockets are broken on Safari and iOS.  Safari gives the helpful `[Error] WebSocket network error: The operation couldn’t be completed. (OSStatus error -9824.) (x17478)` and debugging iOS webviews in the console show the same. 

Some cursory googling suggests more strict protocols are needed when connecting over wss using iOS / Safari, see [here](https://developer.apple.com/forums/thread/132286) for example.  

Unfortunately as far as the recommended fix is concerned, I'm unable to figure out compatible `reflex-platform` pins as `Must-Staple` was added in https://github.com/NixOS/nixpkgs/commit/c16f2218da6928ca52bb500cbebe4c62a67f90f8 (March 3rd, 2020) but the pin of OS's fork of nixpkgs (Aug, 2020) does not appear to include that commit: https://github.com/obsidiansystems/nixpkgs/blob/reflex-platform/nixos/modules/security/acme.nix.

I'm not even sure if ocsp must-staple will fix this problem but if someone can point out an appropriate pin of nixpkgs / reflex-platform to use, I'll try that.

**Comment by ali-abrar** [comment]
Fixed in a previous nixpkgs bump.
