### ISSUE TITLE
`nix-build` and `ob deploy` stuck after hours

### ISSUE THREAD

**Issue by rubenmoor** [obsidiansystems/obelisk#855]
My CPU had a 100% load while I tried to build. Below the output of `ob deploy push -v`, after about 8 hours.

I don't know what part of that process I am in, at that point. Maybe it's the closure compiler?

```
$ ob deploy push -v     

Starting Obelisk </nix/store/d6a5hld8kz92dcrgvzdfbmbl1vs5am9j-obelisk-command-0.9.0.1/bin/.ob-wrapped> args=["deploy","push","-v"] logging-level=Debug
Thunk specification git-v5 did not match "./.obelisk/impl": ReadThunkError_MissingPaths ("./.obelisk/impl/thunk.nix" :| [])
Thunk specification github-v5 did not match "./.obelisk/impl": ReadThunkError_MissingPaths ("./.obelisk/impl/thunk.nix" :| [])
Thunk specification git-v4 did not match "./.obelisk/impl": ReadThunkError_FileDoesNotMatch "./.obelisk/impl/default.nix" "# DO NOT HAND-EDIT THIS FILE\nlet fetch = {url, rev, branch ? null, sha256 ? null, fetchSubmodules ? false, private ? false, ...}:\n  let realUrl = let firstChar = builtins.substring 0 1 url; in\n    if firstChar == \"/\" then /. + url\n    else if firstChar == \".\" then ./. + url\n    else url;\n  in if !fetchSubmodules && private then builtins.fetchGit {\n    url = realUrl; inherit rev;\n    ${if branch == null then null else \"ref\"} = branch;\n  } else (import <nixpkgs> {}).fetchgit {\n    url = realUrl; inherit rev sha256;\n  };\nin import (fetch (builtins.fromJSON (builtins.readFile ./git.json)))"
Thunk specification github-v4 did not match "./.obelisk/impl": ReadThunkError_FileDoesNotMatch "./.obelisk/impl/default.nix" "# DO NOT HAND-EDIT THIS FILE\nlet fetch = { private ? false, fetchSubmodules ? false, owner, repo, rev, sha256, ... }:\n  if !fetchSubmodules && !private then builtins.fetchTarball {\n    url = \"https://github.com/${owner}/${repo}/archive/${rev}.tar.gz\"; inherit sha256;\n  } else (import <nixpkgs> {}).fetchFromGitHub {\n    inherit owner repo rev sha256 fetchSubmodules private;\n  };\nin import (fetch (builtins.fromJSON (builtins.readFile ./github.json)))"
Thunk specification git-v3 did not match "./.obelisk/impl": ReadThunkError_FileDoesNotMatch "./.obelisk/impl/default.nix" "# DO NOT HAND-EDIT THIS FILE\nlet fetch = {url, rev, ref ? null, sha256 ? null, fetchSubmodules ? false, private ? false, ...}:\n  let realUrl = let firstChar = builtins.substring 0 1 url; in\n    if firstChar == \"/\" then /. + url\n    else if firstChar == \".\" then ./. + url\n    else url;\n  in if !fetchSubmodules && private then builtins.fetchGit {\n    url = realUrl; inherit rev;\n  } else (import <nixpkgs> {}).fetchgit {\n    url = realUrl; inherit rev sha256;\n  };\nin import (fetch (builtins.fromJSON (builtins.readFile ./git.json)))"
Thunk specification github-v3 did not match "./.obelisk/impl": ReadThunkError_FileDoesNotMatch "./.obelisk/impl/default.nix" "# DO NOT HAND-EDIT THIS FILE\nlet\n  fetch = { private ? false, ... }@args: if private && builtins.hasAttr \"fetchGit\" builtins\n    then fetchFromGitHubPrivate args\n    else (import <nixpkgs> {}).fetchFromGitHub (builtins.removeAttrs args [\"branch\"]);\n  fetchFromGitHubPrivate =\n    { owner, repo, rev, branch ? null, name ? null, sha256 ? null, private ? false\n    , fetchSubmodules ? false, githubBase ? \"github.com\", ...\n    }: assert !fetchSubmodules;\n      builtins.fetchGit ({\n        url = \"ssh://git@${githubBase}/${owner}/${repo}.git\";\n        inherit rev;\n      }\n      // (if branch == null then {} else { ref = branch; })\n      // (if name == null then {} else { inherit name; }));\nin import (fetch (builtins.fromJSON (builtins.readFile ./github.json)))"
Thunk specification git-v2 did not match "./.obelisk/impl": ReadThunkError_FileDoesNotMatch "./.obelisk/impl/default.nix" "# DO NOT HAND-EDIT THIS FILE\nlet fetchGit = {url, rev, ref ? null, branch ? null, sha256 ? null, fetchSubmodules ? null}:\n  if builtins.hasAttr \"fetchGit\" builtins\n    then builtins.fetchGit ({ inherit url rev; } // (if branch == null then {} else { ref = branch; }))\n    else abort \"Plain Git repositories are only supported on nix 2.0 or higher.\";\nin import (fetchGit (builtins.fromJSON (builtins.readFile ./git.json)))"
Thunk specification github-v2 did not match "./.obelisk/impl": ReadThunkError_FileDoesNotMatch "./.obelisk/impl/default.nix" "# DO NOT HAND-EDIT THIS FILE\nimport ((import <nixpkgs> {}).fetchFromGitHub (\n  let json = builtins.fromJSON (builtins.readFile ./github.json);\n  in { inherit (json) owner repo rev sha256;\n       private = json.private or false;\n     }\n))"
Thunk specification git-v1 did not match "./.obelisk/impl": ReadThunkError_FileDoesNotMatch "./.obelisk/impl/default.nix" "# DO NOT HAND-EDIT THIS FILE\nlet fetchGit = {url, rev, ref ? null, branch ? null, sha256 ? null, fetchSubmodules ? null}:\n  assert !fetchSubmodules; (import <nixpkgs> {}).fetchgit { inherit url rev sha256; };\nin import (fetchGit (builtins.fromJSON (builtins.readFile ./git.json)))"
Thunk specification github-v1 did not match "./.obelisk/impl": ReadThunkError_FileDoesNotMatch "./.obelisk/impl/default.nix" "import ((import <nixpkgs> {}).fetchFromGitHub (builtins.fromJSON (builtins.readFile ./github.json)))"
Creating process: nix-build ./.obelisk/impl -A command --no-out-link
✔ Built on ./.obelisk/impl [command]
Handing off to /nix/store/d6a5hld8kz92dcrgvzdfbmbl1vs5am9j-obelisk-command-0.9.0.1/bin/ob
Starting Obelisk </nix/store/d6a5hld8kz92dcrgvzdfbmbl1vs5am9j-obelisk-command-0.9.0.1/bin/.ob-wrapped> args=["--no-handoff","deploy","push","-v"] logging-level=Debug
Thunk specification git-v5 did not match "/home/ruben/code/podcast/deployment/src": ReadThunkError_UnrecognizedPaths ("/home/ruben/code/podcast/deployment/src/github.json" :| [])
Thunk specification github-v5 matched "/home/ruben/code/podcast/deployment/src"
Creating process: nix-build /home/ruben/code/podcast/deployment/src -A server.system --argstr hostName ec2-18-193-59-202.eu-central-1.compute.amazonaws.com --argstr adminEmail ruben.moor@gmail.com --argstr routeHost podcast-staging.rubenmoor.net --argstr version b7a7c5922a0b2b0f09f65958b9a38840ab8986b2 --arg enableHttps true --arg module $'import /home/ruben/code/podcast/deployment/module.nix' --no-out-link
building '/nix/store/lqwxnvxxbgfvxx009rdki2xdigx42k3x-clay-0.13.3-js-unknown-ghcjs.drv'...
building '/nix/store/gc0xx3nmn9jzpzdz2hc3p8q78qcs87xm-obelisk-generated-static-0-js-unknown-ghcjs.drv'...
building '/nix/store/zsn6xxvq3r7v0rk7sh4h1hl403ana8zj-raw-strings-qq-1.1-js-unknown-ghcjs.drv'...
copying path '/nix/store/z6r4sxaqky3gg61ispa7v66hz2cyq7v2-unordered-containers-0.2.10.0-js-unknown-ghcjs-doc' from 'https://nixcache.reflex-frp.org'...

Running nix-build on /home/ruben/code/podcast/deployment/src [server.system]
```

**Comment by rubenmoor** [comment]
I realize, it could also be an issue with `obelisk-generated-static`. But I have a mere 21 MB of static files, of which 20 MB is Fontawesome.

**Comment by rubenmoor** [comment]
I eliminated the `Fontawesome` folder from `static/` and I eliminated `raw-strings-qq`. I don't know if any one of those two is the culprit, because now the build process gets stuck with `clay`. I am currently trying a fresh `ob init` to find a version of `clay` that actually works. `clay-0.13.1` is marked broken, anyway. So far the versions `0.13.1` and `0.13.3` on a fresh obelisk project cause the build process to hang. Maybe someone here managed to get obelisk running with `clay`. I continue trial and error with different versions.

**Comment by rubenmoor** [comment]
It looks like even if I get `clay` to build (console says "installing") I get stuck in the process thereafter, just like described above.

**Comment by rubenmoor** [comment]
On the way of build the static-files app, I get 1550 entries in /nix/store of the form

/nix/store/SOMEHASH-hashFile.drv

At the moment there 1550 entries, but it's still counting up. What's the origin of these derivations? It seems, there is something wrong.

**Comment by rubenmoor** [comment]
I didn't mention explicitly, but of course for all the packages that seemingly cause trouble when I try to build via `nix-build` or `ob deploy`, the command `ob run` works w/o any problem. Maybe someone can point out to me what structural difference might cause the failure in the actual built, when `ob run` works fine.

**Comment by rubenmoor** [comment]
Could this be related to the fact that I am build on NixOS rather than some other distro only using nix? It doesn't seem anyone else is experiences such severe problems moving from `ob run` to `nix-build`.

**Comment by rubenmoor** [comment]
I finally solved the problem by moving to a conventional hard drive. My nvme drive caused locking issues that I couldn't fix.

**Comment by jmininger** [comment]
@rubenmoor I ran into the same issue where the daemon gets stuck trying to acquire locks on ghcjs builds. I was using a "conventional hard drive". I was able to fix it by bumping my `nixos-20.09` branch to `ac60476ed94fd5424d9f3410c438825f793a8cbb` and garbage collecting. Worth noting for documentation purposes that I had the same issue with the ob skeleton. I am still not entirely sure what the cause was. How did you come to the conclusion that it was your harddrive?

**Comment by rubenmoor** [comment]
I encountered the problem on two different machines that had the nvme disk in common and once I moved over to a conventional hard drive, the problem was gone. There shouldn't be an issue with nvme drives, per se, but this is how I solved the problem for now. I will definitely check out the commit your mentioned:

https://github.com/flyingcircusio/nixpkgs/commit/ac60476ed94fd5424d9f3410c438825f793a8cbb

Do you have information on how this locking problem got potentially fixed?

**Comment by jmininger** [comment]
To be clear the commit was just the newest on the nixos-20.09 branch. It doesn't necessarily point to the fix. I was on a feb version of that branch/channel. So i imagine there was something in between that got tweaked and fixed it

**Comment by rubenmoor** [comment]
Amazing, I ran `nix-channel --update` and verified the channel with `nix-version`. I am on that ac60476 commit now and everything works. It looks like, indeed, my hardware did not have anything to with it after all. It just happens that whatever locking issue there was with ghcjs has been fixed in one of the more recent commits. I just happened to try out that other hard drive at the same time.

I know for sure that the fix is recent, because I did a fresh install of nixos on that other nvme drive ... and I do run `nix-channel --update` regularly, anyway.

**Comment by joehealy** [comment]
Having spent the night with this (or a very similar issue) and also having it appear to be solved by a nix-channel update and rebuild, I noticed the first thing that was updated was the version of nix. Is there a dependency on a certain version/bugfix of nix itself?
