### ISSUE TITLE
About Reflex.Dom tickLossy in obelisk

### ISSUE THREAD

**Issue by MurakamiKennzo** [obsidiansystems/obelisk#856]
Hi, I just use obelisk init to create a simple app. and I wanna passing current time to tickLossy :

```hs
frontend :: Frontend (R FrontendRoute)
frontend = Frontend
  { _frontend_head = do
      el "title" $ text "Obelisk Minimal Example"
      elAttr "link" ("href" =: static @"main.css" <> "type" =: "text/css" <> "rel" =: "stylesheet") blank
  , _frontend_body = do
      el "div" $ do
        new <- liftIO getCurrentTime
        evTick <- tickLossy 3 new
        let evTime = (T.pack . show . _tickInfo_n) <$> evTick
        dynText =<< holdDyn "No ticks yet" evTime
      return ()
  }
```

and I know due to [this](https://github.com/obsidiansystems/obelisk/issues/502) so I can't using liftIO in this monad, but is there a way to using current UTCtime in the code?

**Comment by Yasuke** [comment]
You just need to do the IO action inside a prerender where you are guaranteed to have IO/JS support.

Something like: 

```haskell
_frontend_body = do
  el "div" $ do
    dETick <- prerender (return never) $ do
      eTick <- tickLossy 3 new
      return $ T.pack . show . _tickInfo_n <$> eTick
   dynText =<< holdDyn "No Ticks Yet" $ switchDyn $ dETick
```
This way you still display "No Ticks Yet" when the page loads, and when the JS takes over the page it will switch to sending the ticks.

**Comment by Yasuke** [comment]
Though if you wanna start ticking right away you can use something like tickLossyFromPostBuildTime and save yourself the call to get the current time

**Comment by rubenmoor** [comment]
https://github.com/obsidiansystems/obelisk/issues/849#issuecomment-808289990

This is how I get the current time using the post-build-event, the "current time" being the post-build-time, really. If you need the current time in the sense of app-loading-time (before the building finishes), you can run `getCurrentTime` in `main` before any obelisk code and pass the time to the obelisk frontend code as an argument.

**Comment by MurakamiKennzo** [comment]
> You just need to do the IO action inside a prerender where you are guaranteed to have IO/JS support.
> 
> Something like:
> 
> ```haskell
> _frontend_body = do
>   el "div" $ do
>     dETick <- prerender (return never) $ do
>       eTick <- tickLossy 3 new
>       return $ T.pack . show . _tickInfo_n <$> eTick
>     dynText =<< holdDyn "No Ticks Yet" $ switchDyn $ dETick
> ```
> 
> This way you still display "No Ticks Yet" when the page loads, and when the JS takes over the page it will switch to sending the ticks.

Thanks from reply. Cheers👍!

btw, you may forgot the parentheses. I succeed ny this:
```hs
frontend :: Frontend (R FrontendRoute)
frontend = Frontend
  { _frontend_head = do
      el "title" $ text "Obelisk Minimal Example"
      elAttr "link" ("href" =: static @"main.css" <> "type" =: "text/css" <> "rel" =: "stylesheet") blank
  , _frontend_body = do
      el "div" $ do
        dETick <- prerender (return never) $ do
          new <- liftIO getCurrentTime
          eTick <- tickLossy 3 new
          return $ T.pack . show . _tickInfo_n <$> eTick
        dynText =<< (holdDyn "No Ticks Yet" $ switchDyn $ dETick)
      return ()
  }
```

**Comment by Yasuke** [comment]
Ah yes good catch! Glad you got it working

**Comment by MurakamiKennzo** [comment]
> [#849 (comment)](https://github.com/obsidiansystems/obelisk/issues/849#issuecomment-808289990)
> 
> This is how I get the current time using the post-build-event, the "current time" being the post-build-time, really. If you need the current time in the sense of app-loading-time (before the building finishes), you can run `getCurrentTime` in `main` before any obelisk code and pass the time to the obelisk frontend code as an argument.

I try it before, this actual way is I don't know how to lift IO or using IO in the ObeliskWidget(In my eyes, IO is the bottom monad and not extract😊).

and I see tickLossy code using it:
```hs
tickLossy :: (PostBuild t m, PerformEvent t m, TriggerEvent t m, MonadIO (Performable m), MonadFix m) => NominalDiffTime -> UTCTime -> m (Event t TickInfo)
tickLossy dt t0 = tickLossyFrom dt t0 =<< getPostBuild
```
@Yasuke the way is a good solution.❤️
