### ISSUE TITLE
Is Nix a requirement?

### ISSUE THREAD

**Issue by chespinoza** [obsidiansystems/obelisk#864]
Cant find a way to try obelisk without Nix, what about if I'm not interested in using Nix then what should I do? 
Thanks.

**Comment by cgibbard** [comment]
Obelisk is mostly an easy to use wrapper around a bunch of Nix scripts, so it's hard to imagine what this would mean. You can use all the underlying Haskell libraries, like reflex and reflex-dom on their own, though Obelisk is a very convenient way to get started.

Note that you *don't* need to use NixOS to install the Nix package manager and use its build system.

**Comment by TheKK** [comment]
It's like asking to build an npm project without npm. It's not impossible thought.

In the obelisk case you'll need a bunch of libraries and executables (especially GHCJS) to build/develop an reflex application, so if you put these requirements on you system correctly then yes, nix would become optional. But the reality is that it's tedious (and might be very hard) to get the environment right by hand, and that's the process nix trying to simplify and stabilize.

If you really don't want to install `nix` on your system, perhaps you could give [nix's docker image](https://hub.docker.com/r/nixpkgs/nix) a try?

(BTW, by the design of nix, almost everything nix installed will locate at `/nix` directory, so it is super easy to remove every-nix-thing when you don't need them anymore)
