### ISSUE TITLE
Is MacOS no longer supported?

### ISSUE THREAD

**Issue by santiweight** [obsidiansystems/obelisk#869]
As of MacOS Big Sur I get the following error:

`ld: file not found: /usr/lib/system/libcache.dylib for architecture x86_64
`
when adding any dependency to my obelisk project. That's the weird part to me - the minimal ob init project works just fine, but adding any dependency to any cabal file causes the following stack trace:

```
[1 of 1] Compiling Main             ( Setup.hs, /private/tmp/nix-build-hscolour-1.24.4.drv-0/Main.o )
Linking Setup ...
ld: file not found: /usr/lib/system/libcache.dylib for architecture x86_64
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
`cc' failed in phase `Linker'. (Exit code: 1)
builder for '/nix/store/81sjwgpi807wiwzq66qyrji2gb74ysqr-hscolour-1.24.4.drv' failed with exit code 1
```

There is an issue here already. It really sucks for me because I am trying to revive old code, but I am unable to use nix/ob. I wonder if this is a nix issue? But I imagine some of Obsidian's engineers use MacOS - how do you handle Big Sur?

Relevant issue - https://github.com/obsidiansystems/obelisk/issues/832

**Comment by o1lo01ol1o** [comment]
It looks like this is an upstream issue in nixpkgs: https://github.com/NixOS/nixpkgs/issues/91748.  To fix it, obelisk and `reflex-dom` will need to be moved to a more recent nixpkgs pin (`21.05`?) to use a more recent linker.

**Comment by Ericson2314** [comment]
Thanks @o1lo01ol1o for investigating. We have indeed started bumping obelisk and reflex platform to get to a newer Nixpkgs, but it is a slog.

**Comment by o1lo01ol1o** [comment]
@Ericson2314 I've started to backport an existing fix to the `reflex-platform-20.09` branch of nixpkgs: https://github.com/BeFunctional/nixpkgs/tree/reflex-platform-20.09-backport-big-sur. I'm currently building the world, but if it works out I'll open a PR.

**Comment by o1lo01ol1o** [comment]
Attempting to use the above pins on https://github.com/obsidiansystems/obelisk/pull/867 built quite a bit and then failed to find Cocoa when building ob command.  This appears to be https://gitlab.haskell.org/ghc/ghc/-/issues/18446.  

I'm rolling the dice and trying to build off https://github.com/obsidiansystems/obelisk/tree/ll/ghc8_10 now but I have no idea what the state is of the ghc 8.10 work in obelisk (or reflex-platform for that matter).

**Comment by santiweight** [comment]
Wow thank you for the awesome investment into this issue @o1lo01ol1o 

I think there is already a good amount of work invested into ghc-8.10 on both reflex-platform and obelisk (I'm not an Obsidian employee however), so I wonder whether it might be more profitable to push that effort, since I get the impression that 8.6.5 is soon to breathe its last breaths (my impression from obelisk/HLS/other OSS work)

**Comment by o1lo01ol1o** [comment]
@Ericson2314 Just checking to see if this issue is stale.  We don't currently have a mac on big sur +; have you had any luck building obelisk there?

**Comment by madeline-os** [comment]
@o1lo01ol1o thank you for the prodding. We are indeed still looking into this issue. I will update this issue when I have a better picture of the state of obelisk on darwin.

**Comment by augyg** [comment]
It may be important to note for this thread that Mac M2's are now released and nix throws a warning / error to set the NIXPKGS_ALLOW_UNSUPPORTED_SYSTEMS (If i remember right) variable and nixpkgs issues involving M2 seem to be plentiful. No idea how this will exactly affect Obelisk + Reflex-Platform

**Comment by ali-abrar** [comment]
macOS is supported, and aarch64 macs should be supported once #1046 lands
