### ISSUE TITLE
Android Build error ARMV7A

### ISSUE THREAD

**Issue by MurilloFlorent** [obsidiansystems/obelisk#876]
when I'm going to build a build for android, this error appears... does anyone know how to solve it?

error: attributes 'armv7a' missing
         at /nix/store/bblbjmnzfib5q0r7xbk1c920bsabbw-source/pkgs/development/tools/build-managers/meson/default.nix:84:21

![error arm](https://user-images.githubusercontent.com/73268358/145033148-6ed6b9e8-8e39-420d-a1ca-9fc7f1a800bb.png)

**Comment by fendor** [comment]
Hello!

Thank you for your bug report!

I tried reproducing your issue with the obelisk skeleton project and the following versions:
NixOS: nixpkgs-22.05
Obelisk: master (https://github.com/obsidiansystems/obelisk/commit/e3ec75f6988eed47189dd20f8c8514748b33ea81) and develop (https://github.com/obsidiansystems/obelisk/commit/1e357e1e965d876a36eafa1631e365b7df24c274)

All versions seem to work fine, and I was able to deploy the android build to my phone.

Is this issue still relevant, or can you share more information about your project?

**Comment by ali-abrar** [comment]
arm v7 is no longer supported, due to [this issue](https://gitlab.haskell.org/ghc/ghc/-/issues/17973)
