### ISSUE TITLE
"ob deploy push" doesn't activate config changes

### ISSUE THREAD

**Issue by mightybyte** [obsidiansystems/obelisk#894]
If you deploy with `ob deploy push`, then make a change to something in `config`, then `ob deploy push` again, the new config changes don't seem to take effect in the deployed app.

**Comment by mankyKitty** [comment]
We've seen the `rsync` fail when moving config due to permissions being incorrectly set on the target server. Have you confirmed the app restarted to reload the new configuration? If the app is processing a request or unable to quit for some reason then the restart won't happen.

**Comment by madeline-os** [comment]
I am closing this as a duplicate of #372 . This issue is a real pain. I expect to have a solution to propose this week.
