### ISSUE TITLE
hostName for ec2 instance in conflict with nix requirements

### ISSUE THREAD

**Issue by rubenmoor** [obsidiansystems/obelisk#897]
I deploy according to the instructions for the "Default EC2 Instance":

Thus:

    SERVER=ec2-35-183-22-197.ca-central-1.compute.amazonaws.com

in 

    ob deploy init --hostname $SERVER ...
    
And upon `ob deploy push -v`, I get

    error: The option value `networking.hostName' in `<unknown-file>' is not of type `string matching the pattern ^$|^[[:alnum:]]([[:alnum:]_-]{0,61}[[:alnum:]])?$'.

I found a discussion of the hostName specs here:

https://github.com/NixOS/nixpkgs/issues/94011

but no solution for my case.

**Comment by rubenmoor** [comment]
this is how i fixed the issue for now:

https://github.com/obsidiansystems/obelisk/pull/898

**Comment by o1lo01ol1o** [comment]
@rubenmoor Did #898 successfully generate LetsEncrypt certificates for your deployment?

**Comment by rubenmoor** [comment]
> @rubenmoor Did #898 successfully generate LetsEncrypt certificates for your deployment?

https://palantype.com/ works with SSH, so I conclude that my certificates were not affected.

**Comment by o1lo01ol1o** [comment]
Yes, https works, so that's all good.  Thanks!

**Comment by bitdizzy** [comment]
#911 should have resolved this issue. Let me know if it persists. Note that the fix is currently only in `develop`. We intend to cut a release branch soon, and it will contain this fix.

**Comment by madeline-os** [comment]
https://github.com/obsidiansystems/obelisk/pull/911 should have resolved this issue. Let me know if it persists. Note that the fix is currently only in develop. We intend to cut a release branch soon, and it will contain this fix.
