### ISSUE TITLE
Unable to install obelisk on Monterey

### ISSUE THREAD

**Issue by dmitrydidi** [obsidiansystems/obelisk#902]
`nix-env -f https://github.com/obsidiansystems/obelisk/archive/master.tar.gz -iA command `
 then
 ....
```
checking for dllwrap... no
checking for -objdump... no
checking for objdump... no
checking XCode version... ./configure: line 5201: xcodebuild: command not found
not found (too old?)
checking for x86_64-apple-darwin-gcc... /nix/store/j0c81x7653h5jz2299rjd4b55rqhplq6-clang-wrapper-7.1.0/bin/cc
checking whether the C compiler works... no
configure: error: in `/private/tmp/nix-build-ghc-8.6.5.drv-0/ghc-8.6.5':
configure: error: C compiler cannot create executables
See `config.log' for more details
error: builder for '/nix/store/k16hfmqgpzg01rwc62d943rdzdd5zsmm-ghc-8.6.5.drv' failed with exit code 77
error: 1 dependencies of derivation '/nix/store/qq4ic3ly1x0q3qsg03hwx8b2656vswfz-obelisk-command-0.9.0.1.drv' failed to build
```
Did anybody had the same ?

**Comment by mankyKitty** [comment]
My mac isn't upgraded to Monterey yet, but this line:
```
checking XCode version... ./configure: line 5201: xcodebuild: command not found
```
Seems important ... Have you installed/updated and agreed to all the licences for XCode ? I have memories of that being a sticking point for automated builds on OSX...

**Comment by augyg** [comment]
@dmitrydidi Can you advise whether or not you have an M1 or Intel chip? 

I have just been able to reproduce this error myself and I have an Intel chip with Monterey

**Comment by augyg** [comment]
This problem does not happen when binary caches are added, so that ghc does not need to be built from source. So I am closing this issue.

**Comment by augyg** [comment]
@dmitrydidi Do let us know though if this issue does in fact persist and we will work with you to solve the issue.
