### ISSUE TITLE
ob --verbose invalid character failure

### ISSUE THREAD

**Issue by TravisCardwell** [obsidiansystems/obelisk#908]
Some `ob` commands fail with an error like the following when using the `--verbose` option.

```
$ ob --verbose run
Starting Obelisk </nix/store/ndgqr350z5rnr58wd70nwkzjg9847nxq-obelisk-command-0.9.0.1/bin/.ob-wrapped> args=["--verbose","run"] logging-level=Debug
Thunk specification git-v5 did not match "./.obelisk/impl": ReadThunkError_UnrecognizedPaths ("./.obelisk/impl/github.json" :| [])
Thunk specification github-v5 matched "./.obelisk/impl"
./.obelisk/impl: command not cached, building ...
Creating process: nix-build ./.obelisk/impl -A command --out-link ./.obelisk/impl/.attr-cache/command.out
DONE Built on ./.obelisk/impl [command]
Handing off to ./.obelisk/impl/.attr-cache/command.out/bin/ob
Starting Obelisk </nix/store/ndgqr350z5rnr58wd70nwkzjg9847nxq-obelisk-command-0.9.0.1/bin/.ob-wrapped> args=["--no-handoff","--verbose","run"] logging-level=Debug
Finding packages with root "." and interpret paths:

ob: <stdout>: commitAndReleaseBuffer: invalid argument (invalid character)
```

Here are the commands that I have been able to recreate this error with:

| Command      | Error |
| :----------- | :---: |
| `ob init`    |       |
| `ob deploy`  |       |
| `ob run`     | :x:   |
| `ob profile` |       |
| `ob thunk`   |       |
| `ob repl`    | :x:   |
| `ob watch`   | :x:   |
| `ob shell`   | :x:   |
| `ob doc`     | :x:   |
| `ob hoogle`  |       |

The commands work fine without `--verbose`.

----

Environment:

```
$ nix-env --query
nix-2.7.0
obelisk-command-0.9.0.1
$ locale
LANG=en_US.UTF-8
LC_CTYPE=ja_JP.UTF-8
LC_NUMERIC=ja_JP.UTF-8
LC_TIME=ja_JP.UTF-8
LC_COLLATE=ja_JP.UTF-8
LC_MONETARY=ja_JP.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_PAPER=ja_JP.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=ja_JP.UTF-8
LC_TELEPHONE=ja_JP.UTF-8
LC_MEASUREMENT=ja_JP.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

Steps to reproduce:

```
$ mkdir /tmp/reflex-demo
$ cd /tmp/reflex-demo
$ ob init
$ ob --verbose run
```

Possibly related issues:

* #335

**Comment by TravisCardwell** [comment]
I investigated the `ob run` case and found the cause of the error on the Haskell side.  The [drawPathTree][] function makes use of Unicode box-drawing characters.  When printed using `putLog Debug`, the command fails with the "invalid character" error.  Replacing these characters with ASCII allows the command to progress.

[drawPathTree]: <https://github.com/obsidiansystems/obelisk/blob/e3ec75f6988eed47189dd20f8c8514748b33ea81/lib/command/src/Obelisk/Command/Run.hs#L129-L138>

I confirmed that printing the same characters to my terminal using the following program works fine outside of Nix.

```haskell
{-# LANGUAGE OverloadedStrings #-}

module Main (main) where

import Control.Monad (when)
import Control.Monad.Catch (bracket_)
import Control.Monad.IO.Class (MonadIO(liftIO))
import Data.Text (Text)
import qualified Data.Text.IO as T
import System.Console.ANSI
  ( ConsoleIntensity(FaintIntensity), SGR(Reset, SetConsoleIntensity), hSetSGR
  )
import System.IO (Handle, stdout)

main :: IO ()
main = putStrWithSGR debugColors stdout True "└─├│"
  where
    debugColors = [SetConsoleIntensity FaintIntensity]

------------------------------------------------------------------------------
-- FROM lib/cliapp/src/Obelisk/CliApp/TerminalString.hs

-- | Safely print the string with the given ANSI control codes, resetting in the end.
putStrWithSGR :: MonadIO m => [SGR] -> Handle -> Bool -> Text -> m ()
putStrWithSGR sgr h withNewLine s = liftIO $ bracket_ (hSetSGR h sgr) reset $ T.hPutStr h s
  where
    reset = hSetSGR h [Reset] >> newline -- New line should come *after* reset (to reset cursor color).
    newline = when withNewLine $ T.hPutStrLn h ""
```

Wondering if it might be a terminfo issue, I exported `TERM=xterm` and tried again, but it fails with the same error.

I have not investigated the other commands.  If only using ASCII is easier than fixing the Nix side, the following command can be used to search for all non-ASCII characters in Haskell source files.

```bash
find . -type f -name '*.hs' | xargs grep -P -Hn "[^\x00-\x7F]"
```

**Comment by TravisCardwell** [comment]
This error occurs when the locale(s) specified by the `LANG` and `LC_CTYPE` environment variables are not available.  This happens when using a non-NixOS Linux distribution when the locale(s) specified by the environment variables are not available in Nix, even if they are available in the host OS.

One way to work around the issue is to set the above environment variables to `C.UTF-8`.  Another way to work around the issue is to use the [`LOCALE_ARCHIVE`][] environment variable.  The documentation indicates that it exists to provide a way to specify a locale archive when using different versions of `glibc`, but it can also be used to point to a locale archive on the host system, usually located at `/usr/lib/locale/locale-archive`.

[`LOCALE_ARCHIVE`]: <https://nixos.org/manual/nixpkgs/unstable/#locales>

Technically, this is a general Nix issue.  If it is preferred, I am happy to simply add some documentation to the README or FAQ to help others who run into it while using Obelisk.

It is also possible to implement a fix in Obelisk.  If the locale is not used anyway, then the simplest thing to do is to set the above locale environment variables to `C.UTF-8` when the program runs.  The values have already been read by the time the Haskell code runs, but the changes are effective after hand-off, and the program can be re-executed in the `--no-handoff` case.  I tested this, and you can see the code in the (second) commit referenced above.

A more involved hack could be used to avoid always setting the locale to `C.UTF-8`.  Here is some pseudo-code for the general idea:

```
if LOCALE ARCHIVE is not set:
  if /usr/lib/locale/locale-archive exists:
    set LOCALE_ARCHIVE to /usr/lib/locale/locale-archive
  else:
    setLocaleC (from the above commit)
```

With this logic, users can avoid any automatic changes by making sure that the `LOCALE_ARCHIVE` environment variable is set.  Otherwise, the program sets `LOCALE_ARCHIVE` if a host locale archive is found, allowing users to run with their preferred locale, assuming that the host locale archive is compatible with the version of `glibc` used within Nix.  If all else fails, the locale environment variables are set to `C.UTF-8`.  Note that hand-off or re-execution is still required.  I have not implemented this, but I am happy to do so if it is preferred.

Yet another option is to add all locales to Obelisk.  I have not tried this, but the documentation indicates that this consumes about 100MB of drive space.

**Comment by romefeller** [comment]
I had this same bug. I am taking a look.

**Comment by romefeller** [comment]
Weeks ago I had the same error.
$ locale
LANG=pt_BR.UTF-8
LANGUAGE=pt_BR:pt:en
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC="pt_BR.UTF-8"
LC_TIME="pt_BR.UTF-8"
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY="pt_BR.UTF-8"
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER="pt_BR.UTF-8"
LC_NAME="pt_BR.UTF-8"
LC_ADDRESS="pt_BR.UTF-8"
LC_TELEPHONE="pt_BR.UTF-8"
LC_MEASUREMENT="pt_BR.UTF-8"
LC_IDENTIFICATION="pt_BR.UTF-8"
LC_ALL=

The command "export LANG=C.UTF-8" fixed it and I stopped worrying about it. I will review your proposed solution to make a PR. Thank you for addressing that.

**Comment by madeline-os** [comment]
For reference https://github.com/NixOS/nixpkgs/issues/64603#issuecomment-551419489

**Comment by Ericson2314** [comment]
https://www.extrema.is/blog/2022/04/09/nix-terminfo-and-locale-archive was a nice blog post, BTW, @TravisCardwell
