### ISSUE TITLE
How to use ghc-8.10.7

### ISSUE THREAD

**Issue by santiweight** [obsidiansystems/obelisk#935]
I see that the develop branch supports ghc-8.10.7. I had 8.10.7 working on some old ghc-8.10 branch.

However, when I:
 - unpack my .obelisk/impl thunk
 - checkout origin/develop in that thunk
 - pack the same thunk
 - ob shell etc.

instead of using 8.10, it appears to use 8.6. I can't really use 8.6 (it would incur too much of a burden on me). Is there any way to make obelisk use 8.10?

Thanks for any help you can give! Paging @madeline-os because she appears to have been working on these problems a lot.

**Comment by madeline-os** [comment]
Thanks for reaching out. We are actively working on making this easier, as it is quite fragile right now. We need to ensure that supporting multiple GHC versions does not impact users, and we have to devise a policy for long term compiler version support, so that users are not blindsided by forced upgrades. I will let you know when the work has been merged.

**Comment by santiweight** [comment]
Thanks for the very quick response. Is there anyway I could try experimental branches? I am recovering an old project, but am not interested in recovering the project twice (once in 8.6; once in 8.10). I would be quite happy to report any bugs I experience there/upstream any fixes.

**Comment by madeline-os** [comment]
I know that someone has successfully used https://github.com/obsidiansystems/obelisk/tree/ll/ghc8_10-wip . However, I am doubtful that it works out of the box and cannot guarantee success. If you can wait a week, the situation may be better.

**Comment by mankyKitty** [comment]
As a follow up, we've been working on this and we have a couple more hurdles to clear, then we'll be cutting a new release that includes GHC 8.10 support.

**Comment by santiweight** [comment]
Thanks all :) This work would really help me!

**Comment by madeline-os** [comment]
Fresh in `develop` as of #917 , you can now use ghc 8.10. If you run into any problems, please report them to the issue tracker!

Instructions here: https://github.com/obsidiansystems/obelisk/tree/develop#using-ghc-810
