### ISSUE TITLE
Logs are delayed on deployed server 

### ISSUE THREAD

**Issue by augyg** [obsidiansystems/obelisk#941]
While working on updating configs, the logs were quite delayed. If a request was made at 10:00 am (for example) and journalctl was used directly after, or even 10-20 minutes after in some cases, then logs show zero activity despite this being verifiably untrue. 

`-bash-4.4# sudo journalctl -u backend --since "10m ago"                                                                                                                                                                                       
-- Logs begin at Mon 2022-05-09 21:01:42 UTC, end at Fri 2022-06-24 20:23:50 UTC. --                                                                                                                                                          
-- No entries --                                                                             
`

This happens using the recommended AMI, [here](https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#LaunchInstanceWizard:ami=ami-00a8eeaf232a74f84)

**Comment by madeline-os** [comment]
This is likely caused by buffering. You can set it to `LineBuffering` like here in your app, if you want logs to be more prompt: https://github.com/obsidiansystems/obelisk/blob/d779d5ab007d8ee5c3cd3400473453e1d106f5f1/lib/backend/src/Obelisk/Backend.hs#L122
