### ISSUE TITLE
Closure compiler bug

### ISSUE THREAD

**Issue by p3rsik** [obsidiansystems/obelisk#954]
Hello!

We faced this [issue](https://github.com/google/closure-compiler/issues/3720) when trying to build our obelisk project. 
We're compressing the js code like this:

```
compressedJs = frontend: optimizationLevel: pkgs.runCommand "compressedJs" {} ''
     set -euo pipefail
     cd '${haskellLib.justStaticExecutables frontend}'
     shopt -s globstar
     for f in **/all.js; do
       dir="$out/$(basename "$(dirname "$f")")"
       mkdir -p "$dir"
       ln -s "$(realpath "$f")" "$dir/all.unminified.js"
       ${if optimizationLevel == null then ''
         ln -s "$dir/all.unminified.js" "$dir/all.js"
       '' else ''
         '${pkgs.closurecompiler}/bin/closure-compiler' --externs '${reflex-platform.ghcjsExternsJs}' -O '${optimizationLevel}'
           --jscomp_warning=checkVars --warning_level=QUIET --create_source_map="$dir/all.js.map" --source_map_format=V3 
           --js_output_file="$dir/all.js" "$dir/all.unminified.js"
         echo '//# sourceMappingURL=all.js.map' >> "$dir/all.js"
       ''}
     done
    '';
```

If we turn the warning level to `QUIET`, then everything works just fine.

The error: 
![image](https://user-images.githubusercontent.com/8962864/182134224-7b71ca77-e5a4-435d-8cbe-53aa90709089.png)

I'm not including the steps to reproduce the bug, since it appears to be a floating bug, that I can't 100% reproduce. There is also an explanation of how and why it occurs in the CC issue provided above, please look there for the details. 

For the record:
I did try it with the newest version of CC and it still sometime appears, right now we're using this version of cc:
```
[nix-shell:~/work/organized-siphonophore]$ closure-compiler --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20200719
Built on: 2020-07-20 22:40
```

There are a few questions I would like to ask:
1) Is this a known issue and if so, does anybody know how to solve this?
2) Is turning the warning level to `QUIET` could potentially break something now or in the future for us?

Edit:
I'm not sure which version of obsidian package we use, we followed the official installation guide for the NixOS.

**Comment by madeline-os** [comment]
Squelching warnings by setting to `QUIET` should be fine. I'm not sure if this issue has been found in the wild for obelisk before. Thank you for the issue report!
