### ISSUE TITLE
Don't use canonicalizePath to locate migrations

### ISSUE THREAD

**Issue by srid** [obsidiansystems/obelisk#98]
Alternatives:

- `runCommand ... ''wrapProgram originalob MIGRATIONS=${path/to/src/migrations}''`
- symlink to the migrations directory from the wrapping ob

Probably the former.

**Comment by danharaj** [comment]
Consider using template haskell to load the migration graph at compile time.

**Comment by luigy** [comment]
Closing this since migrations have been deferred for now
